### ISSUE TITLE
Icecream can't detect when scheduler comes online

### ISSUE THREAD

**Issue by krf** [icecc/icecream#107]
Easy to reproduce with the Icecream Monitor:
- Make sure icecc scheduler is offline
- Start the monitor
- Now start the scheduler
- Monitor still thinks we're "offline", i.e. there's no scheduler

Do I have to change something in the monitors polling routine? See `IcecreamMonitor::slotCheckScheduler()` for reference. I'm unsure if this is a bug on my side or in libicecc (that is, `comm.cpp`)

Note: Both using master branches of icecream and icemon.
Note: I'm about to finally release the Qt only, Qt5-based version of the monitor, and this is a release blocker.

Thanks

**Comment by HenryMiller1** [comment]
There was a pull request on this, and no further comment in almost 2 years.  Assuming this is fixed
