### ISSUE TITLE
ccache keeps icecc warnings and errors as part of the compilers output

### ISSUE THREAD

**Issue by calvaris** [icecc/icecream#112]
I commented this issue on the ccache bugzilla and they gave me this answer:

https://bugzilla.samba.org/show_bug.cgi?id=10923

I think it would be really interesting that IceCream could support this.

**Comment by cwgreene** [comment]
Can you provide a test case for this?

**Comment by calvaris** [comment]
It is easier to reproduce that I thought.

1. Ensure that you have ccache installed and properly prepared to work with your compiler (either clang or gcc will work).

$ ls -lash /usr/lib/ccache/clang
0 lrwxrwxrwx 1 root root 16 Mai 31 19:58 /usr/lib/ccache/clang -> ../../bin/ccache

$ export CCACHE_PREFIX=icecc
$ export ICECC_VERSION=lol
$ /usr/lib/ccache/clang -c test.c # being test.c a valid C file
ICECC[12991] 10:21:46: $ICECC_VERSION has to point to an existing file to be installed lol

The you can call the command again and will get the same output even when icecc is not even invoked because the file is retrieved from the cache.

$ /usr/lib/ccache/clang -c test.c # being test.c a valid C file
ICECC[12991] 10:21:46: $ICECC_VERSION has to point to an existing file to be installed lol

The idea is that the second command should print out only the possible warnings/errors that the compiler gave, but it does not make sense that it prints out IceCC information cause it is irrelevant at the point and misleading (it might make you think that it is recompiling something when it is really getting it from the cache).

**Comment by HenryMiller1** [comment]
> ccache sets the environment variable called UNCACHED_ERR_FD to a file descriptor to which distcc sends error messages it does not want to be cached by ccache

Unfortunately icercream logging (services/logging.cpp) uses C++ iostreams.  From what I can tell there is no portable way to go from a file descriptor to an iostream.  There is a gcc extension in libstdc++, but that will not work on OSX, I'm not sure what the situation is on *BSD.  My autotools foo is not strong enough to implement the required checks to make this work in linux without breaking everything else.

**Comment by llunak** [comment]
Should be handled now, with the above commit.
