### ISSUE TITLE
"scheduler not yet found" in iceccd log

### ISSUE THREAD

**Issue by dagger-nn** [icecc/icecream#115]
I use RHEL 6.1 as a icecc daemon and RHEL 6.2 as a icecc scheduler. After iceccd start the multiple lines are appeared in iceccd log:

9341] 18:48:00: scheduler is on 192.168.1.42:8765 (net )
[9341] 18:48:00: scheduler not yet found.
[9341] 18:48:03: reconn Node Name: hostname

All builds are local. I've disabled iptables on both sides but result is still the same. I have a secondary icecc-scheduler running on other host. It works perfectly but when I try to connect icecc daemon from RHEL 6.1 host the result is also negative. What can be possible reason for this?

**Comment by llunak** [comment]
The message now says "scheduler not yet found/selected". As long as the daemon eventually connects this is harmless.
