### ISSUE TITLE
Freed pointer passed as an argument

### ISSUE THREAD

**Issue by garima-g** [icecc/icecream#117]
icecream version 1.0.1
File: daemon/main.cpp

In method handle_activity() at line number 1370, 
ret = handle_file_chunk_env(client, msg);
Here, handle_file_chunk_env frees client and freed pointer 'client' is passed as an argument to other functions (like handle_compile_file(), handle_transfer_env(), handle_get_cs()).
handle_file_chunk_env also frees msg and freed pointer msg is dereferenced at statement switch(msg->type) at line number 1377.

Suggested patch:
![patch2](https://cloud.githubusercontent.com/assets/10647613/5878853/0d2f4a4a-a350-11e4-932c-0ca21376cf07.jpg)

**Comment by garima-g** [comment]
Hi reviewers and maintainers, kindly review this patch and let me know in case of any issues or suggestion.

**Comment by HenryMiller1** [comment]
I'd like to see some sort of test that shows how this can happen.  (I haven't figured out the icecc tests enough to make this happen though)

**Comment by garima-g29** [comment]
Hi, I found this issue using static tool.

**Comment by coolo** [comment]
the error is real from what I can see, but the fix is wrong.

ret = false means success, so the if is the right way around. deleting the msg is correct too, no idea why handle_file_chunk_env deletes the msg *sometimes*. That's the problem IMO
