### ISSUE TITLE
RFE: don't accept jobs when running on battery power

### ISSUE THREAD

**Issue by michich** [icecc/icecream#133]
This is an idea from Arun Raghavan (https://bugzilla.redhat.com/show_bug.cgi?id=1229618):

> It would be nice if iceccd on laptops only runs when we are on A/C power.
> We probably don't want random compile jobs to be scheduled on our laptop
> when we're running on battery.

**Comment by aAlexanderUtsch** [comment]
Until this is part of iceccd I am using following workaround on Fedora 23:

I've created a `udev` rule in `/etc/udev/rules.d/99-icecream-on-battery.rules`:
```
SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_ONLINE}=="0", RUN+="/usr/bin/systemctl stop iceccd.service"
SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_ONLINE}=="1", RUN+="/usr/bin/systemctl start iceccd.service"
```

After a system restart (or triggering to reload the udev rules: `sudo udevadm control --reload`) systemd now stops `iceccd` whenever I am running on battery and starts it again as soon as my laptop is powered by A/C power.

**Comment by llunak** [comment]
I've thought about this and I consider the "workaround" to be actually a proper solution. Detecting whether running on batter is non-trivial (differs on different platforms, for example), and some people might not want it, plus some people might ask for other reactions to system events, and it's simply not Icecream's job. So an outside tool controlling Icecream this way looks like a simple and correct solution.
