### ISSUE TITLE
clang: error: no such file or directory: '2'

### ISSUE THREAD

**Issue by ldjhust** [icecc/icecream#146]
Hi, guys!
I'm using icecc's clang compiler with xcodebuild, but get below error, i don't know why, can anyone help me? Very thank you!

---

Build settings from command line:
    CC = /usr/local/opt/icecream/libexec/icecc/bin/clang
    SDKROOT = iphonesimulator9.2

=== BUILD TARGET Helloworld OF PROJECT Helloworld WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-all-non-framework-target-headers.hmap
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-project-headers.hmap
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-generated-files.hmap
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld.hmap
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-all-target-headers.hmap
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-own-target-headers.hmap
/bin/mkdir -p /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386
write-file /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/Helloworld.LinkFileList

Create product structure
/bin/mkdir -p /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator/Helloworld.app

CompileC build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/AppDelegate.o Helloworld/AppDelegate.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/leodjli/Documents/Objc_Workspacks/Helloworld
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/llvm/bin"
    /usr/local/opt/icecream/libexec/icecc/bin/clang -x objective-c -arch i386 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/1k/jzxhk8ss1fngznxk01w_ckq00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.2 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-generated-files.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-own-target-headers.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-all-target-headers.hmap -iquote /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-project-headers.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator/include -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/DerivedSources/i386 -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/DerivedSources -F/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/AppDelegate.d --serialize-diagnostics /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/AppDelegate.dia -c /Users/leodjli/Documents/Objc_Workspacks/Helloworld/Helloworld/AppDelegate.m -o /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/AppDelegate.o

CompileC build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/main.o Helloworld/main.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/leodjli/Documents/Objc_Workspacks/Helloworld
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/llvm/bin"
    /usr/local/opt/icecream/libexec/icecc/bin/clang -x objective-c -arch i386 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/1k/jzxhk8ss1fngznxk01w_ckq00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.2 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-generated-files.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-own-target-headers.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-all-target-headers.hmap -iquote /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-project-headers.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator/include -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/DerivedSources/i386 -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/DerivedSources -F/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/main.d --serialize-diagnostics /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/main.dia -c /Users/leodjli/Documents/Objc_Workspacks/Helloworld/Helloworld/main.m -o /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/main.o

CompileC build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/ViewController.o Helloworld/ViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/leodjli/Documents/Objc_Workspacks/Helloworld
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/llvm/bin"
    /usr/local/opt/icecream/libexec/icecc/bin/clang -x objective-c -arch i386 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/1k/jzxhk8ss1fngznxk01w_ckq00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.2 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-generated-files.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-own-target-headers.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-all-target-headers.hmap -iquote /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Helloworld-project-headers.hmap -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator/include -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/DerivedSources/i386 -I/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/DerivedSources -F/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/ViewController.d --serialize-diagnostics /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/ViewController.dia -c /Users/leodjli/Documents/Objc_Workspacks/Helloworld/Helloworld/ViewController.m -o /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/ViewController.o

Ld build/Debug-iphonesimulator/Helloworld.app/Helloworld normal i386
    cd /Users/leodjli/Documents/Objc_Workspacks/Helloworld
    export IPHONEOS_DEPLOYMENT_TARGET=9.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/llvm/bin"
    /usr/local/opt/icecream/libexec/icecc/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -L/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator -F/Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator -filelist /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/Helloworld.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.2 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -dependency_info -Xlinker /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Helloworld.build/Debug-iphonesimulator/Helloworld.build/Objects-normal/i386/Helloworld_dependency_info.dat -o /Users/leodjli/Documents/Objc_Workspacks/Helloworld/build/Debug-iphonesimulator/Helloworld.app/Helloworld
clang: error: no such file or directory: '2'

*\* BUILD FAILED **

The following build commands failed:
    Ld build/Debug-iphonesimulator/Helloworld.app/Helloworld normal i386
(1 failure)

**Comment by chironyf** [comment]
I met the same problem with yours. Did you resolved it?? This is my [description](https://github.com/icecc/icecream/issues/416).

**Comment by llunak** [comment]
If this is still valid, please try with a more recent icecream version. If the problem persists, please use ICECC_DEBUG=debug to get log information about the problem. Given that this is old, closing, but feel free to reopen.
