### ISSUE TITLE
feature request: add an icecc-sheduler option to reject iceccd versions that are too old

### ISSUE THREAD

**Issue by mostynb** [icecc/icecream#150]
1.1rc2 now has split-dwarf support, but it is not safe to use on a possibly mixed version icecc network- pre 1.1rc2 iceccd's don't support split-dwarf debug symbols, and will force clients attempting to use this into local compilation.  Therefore, I think it would be useful to have an icecc-scheduler option to reject such iceccd versions, with a useful message, eg something like "Connection rejected- icecc version X or later is required with this scheduler".

I suppose that an icecc-scheduler command line option to set MIN_PROTOCOL_VERSION would suffice.  Would such a patch be welcome?

**Comment by johnmiked15** [comment]
That's not entirely true. The communication protocol has a version built in and is communicated between the scheduler and various daemons.

I increased the protocol version for -gsplit-dwarf to 35 and made it backward compatible. What this means is that using a new (1.1rc2 or newer) client and daemon locally will let you use the flag when doing local jobs, and will attempt to tell other daemons that are protocol version 35 or newer to do so as well. If it happens to hit a daemon with an older version, the file will still compile, it just won't use -gsplit-dwarf. The returned object file will still work fine, it just won't be split like others would be.

An older local client and daemon will just build everything that has that flag locally as it did before.

That said, an *optional* command line flag or environment variable for the scheduler to enforce a minimum protocol version for connecting daemons is not a terrible idea.

**Comment by mostynb** [comment]
It seems that I misunderstood by debug build logs- when building with -gsplit-dwarf and the job is sent to a version of iceccd that doesn't support this option, ccache sees that the .dwo file is missing and then calls icecc again (after a "Failed; falling back to running the real compiler" log message).  While not as bad as compiling locally, it's could still be a significant performance hit.

Here's an excerpt from my ccache.log for a minimal test case:
[2016-04-17T20:33:19.328294 22056] Executing /usr/bin/icecc /usr/bin/g++ -gsplit-dwarf -c -o hello.o /home/user/.ccache/tmp/hello.stdout.foo.22056.lwEEhG.ii
[2016-04-17T20:33:19.359688 22056] Unlink /home/user/.ccache/8/f/e4076d68053a760b3c7634807a8c60-17491.o.tmp.stdout.foo.22056.RpZYDN
[2016-04-17T20:33:19.359839 22056] Unlink /home/user/.ccache/8/f/e4076d68053a760b3c7634807a8c60-17491.o.tmp.stderr.foo.22056.xHQ9jR.2
[2016-04-17T20:33:19.359873 22056] Compiler didn't produce a split dwarf file
[2016-04-17T20:33:19.359898 22056] Using command-line prefix icecc
[2016-04-17T20:33:19.359905 22056] Failed; falling back to running the real compiler
[2016-04-17T20:33:19.359911 22056] Executing /usr/bin/icecc /usr/bin/g++ -c hello.cc -gsplit-dwarf

I will experiment with adding a minimum protocol version command line arg, and see how that works.

**Comment by bluGill** [comment]
Perhaps it would be better tell the scheduler not to give less than version 35 clients when that option is sent. That way someone who can't install a newer client for some reason isn't rejected. 

On April 17, 2016 1:43:07 PM CDT, mostynb <notifications@github.com> wrote:
>It seems that I misunderstood by debug build logs- when building with
>-gsplit-dwarf and the job is sent to a version of iceccd that doesn't
>support this option, ccache sees that the .dwo file is missing and then
>calls icecc again (after a "Failed; falling back to running the real
>compiler" log message).  While not as bad as compiling locally, it's
>could still be a significant performance hit.
>
>Here's an excerpt from my ccache.log for a minimal test case:
>[2016-04-17T20:33:19.328294 22056] Executing /usr/bin/icecc
>/usr/bin/g++ -gsplit-dwarf -c -o hello.o
>/home/user/.ccache/tmp/hello.stdout.foo.22056.lwEEhG.ii
>[2016-04-17T20:33:19.359688 22056] Unlink
>/home/user/.ccache/8/f/e4076d68053a760b3c7634807a8c60-17491.o.tmp.stdout.foo.22056.RpZYDN
>[2016-04-17T20:33:19.359839 22056] Unlink
>/home/user/.ccache/8/f/e4076d68053a760b3c7634807a8c60-17491.o.tmp.stderr.foo.22056.xHQ9jR.2
>[2016-04-17T20:33:19.359873 22056] Compiler didn't produce a split
>dwarf file
>[2016-04-17T20:33:19.359898 22056] Using command-line prefix icecc
>[2016-04-17T20:33:19.359905 22056] Failed; falling back to running the
>real compiler
>[2016-04-17T20:33:19.359911 22056] Executing /usr/bin/icecc
>/usr/bin/g++ -c hello.cc -gsplit-dwarf
>
>I will experiment with adding a minimum protocol version command line
>arg, and see how that works.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/icecc/icecream/issues/150#issuecomment-211078306

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mostynb** [comment]
Preliminary pull-request here:
https://github.com/icecc/icecream/pull/151

@bluGill in my opinion it would be better if the scheduler admin could force clients to upgrade (if they want to continue using that particular scheduler).  Otherwise, it would be difficult for clients to know how many usable nodes are available, and consequently how many simultaneous compile jobs to spawn.  This could force lots of local compile jobs if the client picks a number that is too large for the number.  Note that my pull-request does not prevent old clients from connecting, it just gives the scheduler admin the option to do so at runtime instead of compile time.

**Comment by coolo** [comment]
This sounds backward to me. You want your client not to talk to version 34, that I can understand. But still in a mixed version farm it should still be possible to use version 30 features. What we miss instead IMO is considering that one *job* is *requiring* version 35 and as such only wants to schedule it on daemons supporting it. The same client might still have version 34 jobs.

**Comment by mostynb** [comment]
I think there's value in both allowing the scheduler admin to choose to operate either a non-mixed protocol version network (or a more restricted protocol version range), and handling mixed protocol version networks better.  This feature/pull request only deals with the former (since it benefits my use case more), but I can possibly look into the latter in a separate task.

**Comment by coolo** [comment]
but if you want a non-mixed protocol version network, why have the admin know something as concrete as the internal protocol version (you have to read the sources to get it actually).

For your user story, a --only-allow-newest-protocol sounds more appropriate

**Comment by mostynb** [comment]
An --only-allow-newest-protocol flag would work for my use case, but I would probably still need to read the source code to figure out which client versions are acceptable.  Which option flag would you prefer?  

Either way, we could add some documentation of protocol versions in README.md.

**Comment by HenryMiller1** [comment]
I like --only-allow-newest-protocol better.  

However I only see this as a useful flag for force upgrades, which is different from the problem at hand. when we go to protocol 36 you still only need 35, and might not care to force the upgrade.

**Comment by johnmiked15** [comment]
Actually I think this is the best. It's on a per-job basis, and will tell the scheduler to only send jobs with debug fission enabled on them to compile servers that are at least protocol version 35.

Thoughts?

```diff
diff --git a/client/remote.cpp b/client/remote.cpp
index 82b145c..250ef47 100644
--- a/client/remote.cpp
+++ b/client/remote.cpp
@@ -711,11 +711,16 @@ maybe_build_local(MsgChannel *local_daemon, UseCSMsg *usecs, CompileJob &job,
 }

 // Minimal version of remote host that we want to use for the job.
-static int minimalRemoteVersion( const CompileJob& )
+static int minimalRemoteVersion( const CompileJob& job)
 {
     int version = MIN_PROTOCOL_VERSION;
-    if( ignore_unverified())
+    if (ignore_unverified()) {
         version = max( version, 31 );
+    }
+
+    if (job.dwarfFissionEnabled()) {
+        version = max( version, 35 );
+    }
     return version;
 }
```

**Comment by coolo** [comment]
The remaining question is if the user story of forced upgrades is valid outside of this context

**Comment by mostynb** [comment]
@johnmiked15's patch looks good, without something like this icecc can produce different output to local compile jobs, which is bad.  But I still think it is useful for the scheduler admin to have the option of requiring support for a particular protocol version.

For example: say you run the scheduler for a reasonable sized network, where the daemons are all locally administered by the user of each individual pc.  Suppose there are only a few daemons that support protocol version 35, and one of the users wants to make a -gsplit-dwarf build, so they fire up icemon and see the total number of clients, then start their build with a large number of threads, expecting the entire network to be available.  With @johnmiked15's patch, only very few compile jobs will be distributed, confusing the user and possibly creating some detective work for the scheduler admin if the user complains.

The scheduler admin could just make an announce to the users "please upgrade to icecc version X!", but the users can only guess how many nodes are running that version.  On the other hand with my patch, the scheduler admin can announce "we now require icecc version X, in order to support <particular feature>", and the users can see how many nodes have upgraded and are available in icemon and make use of an according number of build threads.

**Comment by johnmiked15** [comment]
I'm going to make the change I suggested last April. If you want to continue the discussion of a scheduler enforced minimum protocol version, let's make a new issue.
