### ISSUE TITLE
Bug when creating environnement for clang 3.8

### ISSUE THREAD

**Issue by ericch1** [icecc/icecream#152]
Hi,

I am trying to use icecream+ccache+clang but have some problems.

When lauching compilation, I first got many times the message:

"ICECC[148198] 14:37:17: no response from local daemon within timeout."

After a bunch of them, everything starts to work...

I decided to create myself the environement and got a strange behavior.  I launched:

icecc --build-native clang

and got a looooooooong output with strange recursive-like paths:
adding file /bin/true
adding file /lib64/libc.so.6
adding file /lib64/ld-linux-x86-64.so.2
adding file /usr/bin/clang=/usr/bin/X11/clang
adding file /usr/bin/X11/../lib64/libLLVMAArch64CodeGen.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/libLLVMAArch64AsmPrinter.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMAArch64Utils.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/libLLVMSupport.so.3.8
adding file /lib64/libdl.so.2
adding file /lib64/libtinfo.so.5
adding file /lib64/libpthread.so.0
adding file /lib64/libz.so.1
adding file /lib64/libm.so.6
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/../lib64/libstdc++.so.6
adding file /lib64/libgcc_s.so.1
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/libstdc++.so.6
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMMC.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMSupport.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libstdc++.so.6
adding file /usr/bin/X11/../lib64/../lib64/libLLVMAArch64Desc.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMAArch64AsmPrinter.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/libLLVMAArch64Utils.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/../lib64/libLLVMSupport.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/../lib64/../lib64/libstdc++.so.6
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/libLLVMMC.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMAArch64Info.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/libLLVMAArch64Info.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/libLLVMAArch64Utils.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/libLLVMAnalysis.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMCore.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/libLLVMAsmPrinter.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMAnalysis.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/libLLVMCore.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/libLLVMCodeGen.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/libLLVMAnalysis.so.3.8
adding file /usr/bin/X11/../lib64/../lib64/../lib64/../lib64/../lib64/libLLVMCore.so.3.8

and so on...

it lasts on 434 lines...

I also tried:

/usr/lib/icecc/icecc-create-env --clang /usr/bin/clang /usr/lib/icecc/compilerwrapper --addfile /usr/bin/objcopy

but it gives the same output...

OS: OpenSus Leap 42.1

rpms:
icecream-1.0.1-8.3.x86_64
llvm-clang-3.8.0-458.3.x86_64
icecream-clang-wrappers-1.0.1-8.3.x86_64
libclang-3.8.0-458.3.x86_64

What's wrong?

Thanks,

Eric

**Comment by llunak** [comment]
I expect c5663ea6419315f5bbfed1712b0090c32e48941a handled this.
