### ISSUE TITLE
calling "strip -s" from icecc-create-env can lead to unsuable executable

### ISSUE THREAD

**Issue by CapOM** [icecc/icecream#154]
Hi if a file is already stripped, what is the point of calling strip -s again ? 

ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=bff74785b1e283b98f49c3b97fffd9b6b05497f9, stripped

After extracting the generated tar ball when running icecc-create-env, a originally stripped executable is then not useable.
If I remove the call to strip then sudo chroot generated/ /usr/bin/gcc --version , works. But with strip then it fails (not output error but crash when using gdb but not backtrace)

Before providing more details, would it be possible to re-visit the existing call to strip -s since this code has not been touch since 2006 ? Thx

**Comment by CapOM** [comment]
Would you be interested in a patch that before calling strip from icecc-create-env willcheck that the original binary is already stripped and also instead of doing in-place strip it will write do it on a temp file and rename it only if it succeeds. Indeed on my setup it corrupts the binaries. So better to not call strip. Moreover original binaries were already stripped.

**Comment by llunak** [comment]
I agree, it seems rather pointless, and if it breaks things, it's better to remove it. f7562625a4a9ae7059b131ee96bab2fc95fcafe0 .
