### ISSUE TITLE
[question] how to disable scheduler back to node on poer 10245 for --no-remote workers

### ISSUE THREAD

**Issue by defunctzombie** [icecc/icecream#162]
I have setup a cluster of build-only workers and attached them to a scheduler. For each developer, I am trying to run iceccd with the `--no-remote` option but it seems to fail because the scheduler is trying to connect back to the developer's instance on port 10245. Is there a way to disable this behavior for nodes that are configured to not accept remote jobs? The firewall does not open this port from where the scheduler is located back to the developer machine (but 10245 is open on the icecc worker cluster to the developer machines)

What I am practically trying to do is just allow the nodes to connect to the scheduler on its port without the scheduler attempting to connect to the developer's iceccd instance on port 10245 since there is no point for that as the `--no-remote` flag is being used.

**Comment by llunak** [comment]
Looking at the code, the scheduler never connects to daemons on port 10245. The only such connections come from the icecc client, when it asks the daemons to do a remote build, and that should happen only if daemons actually announce they accept them.

Given how old this report is (sorry), this has possibly changed, but one way or another I expect this is totally outdated, so I'll close this. If you still have a problem, please report it again with more details.
