### ISSUE TITLE
icecc client forces "building_local" if you use a version-specific clang or gcc binary

### ISSUE THREAD

**Issue by dholbert** [icecc/icecream#164]
The llvm project provides [version-specific clang snapshots](http://apt.llvm.org/) whose binaries are named e.g. `clang++-3.8` (which is clang++ version 3.8).  (This is convenient for installing & testing multiple versions of clang side-by-side.)

BUT, when I try to compile with `icecc` and these distributions of clang, I only get `<building_local>` in my `ICECC_LOGFILE` -- no builds end up being distributed to other nodes!! So I get no benefit from running `icecc`.

I diagnosed this (I think) by building `icecc` locally & adding some debugging code.  It looks to me like things are falling over because of this code where the `icecc` client is trying to figure out the language:
https://github.com/icecc/icecream/blob/master/client/arg.cpp#L76

```
if ((suffix == "++") || (suffix == "CC")) {
    job.setLanguage(CompileJob::Lang_CXX);
} else if (suffix == "cc") {
    job.setLanguage(CompileJob::Lang_C);
} else if (compiler_name == "clang") {
    job.setLanguage(CompileJob::Lang_C);
} else {
    job.setLanguage(CompileJob::Lang_Custom);
    log_info() << "custom command, running locally." << endl;
    return true;
}
```

My compiler binary (from LLVM's official site), `clang++-3.8`, _does not_ have a suffix of "++" -- therefore, this code rejects it as a "custom command" / custom language, and treats it as a must-be-local compile job (which is what the `return true` indicates).

Hence: I'm filing this issue on broadening this source code to gracefully handle C++ compilers with names like `clang++-3.8`.

**Comment by mostynb** [comment]
This seems to work for me:
https://github.com/icecc/icecream/pull/165

**Comment by llunak** [comment]
#165 has been merged, so closing.
