### ISSUE TITLE
flush_writebuf() failed Broken pipe

### ISSUE THREAD

**Issue by dabrahams** [icecc/icecream#167]
I am running the latest master on MacOS; almost everything seems to be working for me now, launching on the master (192.168.0.1):

```
$ sudo icecc-scheduler -n frutti -u daemon -vvv
$ sudo iceccd -n frutti -m 3 -vvv -s localhost -N skree -u daemon
```

and on the slave (192.168.0.2):

```
$ sudo iceccd -n frutti -m 3 -vvv -s 192.168.0.1 -N wingy -u daemon
```

But although the slave shakes hands and even gets the environment from the master, it never seems to actually build anything.  My build command output is full of these:

```
ICECC[39986] 16:56:08: flush_writebuf() failed Broken pipe
ICECC[39986] 16:56:08: write of source chunk to host 192.168.0.2
ICECC[39986] 16:56:08: failed  Broken pipe
ICECC[39986] 16:56:08: got exception Error 15 - write to host failed (192.168.0.2) 
```

and my slave log looks like this:

```
[2909] 16:55:12: ICECREAM daemon 1.1rc2 starting up (nice level 5) 
[2909] 16:55:12: 8 CPU(s) online on this server
[2909] 16:55:12: allowing up to 10 active jobs
[2909] 16:55:12: not detaching
[2909] 16:55:12: entered process group
[2909] 16:55:12: ignoring localhost lo0
[2909] 16:55:12: broadcast en0 17.114.131.255
[2909] 16:55:12: broadcast bridge0 192.168.0.255
[2909] 16:55:12: Netnames:
[2909] 16:55:12: frutti
[2909] 16:55:12: scheduler is on 192.168.0.1:8765 (net )
[2909] 16:55:12: scheduler not yet found.
[2909] 16:55:15: scheduler not yet found.
[2909] 16:55:18: Connected to scheduler (I am known as 192.168.0.2)
[2909] 16:55:44: accepted 7 192.168.0.1
[2909] 16:55:44: handle_transfer_env
[2909] 16:55:44: pid 2910
[2909] 16:55:44: got pid 2910
[2909] 16:55:44: handle_transfer_env_done
[2909] 16:55:44: installed_size: 59830408
[2909] 16:55:44: installed Darwin16_x86_64/fc70ec139a0b6f7f67e5f0a262357823 size: 59830408 all: 59830408
[2909] 16:55:44: reannounce_environments 
[2909] 16:55:44: Verify environment done, success, environment fc70ec139a0b6f7f67e5f0a262357823 (Darwin16_x86_64)
[2909] 16:55:44: requests--1
[2909] 16:55:44: handle connection returned 2912
[2912] 23:55:44: <parent, waiting>
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: </parent, waiting: 20ms>
[2909] 16:55:45: accepted 7 192.168.0.1
[2909] 16:55:45: requests--7
[2909] 16:55:45: handle connection returned 2914
[2914] 23:55:45: <parent, waiting>
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: </parent, waiting: 14ms>
[2909] 16:55:45: accepted 7 192.168.0.1
[2909] 16:55:45: requests--14
[2909] 16:55:45: handle connection returned 2916
[2916] 23:55:45: <parent, waiting>
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: </parent, waiting: 14ms>
[2909] 16:55:46: accepted 7 192.168.0.1
[2909] 16:55:46: requests--16
...etc...
```

Any help would be most appreciated!

**Comment by sss123next** [comment]
same problem
gentoo system x86_64 gcc620

**Comment by adam-trhon** [comment]
We face similar problem in our company. We figured out that it is caused by wrong toolchain configuration (we have the error only when cross-compiling). Preprocessor is not found (or fails), so it produces (and sends) no output, so the remote machine gets unexpected EOF.

**Comment by dabrahams** [comment]
So it seems like icecream ought to be putting something more useful in the logs for these cases....

**Comment by adam-trhon** [comment]
Exactly. It would be great to have some extended log (other than -vvv) that would output all commands run, their arguments, output and any error their print. While -vvv is surely very useful for debugging icecc, there seems to be no way to debug the compiler setup.

**Comment by bluGill** [comment]
Patches welcome...  I've considered adding some of it myself, but
it seems like I'm the only one who looks at patches so who would
check my work?


--

  Henry Miller

  hank@millerfarm.com







On Sun, Feb 5, 2017, at 06:38 AM, adam-trhon wrote:

> Exactly. It would be great to have some extended log (other than -vvv)
> that would output all commands run, their arguments, output and any
> error their print. While -vvv is surely very useful for debugging
> icecc, there seems to be no way to debug the compiler setup.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 


Links:

  1. https://github.com/icecc/icecream/issues/167#issuecomment-277517107

**Comment by adam-trhon** [comment]
So I started adding debug prints to the code. When invoking make it prints:

    ICECC[16091] 23:18:52: <send compile_file>
    ICECC[16091] 23:18:52: </send compile_file: 0ms>
    ICECC[16091] 23:18:52: <write_server_cpp from cpp>
    ICECC[16091] 23:18:52: [=DBG=] write_server_cpp offset : 100000
    ICECC[16091] 23:18:52: [=DBG=] sending FileChunkMsg to MsgChannel, len 100000
    # 1 "f1001.cpp"
    # 1 "<built-in>"
    # 1 "<command-line>"
    # 1 "/usr/local/tbs-sdk-tseries12-armv7a-i686/
    ICECC[16091] 23:18:52: [=DBG=] MsgChannel::writecompressed _in_len 100000 _out_len 88419
    ICECC[16091] 23:18:52: [=DBG=] sent FileChunkMsg to MsgChannel, compressed 20471
    ICECC[16091] 23:18:52: [=DBG=] write_server_cpp offset : 100000
    ICECC[16091] 23:18:52: [=DBG=] sending FileChunkMsg to MsgChannel, len 100000
    -gnueabi/usr/include/boost/preprocessor/tuple/eat.hpp" 1 3 4
    # 22 "/usr/local/tbs-sdk-tseries12-armv
    ICECC[16091] 23:18:52: [=DBG=] MsgChannel::writecompressed _in_len 100000 _out_len 20471
    ICECC[16091] 23:18:52: [=DBG=] sent FileChunkMsg to MsgChannel, compressed 12427
    ICECC[16091] 23:18:52: [=DBG=] write_server_cpp offset : 100000
    ICECC[16091] 23:18:52: [=DBG=] sending FileChunkMsg to MsgChannel, len 100000
    ile > { static const bool value = true; };

    template <class R, class T , class T0 , class T1>
    struct
    ICECC[16091] 23:18:52: [=DBG=] MsgChannel::writecompressed _in_len 100000 _out_len 12427
    ICECC[16091] 23:18:52: [=DBG=] sent FileChunkMsg to MsgChannel, compressed 9988
    ICECC[16091] 23:18:52: flush_writebuf() failed Broken pipe
    ICECC[16091] 23:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    ICECC[16091] 23:18:52: [=DBG=] read_a_bit read 128 bytes
    ICECC[16091] 23:18:52: [=DBG=] read_a_bit read 167 bytes
    ICECC[16091] 23:18:52: [=DBG=] MsgChannel::wait_for_msg done
    ICECC[16091] 23:18:52: write of source chunk to host 172.17.0.3
    ICECC[16091] 23:18:52: failed  Broken pipe
    ICECC[16091] 23:18:52: </write_server_cpp from cpp: 77ms>
    ICECC[16091] 23:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    ICECC[16091] 23:18:52: [=DBG=] read_a_bit setting eof
    ICECC[16091] 23:18:52: timeout <= 0
    ICECC[16091] 23:18:52: saw eof without complete msg! 1
    ICECC[16091] 23:18:52: got exception Error 15 - write to host failed (172.17.0.3) 


Lines containing `[=DBG=]` are mine. I also print first 100 bytes of every chunk sent. So far so good (maybe with the exception of 0ms in send_compile_file, is that OK?). Let's see what says the daemon on remote machine:

    [41] 22:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    [41] 22:18:52: timeout <= 0
    [41] 22:18:52: !wait_for_msg()
    [41] 22:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    [41] 22:18:52: [=DBG=] read_a_bit read 20487 bytes
    [41] 22:18:52: timeout <= 0
    [41] 22:18:52: [=DBG=] filling FileChunkMsg from MsgChannel
    [41] 22:18:52: [=DBG=] MsgChannel::readcompressed uncompressed_len 100000 compressed_len 20471
    [41] 22:18:52: [=DBG=] filled FileChunkMsg from MsgChannel, len 100000, compressed 20471
    # 1 "f1001.cpp"
    # 1 "<built-in>"
    # 1 "<command-line>"
    # 1 "/usr/local/tbs-sdk-tseries12-armv7a-i686/
    [41] 22:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    [41] 22:18:52: timeout <= 0
    [41] 22:18:52: !wait_for_msg()
    [41] 22:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    [41] 22:18:52: timeout <= 0
    [41] 22:18:52: !wait_for_msg()
    [41] 22:18:52: [=DBG=] MsgChannel::wait_for_msg begin
    [41] 22:18:52: timeout <= 0
    [41] 22:18:52: !wait_for_msg()
    [41] 22:18:52: </parent, waiting: 22ms>
    [36] 22:18:52: [DBG] Daemon::answer_client_requests listen_fd == -1
    [36] 22:18:52: [DBG] Daemon::answer_client_requests handle_compile_done

And it appears that the daemon only receives the first file chunk.

So I started Wireshark and captured. There is some comunication, the a [FIN,ACK] coming from remote daemon and then a bunch of [RST] coming from remote daemon again. This seems as if remote daemon closed the socket. But why? I started to dig again, added some more debug prints, ended up in `work_it` and lost all my courage (for now).

**Comment by adam-trhon** [comment]
> Patches welcome...  I've considered adding some of it myself, but
it seems like I'm the only one who looks at patches so who would
check my work?

If you make a pull request I could check if it works for me...?

**Comment by HenryMiller1** [comment]
Good investigation. I’m not sure what to make of it, but we know more anyway.

**Comment by stoupa-cz** [comment]
Hi guys,

we had a very same problem with my colleague (adam-trhon) and it looks like the remote compiler fails for some reason (either it cannot be executed or there are wrong arguments). I'm not sure if the wrong source code looks the same or if is the remote error printed with `-vvv`.

One problem we found was that our C preprocessor didn't expand the `stdc-predef.h` header. Behaviour of that file was changed in gcc 4.8. @dabrahams, @sss123next, could you please check how your preprocessed file looks like (i.e. is the stdc-predef.h expanded)? And if it is not expanded, could you please check if your toolchain created by icecc contains that header?

BTW1 - we will continue on that problem, so we will hopefully find the solution.
BTW2 - the other two problems we had in our toolchain were missing `/bin/true` and wrong `rpath`s in toolchain binaries and libraries.

**Comment by stoupa-cz** [comment]
@dabrahams, @sss123next, so the `stdc-predef.h` was not an issue. Icecream internally calls gcc with `-fpreprocessed` so it won't hurt. The problem was finally in the toolchain. Missing /bin/true was the first problem and the rpaths was the second. We fixed the second problem with something like this in the icecc-create-env script:
```
for f in ${tempdir}/usr/bin/{as,gcc,cc1,g++,cc1plus}; do
        # FIXME hardcoded path of loader
        patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 $f || exit 3
        patchelf --set-rpath /lib $f || exit 3
        echo $f;
done
```
The icecc now works for us (although the build was slower in one case so we need to investigate further).

**Comment by adam-trhon** [comment]
@dabrahams, @sss123next can you still repeat the case? If so, please try to enable icecc logs:

    export ICECC_DEBUG=info

and disable caret workaround:

    export ICECC_CARET_WORKAROUND=0

in your client's terminal (where you run make).  Does it print anything interesting now?

**Comment by sss123next** [comment]
i will check, currently i have switched back to distcc because of this problem.

**Comment by dabrahams** [comment]
@adam-trhon it may be some time before I can do this, because like @sss123next currently i have switched back to distcc because of this problem.

**Comment by HenryMiller1** [comment]
I tried to repeat this case by inserting the line:  “this is illegal code”.  I don’t think there are any surprises here, but I figured I’d show this anyway just in case it tells you something.  Any other debugging you want me to do?


Before:
ICECC[176] 10:09:50: <send compile_file>
ICECC[176] 10:09:50: </send compile_file: 0ms>
ICECC[176] 10:09:50: <write_server_cpp from cpp>
ICECC[176] 10:09:50: </write_server_cpp from cpp: 546ms>
ICECC[176] 10:09:50: <wait for cpp>
ICECC[176] 10:09:50: </wait for cpp: 0ms>
ICECC[176] 10:09:50: <wait for cs>
ICECC[176] 10:09:53: </wait for cs: 2414ms>
ICECC[176] 10:09:53: command needs stdout/stderr workaround, recompiling locally
ICECC[176] 10:09:53: local build forced by remote exception: Error 102 - command needs stdout/stderr workaround, recompiling locally
testcase.cpp:22:1: error: expected unqualified-id before 'this'
this is illegal code
^
ERROR: ninja: build stopped: subcommand failed.


After:

ICECC[169] 10:14:42: <send compile_file>
ICECC[169] 10:14:42: </send compile_file: 0ms>
ICECC[169] 10:14:42: <write_server_cpp from cpp>
ICECC[169] 10:14:43: </write_server_cpp from cpp: 548ms>
ICECC[169] 10:14:43: <wait for cpp>
ICECC[169] 10:14:43: </wait for cpp: 0ms>
ICECC[169] 10:14:43: <wait for cs>
ICECC[169] 10:14:45: </wait for cs: 2018ms>
testcase.cpp:22:1: error: expected unqualified-id before 'this'
ICECC[169] 10:14:45: Compiled on 10.140.160.74
ERROR: ninja: build stopped: subcommand failed.

**Comment by adam-trhon** [comment]
@HenryMiller1 Thank you, but I don't need to verify the behavior. I think that setting these two variables might print the real reason behind the `Broken pipe` error.

**Comment by stoupa-cz** [comment]
@HenryMiller1 Well, one "surprise" is there. With your previous settings (i.e. without `export ICECC_CARET_WORKAROUND=0`) your remote build failed and it was recompiled locally. This is huge performance penalty in case that you have a warnings in your build output. We were trying to compile opencv for a benchmark and the performance was terrible (much worse than a local build). We fixed it with by disabling the caret workaround.

**Comment by HenryMiller1** [comment]
It is understood that the build will happen locally when the carret workaround is on.  The question is why are we getting a broken pipe error.

**Comment by stoupa-cz** [comment]
@HenryMiller1 we are currently off-topic. I know that you get a broken pipe error. I was also hoping that  `export ICECC_DEBUG=info` will help us to identify the problem. But it didn't. I was just pointing out that there were another problem with remote build failing. Back to your question:

> It is understood that the build will happen locally when the carret workaround is on.

AFAIK only in case when warning is emitted during the compilation (this warning contains caret in newer gccs and you need the original source code file to print the caret correctly in the context).

**Comment by adam-trhon** [comment]
@HenryMiller1 one of the error scenarios on our side was:

1. ICECC_VERSION pointed to a badly assembled archive
1. remote node failed to start gcc, didn't receive the source at all, which caused the `Broken pipe` error
1. local node got error message from remote node
1. local node discarded error message and started to recompile locally
1. local recompilation failed as well because we did more mistakes
1. only thing we saw was the broken pipe error, so we started playing with wireshark

This is the scenario I wish we'd had:

1. ICECC_VERSION pointed to a badly assembled archive
1. remote node failed to start gcc, didn't receive the source at all, which caused the `Broken pipe` error
1. local node got error message from remote node
1. local node printed error message
1. we started fixing the real problems

Based on this I advise OP to disable the workaround, so that any error coming from remote node is not discarded, but printed.

When we see what the real problem is, we can replicate it on our computers and figure out why it prints `Broken pipe` instead of anything useful.

**Comment by johnmiked15** [comment]
The reason the icecream client is printing a `Broken pipe` is simple. The way icecream works is roughly the following:

Client finds a daemon. The daemon then spawns a process to handle the job. This process sets up some pipes with another child process that fork/execs the compiler itself. The compiler's stdin is piped to a buffer controlled by this process. The controlling process writes to the compiler's stdin pipe as it receives the content of the preprocessed file from the client over the socket.

The error with an incorrect toolchain (or any similar error) occurs before the compiler even attempts to read stdin. It dies, and the controlling process notices this. The controlling process is currently coded to just die whenever the child compiler process terminates for any non-successful reason other than an out of memory error. This kills the socket connection between daemon and client, while the client is still attempting to write the preprocessed file, resulting in a broken pipe.

This can be fixed, or at least alleviated, by making the client smarter about the errors its seeing, and making the daemon smarter about sending stderr output back to the client in all cases. I haven't had a chance to set up a reproducible scenario but I think I gave some ideas on how to fix this in another issue somewhere. I want the final solution to be more elegant than my hack job in that suggestion, though.

**Comment by NextDesign1** [comment]
We are seeing this error very frequently. I have not tested the original version that @creste merged in above, but I'm wondering if there may be a regression? I haven't been able to see anything telling from the logs, or even from packet captures over the network. I'm certain that the send build chain is correct however, as the machines that it eventually starts complaining about has compiled hundreds of files in the same build. We have 284 workers (threads) on our farm, and it doesn't seem to matter whether I set -j100 or -j300 when building. Do jobs have a certain time-to-live? I.e. will they time out? My only other thought was that we are saturating the network, however if I build with -j32, it still has a chance of erroring out.

I'll try to collect some sample logs in the next few days.

**Comment by zub2** [comment]
@NextDesign1 perhaps you're experiencing https://github.com/icecc/icecream/issues/527?
