### ISSUE TITLE
feature request: add an option to fail with an error rather than build locally

### ISSUE THREAD

**Issue by mostynb** [icecc/icecream#169]
I run icecc on a build farm, which works well when things are working as expected.  However sometimes changes are introduced to our build system which prevent icecc from building remotely, and unattended builds on the build farm become really slow.  Realising and fixing these types of problems can take quite some time.  I would love it if icecc had a setting that would cause builds to fail rather than fall back to local compilation (off by default).

For example, how about a new environment variable ICECC_LOCAL_FALLBACK with possible values 1 (default, allow local fallback) and 0 (fail rather than build locally) ?

I can implement this feature, if it would be accepted.

**Comment by HenryMiller1** [comment]
I'm not against it. I think I prefer it to be a local daemon option over an environment variable.  If the code is clean I'll accept it.

**Comment by llunak** [comment]
Given the lack of the implementation of this feature, I take it this is no longer valid.
