### ISSUE TITLE
Mouse Cursor disappears while icecc is running

### ISSUE THREAD

**Issue by AlgorithMan-de** [icecc/icecream#181]
I know this sounds stupid, because it seems like it can't possibly be related, but I have observed this for several months and I am convinced that it is related. My mouse cursor disappears when I am compiling with icecc (whether my machine is used by someone elses compilation or I am using someone elses machine). It doesn't always happen and not immediately. Sometimes it comes back, but in about 50% of the cases, I can't even get it back by restarting drivers, switching to text-mode and back, changing the mouse cursor manually etc. - I have to kill the X-Server which is very annoying.
I think it might be related to the libs that are opened in the compilation process - I compile the Qt framework, which of course links against a lot of gui/input/system libs - but the problem doesn't occur when I compile with g++. It also happens when a different mouse is attached.
Running on Linux Mint 17.3 64-Bit, KDE, Kernel 3.19.0-32-generic, GPU: Mesa DRI Intel(R) Haswell Desktop, XCB API.

**Comment by tronical** [comment]
I suspect that this isn't strictly icecream related but perhaps more to the load on your system and how your kernel deals with that. I wonder if the same problem appears (or visually "disappears" in your case ;-) if you could produce similar load with something else.

**Comment by AlgorithMan-de** [comment]
I just ran `stress -c 16 -i 60` and had no issues. I should also mention that the mouse is still usable, only the cursor becomes invisible.

**Comment by AlgorithMan-de** [comment]
After I added "nomodeset" to the kernel parameters (as @tronical suggested) I haven't seen this happen again.
