### ISSUE TITLE
Icemon unable to connect to explicitely specified scheduler

### ISSUE THREAD

**Issue by LuxoftAKutsan** [icecc/icecream#183]
icemon Error : 
```
➜  scheduler git:(master) ✗ USE_SCHEDULER=127.0.0.1 icemon
scheduler is on 127.0.0.1:8765 (net )
no response from local daemon within timeout.
QSocketNotifier: Invalid socket 12 and type 'Write', disabling...
```

Scheduler started in docker container with exposed 8765 port. 
Here is [Scheduler Dockerfile](https://github.com/alexkutsan/RnD_fun/blob/master/icecc-fun/scheduler/Dockerfile)
with command :
```
docker run -d  -p 8765:8765 icecc-scheduler
```

Daemon started in docker container with exposed 10245 port. 
Here is [Daemon Dockerfile](https://github.com/alexkutsan/RnD_fun/blob/master/icecc-fun/Dockerfile)
with command :
```
docker run -d  -p 10245:10245 icecc-daemon 
```
Icemon started on local workstation with command : 
```
USE_SCHEDULER=127.0.0.1 icemon
```

First start of icemon is successful. But after Ctrl-C and starting it print it returns error : 
```
scheduler is on 127.0.0.1:8765 (net )
no response from local daemon within timeout.
QSocketNotifier: Invalid socket 12 and type 'Write', disabling...
```

What could be the issue? Is it bug?

**Comment by HenryMiller1** [comment]
It could be, but you will need someone with networking knowledge to dig in and figure out what. I don't think anyone has experience with using docker and ice cream so you are on your own.

**Comment by llunak** [comment]
Is this still a valid issue? If yes, please run icemon with ICECC_DEBUG=debug and provide the debug output.

**Comment by llunak** [comment]
No response, closing.
