### ISSUE TITLE
iceccd discards error output from remote build

### ISSUE THREAD

**Issue by adam-trhon** [icecc/icecream#185]
When playing with `work_it` (in daemon/workit.cpp) to solve the `flush_writebuf() failed Broken pipe` problem (issue https://github.com/icecc/icecream/issues/167) I found out that the error output is discarded.

My remote daemon prints:

    [85] 10:15:32: timeout <= 0
    [85] 10:15:32: !wait_for_msg()
    [85] 10:15:32: timeout <= 0
    [85] 10:15:32: !wait_for_msg()

which says nothing. After commenting out the line `dup2(sock_err[1], STDERR_FILENO); ` from `daemon/workit.cpp` (somewhere around line 300) it prints:

    [85] 10:15:32: timeout <= 0
    [85] 10:15:32: !wait_for_msg()
    g++: error: unrecognized command line option '-marm'; did you mean '-mabm'?
    g++: error: unrecognized command line option '-mthumb-interwork'
    g++: error: unrecognized command line option '-mfloat-abi=softfp'
    g++: error: unrecognized command line option '-mfpu=neon'
    [85] 10:15:32: [=DBG=] MsgChannel::wait_for_msg begin
    [85] 10:15:32: timeout <= 0
    [85] 10:15:32: !wait_for_msg()

which points to the real problem. I have `export ICECC_DEBUG=debug` in make's terminal, both iceccd and iceccd-shceduler started with -vvv, and I see these lines for the first time.

**Comment by HenryMiller1** [comment]
interesting data.

Is the problem only that icecc is dropping build output, or are there other problems?  That is appears that you are trying to compile for ARM, is it your mistake that remote jobs are using a non-arm compiler environment, or is it some weird bug in icecc where sometimes the wrong environment is used?

Either way I agree we shouldn't be dropping this output, though I'm not clear if your solution is correct or not.

**Comment by adam-trhon** [comment]
There are two problems involved:

1. We are setting up an ARM toolchain and it does not work. This is our problem to solve and it's not the subject of this issue.
1. In our case icecc does not help much. Instead of telling us about a compiler problem it complains about a broken pipe and communication issues. I actually spent about two days digging around in the code before I figured out the root cause. This I would like to improve.

So, I propose (and plan, at least for us) to add either a command line argument or an envirnoment variable that would disable the line I commented out. When you have problems you enable compiler output and see what is wrong. When you run production node you leave it disabled to avoid side effects (as filling the logs with lengthy compiler warnings). What do you think about this way?

There are two questions to answer:

1. Command line argument or environment variable? How to call it?
1. Enable the compiler output by default (friendly to newcomers) or disable by default (backwards compatible)?

**Comment by HenryMiller1** [comment]
I don't see any reason to not print this out by default.  Maybe a command line option to disable it, or maybe print it with -v (minimum verbosity).  I think it is reasonable to expect users running icecream to have log rotation (though we should document this and make sure it works).  

I'm assuming that this output will go to log files on the machine running the build.  Ideally I think we need to tell the user who is compiling "Compile on node.example.com failed, but succeeded locally; see log messages on that machine" so they know to go look at that machine.  Or something like that.

**Comment by HenryMiller1** [comment]
I don't think just commenting out that line is correct though. I think we want to save stderr to a buffer and dump it all at once after the build. I'm thinking about cases where the machine has accepted many build jobs at the same time: the logs may get many messages mixed up.  Also when we print the log we should note what machine we are doing the compile for.

**Comment by johnmiked15** [comment]
@HenryMiller1, I don't think you've completely understood what the problem here is.

The iceccd process running on the remote machine (the same process that forks the compiler command to run), is sending a TCP reset packet to the daemon running on the box that is running the build when the compile command errors out.

The line that the @adam-trhon wants to comment out is doing nothing but binding stderr for the compile command to the socket connection back to the originating host. This is intended to let the *local* icecream daemon see the error messages generated by compile command.

We need to investigate why this particular situation causes the TCP reset instead of sending the stderr output over the socket.

**Comment by johnmiked15** [comment]
@adam-trhon: if you could do me a favor and add the following line of code to the bottom of serve.cpp:

```cpp
delete msg;
delete job;

log_info() << "workit returned: " << e.exitcode() << endl; // add this line

_exit(e.exitcode());
```
And then run your scenario again? Post back here with the value in the log on the remote daemon.

The next thing you can try after you've done that is try applying the following diff and see if it "fixes" the issue:
```diff
diff --git a/daemon/serve.cpp b/daemon/serve.cpp
index baddb5c..76e70e1 100644
--- a/daemon/serve.cpp
+++ b/daemon/serve.cpp
@@ -268,12 +268,8 @@ int handle_connection(const string &basedir, CompileJob *job,
             ret = work_it(*job, job_stat, client, rmsg, build_path, "", file_name, mem_limit, client->fd, -1);
         }

-        if (ret) {
-            if (ret == EXIT_OUT_OF_MEMORY) {   // we catch that as special case
-                rmsg.was_out_of_memory = true;
-            } else {
-                throw myexception(ret);
-            }
+        if (ret == EXIT_OUT_OF_MEMORY) {
+            rmsg.was_out_of_memory = true;
         }

         if (!client->send_msg(rmsg)) {
@@ -281,6 +277,10 @@ int handle_connection(const string &basedir, CompileJob *job,
             throw myexception(EXIT_DISTCC_FAILED);
         }

+        if (ret && ret != EXIT_OUT_OF_MEMORY) {
+            throw myexception(ret);
+        }
+
         struct stat st;

         if (!stat(obj_file.c_str(), &st)) {
```

**Comment by HenryMiller1** [comment]
@johnmiked15 I bow to your superior understanding of this issue. 

I suspect we are seeing this same issue here, so I'm curious what the result it.

**Comment by adam-trhon** [comment]
@johnmiked15:

I lost the original toolchain archive, which was a bit "special" - it created the preprocessed file (succeeded locally), but failed to perform the remote build. So I made a "special" cpp file that can be preprocessed, but cannot be compiled. Now it behaves the same way (remote gcc is started, prints some errors and fails), just the error messages are different.

I applied the first patch, kept the `dup2(... ` line commented out and got:

    [672] 16:07:02: timeout <= 0
    [672] 16:07:02: !wait_for_msg()
    [672] 16:07:02: timeout <= 0
    nonsense.cpp:2:1: error: 'nonsense' does not name a type
    [672] 16:07:02: timeout <= 0
    [672] 16:07:02: !wait_for_msg()
    [672] 16:07:02: </parent, waiting: 6ms>
    [672] 16:07:02: [johnmiked15] workit returned: 1

from the remote node. Then I applied the second patch, did the same and got the exact same output. I observed no change on local node output or make output.

If you want to reproduce it yourself, build any file that can be preprocessed but cannot be compiled:

    $ cat nonsense.cpp 

    nonsense nonsense nonsense

    $

**Comment by johnmiked15** [comment]
Don't comment the dup2 line. Then try again. Thanks for your help reproducing this.

**Comment by adam-trhon** [comment]
I uncommented the dup2 line and I got the error message when invoking make. So I did a cross check: I disabled your patch, tried again and got the message again. So it behaves as it should, but this is not what I observed at the beginning.

So I recreated the situation more precisely. I had a wrong toolchain on the remote node, it could not parse the arguments passed by CXXFLAGS. So I forced my native toolchain for cross compilation using ICECC_VERSION:

    export ICECC_VERSION=$(pwd)/native.tar.gz,x86_64:$(pwd)/native.tar.gz=arm-oe-linux-gnueabi

This simulates my original situation: local toolchain is set up correctly, so it understands the `-marm`, `-mthumb-interwork`, etc arguments and produces preprocessed file. The preprocessed file is sent to remote node, where the native toolchain is (wrongly) installed, does not understand the arguments and fails with the messages in my original post.

I enabled both your patches and got:

    [775] 20:55:42: <parent, waiting>
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: timeout <= 0
    [775] 20:55:42: !wait_for_msg()
    [775] 20:55:42: </parent, waiting: 29ms>
    [775] 20:55:42: [johnmiked15] workit returned: 1

from remote node, 

    ICECC[11330] 21:55:42: write of source chunk to host 172.17.0.3
    ICECC[11330] 21:55:42: failed  Broken pipe
    ICECC[11330] 21:55:42: </write_server_cpp from cpp: 74ms>
    ICECC[11330] 21:55:42: timeout <= 0
    ICECC[11330] 21:55:42: saw eof without complete msg! 1
    ICECC[11330] 21:55:42: got exception Error 15 - write to host failed (172.17.0.3) 
    make: *** [<builtin>: f1001.o] Error 15

from make (remote node runs on docker, so the different time). What I would like is to see the 

    g++: error: unrecognized command line option '-marm'; did you mean '-mabm'?
    g++: error: unrecognized command line option '-mthumb-interwork'
    g++: error: unrecognized command line option '-mfloat-abi=softfp'
    g++: error: unrecognized command line option '-mfpu=neon'

errors somewhere (I had to run another iteration, with dup2 line commented out, to get them). Note that even if you do the toolchain verification test:

    chroot . /usr/bin/gcc main.c 

you don't get these errors, as you need to provide the command line options.

**Comment by adam-trhon** [comment]
I discovered why the error output is discarded. The error message from the compiler triggers the stdout/stderr workaround and the source is compiled locally. Icecc client tells that in logs, I just didn't connect these two.

**Comment by johnmiked15** [comment]
Try one more thing for me. Don't use any of the other suggested changes, but just try adding the following snippet to workit.cpp. This will basically send stderr from the compiler command as an error message back to the client whenever there was a failure. Brief local testing confirms this works, but I want to make sure it helps your use case.

```diff
diff --git a/daemon/workit.cpp b/daemon/workit.cpp
index 87a0ad6..f68c463 100644
--- a/daemon/workit.cpp
+++ b/daemon/workit.cpp
@@ -593,6 +593,9 @@ int work_it(CompileJob &j, unsigned int job_stat[], MsgChannel *client, CompileR
                     job_stat[JobStatistics::sys_pfaults] = ru.ru_majflt + ru.ru_nswap + ru.ru_minflt;
                 }
 
+                if (return_value && !rmsg.err.empty()) {
+                    error_client(client, rmsg.err);
+                }
                 return return_value;
             }
         }
```

**Comment by llunak** [comment]
Current version now logs stdout, stderr and exitcode of the remote compiler run, so I think this is handled now.
