### ISSUE TITLE
icecream melts down from long warnings

### ISSUE THREAD

**Issue by adam-trhon** [icecc/icecream#190]
Compiling OpenCV on 4 local cores and 8 remote cores takes us 14 minutes. That's bad, because compiling the same on the local machine only takes 12 minutes. There are big gaps between jobs, it seems that the scheduler does not do its job well.

When we disable warnings (which we don't want to do in production), the distributed build takes 8 minutes. I did some experiments and if I understand it right, icecc cannot distribute other builds when warnings are transferred. And when the transfer takes two or three seconds it hurts the performance very badly.

The only solution I see here is to limit the warning amount. If we have, say, more than 10kB of warnings, we won't read them anyway. How to patch icecream this way? Could we add some env variable to adjust the amount of transferred warnings?

**Comment by HenryMiller1** [comment]
I agree that there is a problem, patches welcome…

That said, I’m not sure why you don’t want to disable warnings.  To my thinking, either you maintain OpenCV and thus want to be running -werror and fixing all warnings, or this is a “third party” library that you don’t maintain and thus are not interested in any warnings anyway.

**Comment by adam-trhon** [comment]
I was completely wrong with the cause estimation. It's not the length, it's the content. This is my sample warning:

    g++ -o f9.o f9.cpp -Wall -c
    In file included from f9.cpp:1:0:
    impl.cpp:6:28: warning: ‘i6’ defined but not used [-Wunused-variable]
     static int APPEND_LINE_NUM(i);
                                ^
    impl.cpp:2:37: note: in definition of macro ‘APPEND_LINE_NUM_3’
     #define APPEND_LINE_NUM_3(ID, LINE) ID##LINE
                                         ^~
    impl.cpp:4:29: note: in expansion of macro ‘APPEND_LINE_NUM_2’
     #define APPEND_LINE_NUM(ID) APPEND_LINE_NUM_2(ID, __LINE__)
                                 ^~~~~~~~~~~~~~~~~
    impl.cpp:6:12: note: in expansion of macro ‘APPEND_LINE_NUM’
     static int APPEND_LINE_NUM(i);
                ^~~~~~~~~~~~~~~

It contains a lot of carets, causing icecc to rebuild the file locally. This is the same warning when I disable the caret workaround using `ICECC_CARET_WORKAROUND`:

    g++ -o f9.o f9.cpp -Wall -c
    In file included from f9.cpp:1:0:
    impl.cpp:6:12: warning: 'i6' defined but not used [-Wunused-variable]

Although not ideal, it's enough to decide if the warning is worth further ivestigation (either fix it directly or manually trigger the local build) or not. IMHO the worst thing about this is that when caret workaround is active and triggered, M_END message fails to transfer, generating timeout and Broken Pipe logs. To a newcommer it looks like an internal icecc error.

Would you accept a patch that disables caret workaround by default? Something as 

    diff --git a/client/util.cpp b/client/util.cpp
    index d384dbd..ea496e3 100644
    --- a/client/util.cpp
    +++ b/client/util.cpp
    @@ -322,12 +322,15 @@ bool ignore_unverified()
     // be worth it.
     bool output_needs_workaround(const CompileJob &job)
     {
    +    const char *caret_workaround(0);
    +    if (!(caret_workaround = getenv("ICECC_CARET_WORKAROUND")))
    +        return false;
    +    if (*carret_workaround != '1')
    +        return false;
         if (compiler_is_clang(job))
             return false;
         if (explicit_no_show_caret)
         return false;
    -    if (const char* caret_workaround = getenv("ICECC_CARET_WORKAROUND"))
    -        return *caret_workaround == '1';
     #ifdef HAVE_GCC_SHOW_CARET
         return true;
     #endif

We would end up with some misteriously missing carets, but searching for "icecc missing caret" will eventually point to a right direction, unlike "icecc Broken pipe". During monday I will check if it helps with OpenCV.

To your question. Substitute OpenCV for Boost or gSoap. These are third party libraries that generate warnings in our code. We can't disable warnings globally, as it would hide ours.

**Comment by adam-trhon** [comment]
So we checked the OpenCV build and confirmed that disabling caret workaround really helped. Now there is no difference between logs enabled and logs disabled.

I also repeated some of the error scenarios we faced before and got much more relevant error messages.

**Comment by HenryMiller1** [comment]
Now that I have looked into this a little, I think I would accept it if it is documented better. This variable is only visibly documented in the help output from icecc where it seems unlikely somebody will look.  The comment in util.cpp is much more useful, but expecting users to read the source code to see it seems ugly.

Adding documentation in README.md (or perhaps split that file?) using the comment in util.cpp as a guide is a good start.  Make sure you mention that it adds significantly to compile time if this is on (because files are built twice, once locally), but you get the nicer error message. That way users can decide what is right for them.

I’m trying to decide if I want the user to see a message “You might get better error messages by enabling ICECC_CARET_WORKAROUND” every time this could apply.  One the one hand users probably want to know and decide for themselves, on the other hand if you have decided you it isn’t worth it getting spammed by the message is unfriendly. (perhaps if the variable is set don’t show the message?)

What are everyone’s thoughts on this?

**Comment by HenryMiller1** [comment]
I think the documentation changes made are enough.
