### ISSUE TITLE
Icecream not distributing tasks to remote nodes

### ISSUE THREAD

**Issue by msmithatcarmanahsigns** [icecc/icecream#198]
Using Ubuntu 16.04, I've installed icecc on three machines.  I have set the net name to icecc_net, and using Icecream Monitor I can see all three machines connected and showing the correct number of available threads for each machine.  However when I run make -j13, only the local machine is used for compilation.

I enabled debug output, and I see many lines that look like this:

ICECC[5998] 11:21:50: connected to /var/run/icecc/iceccd.socket
ICECC[5998] 11:21:50: <building_local>
ICECC[5971] 11:21:50: </building_local: 101ms>
ICECC[5969] 11:21:50: invoking: /usr/bin/cc

But no mention of distributing tasks to the other machines.

I tried to look at the log files but they are all empty.

Also, running iceccd -vvv on the remote nodes shows startup messages that look correct (it connects to the server), but once I start a compile job on the host machine they show no new output.  I also see no network activity.

**Comment by v-lopez** [comment]
I'm seeing the same issue in Ubuntu 14.04 using version 1.1rc2

**Comment by HenryMiller1** [comment]
This is going to require someone who sees this issue to investigate.  I'm running 14.04 and do not see this (though I'm not running a normal setup). We have the tests running in 14.04 and they at least are passing and part of the test is verifying that they distribute jobs.

The one provided log just says building local, but it isn't clear why it is building local.

**Comment by v-lopez** [comment]
Actually I tried with master and seems to be fixed, probably fixed by https://github.com/icecc/icecream/pull/165

**Comment by HenryMiller1** [comment]
seems to be fixed then, please reopen if master doesn't fix this for someone.

**Comment by tcloaa** [comment]
Is it possible to force the client to do jobs on other remote hosts?

I have tried the following methods:

1. export ICECC_TEST_REMOTEBUILD=1
2. g++ hello.cpp -c

But there is always log like:

```
ICECC[11924] 15:17:48: connect failed on /var/run/icecc/iceccd.socket
ICECC[11924] 15:17:48: connect failed on /var/run/iceccd.socket
ICECC[11924] 15:17:48: connected to /home/icecream1/.iceccd.socket
ICECC[11924] 15:17:52: native /tmp/icecc-envs/native/f460c155dc5bab0e735d143934a2d5d1.tar.gz
ICECC[11924] 15:17:52: env: x86_64 '/tmp/icecc-envs/native/f460c155dc5bab0e735d143934a2d5d1.tar.gz'
ICECC[11924] 15:17:52: hello.cpp compiled 1 times on x86_64
ICECC[11924] 15:17:52: building myself, but telling localhost
ICECC[11924] 15:17:52: invoking: /usr/bin/g++
ICECC[11924] 15:17:52: speed=15
```

**Comment by timblaktu** [comment]
@tcloaa I'm troubleshooting same error logs and am wondering if you made any headway with this? Are you running the icecc daemon as root, or normal user? Does your normal user have access to /var/run? I am currently seeing this issue (socket connection failures and limited remote jobs) and am currently running daemon as normal user in icecc group.

**Comment by llunak** [comment]
Please open a new issue if you have a problem. It's unlikely to work try to get something out of a 2-year old comment on an old closed issue.
