### ISSUE TITLE
Under some conditions -Werror triggers only under icecc

### ISSUE THREAD

**Issue by adam-trhon** [icecc/icecream#202]
Build of `ltrace` succeeds when building locally, but fails when building with icecream.

After some deeper investigation we figured out that they have `-Wall -Werror` on command line, this line in the code (for the ARM platform):

    assert(info->type != info->type);

and gcc does not show warnings if they are generated by preprocessor and preprocessing and compilation are done in one step.

When building locally, preprocessing and compilation are done in one step and the warning is not generated, because it is in macro. But when building remotely, preprocessing and compilation are split, warning is generated and `-Werror` causes compilation error.

We plan to patch ltrace, I reported the problem to gcc  [bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80369), but since at first glance it looks like an icecc problem, I think it sould be addressed here as well. 

I assume that a paragraph in the troubleshooting section would be enough. If you agree, I will prepare it.

**Comment by HenryMiller1** [comment]
I think the unfortunate answer to this from both gcc and icecream is "works as designed". The C preprocessor causes a lot of messes.  

A section in trouble shooting seems like the best we can do here, there is no way for the preprocessor to give this information to the compiler when you split the steps, and icecream has to split them. (unless/until someone implements "pump mode"). 

I would accept your addition to troubleshooting.
