### ISSUE TITLE
make -jXXX freezes later after starting

### ISSUE THREAD

**Issue by HeinrichGit** [icecc/icecream#237]
Ubuntu 16.04 LTS
ICECC 1.0.1-2

`make target -jxxx`

Its been working for a long time good after invoking the above, but for some time the system has started freezing after trying to invoke the above command. Each time it was advancing in compiling though, before everything freezes (the whole system, a hard reset is than needed)

So my question, when it happens to freeze again, where do I dig out the dump from, i.e. find the reason for freezing ?

**Comment by HenryMiller1** [comment]
The ubuntu packages are not setup to properly log.  I have reported this at https://bugs.launchpad.net/ubuntu/+source/icecc/+bug/1671926

I strongly suggest you upgrade to the latest -rc2, or better yet the latest master.  The 1.0.1 release is very old. We have made a number of fixes, and log a lot more error cases in master, which might help.  We are working hard to get a 1.1 release out soon.

**Comment by HeinrichGit** [comment]
I updated my icecc version. It is 1.0.1-2. Is it good enough?

If not, where do I get one (for ubuntu) ?

If yes, I think my problem is caused by excessive memory usage, i.e. icecc processes start consume too much memory, which causes ubuntu to freeze (which seems to be a known ubuntu bug). In this case, how do I control the memory used by icecc ?

**Comment by HenryMiller1** [comment]
The 1.0.1-2 package was created in 2014 (I'm not sure what source code they used). I would say it is far out of date.  I can't find a newer version in any ppa so you will need to create it yourself if you want it.

As for excessive memory usage, I have some ideas: I would like iceccd to limit local preprocessing (to the number of CPUs on your system). However I'm focuses on getting 1.1 out before I try to release that.

**Comment by HeinrichGit** [comment]
After downloading and building the -rc2 version, I observed similar issues: 
- make with -j > than my ubuntu machine (8GB physical cores, 4 cores (2 real one) ) can handle, it freezes again.
- Scanning dependencies of target xxx : takes longer than before.

**Comment by HeinrichGit** [comment]
After downloading and building the -rc2 version, I observed similar issues: 
- make with -j > than my ubuntu machine (8GB physical cores, 4 cores (2 real one) ) can handle, it freezes again.
- Scanning dependencies of target xxx : takes longer than before.

**Comment by llunak** [comment]
If your system hangs, the reason for freezing, if it can be found somewhere, is in the system logs. Unless this is #285 , which already has been handled, I doubt this is actually an Icecream problem - you simply overload your local system too much. Compile with smaller parallelism, or if you have expensive local build steps, serialize them by wrapping them in 'icerun'.
