### ISSUE TITLE
ICECC_CLANG_REMOTE_CPP=1 should use -fdirectives-only on gcc

### ISSUE THREAD

**Issue by RedBeard0531** [icecc/icecream#240]
It is roughly equivalent to clang's -frewrite-includes. It is actually slightly nicer because it also handles #if blocks locally so less code is shipped over the wire. We need this on our code base to work with -Werror and ld.gold's --detect-odr-violations (it uses line and column numbers which gcc -E changes without -fdirectives-only).

**Comment by llunak** [comment]
7ab429b5f3405ec8451c31f80573658c8818b972
