### ISSUE TITLE
icecc : make vs ninja

### ISSUE THREAD

**Issue by HeinrichGit** [icecc/icecream#242]
Does _icecc_ is supposed to work well with _ninja_ as well ?

**Comment by HenryMiller1** [comment]
icecc works well with ninja.  Most of my use of icecc is actually through ninja.

**Comment by HeinrichGit** [comment]
Are there any special configuration rules for ninja, different than for make?

e.g. if I want to use icecc with ccache ? (e.g. export CCACHE_PREFIX="icecc" ?)

**Comment by HenryMiller1** [comment]
Everything is the same. icecream doesn't interact with make or ninja in any way.

Note that one thing that is the same is the rule that you need to set a -j parameter that is fairly high.  Make defaults to -j 1 (for historical reasons), ninja defaults to -j [number of cpus on your system]. This default in ninja is to low to make icecream useful and so you need to specify a value yourself.

**Comment by HeinrichGit** [comment]
Yes, setting -j to a failrly high option is always the goal. But as have discussed in another topic already,  my ubuntu machine will freeze when the icecc processes/threads allocate the maximum of available RAM. So this would be a really urgent fix (at least for an ubuntu machine) : to not allocate until 100% of the RAM available.
