### ISSUE TITLE
Use 'as' from path when creating native environment

### ISSUE THREAD

**Issue by bkin** [icecc/icecream#245]
My objectfiles have different md5sums when I compare remote and local builds. This is due to the different assemblers used. icecc-create-env hardwires '/usr/bin/as' whereas I have a more recent version in '/usr/local/bin/as', which is early in my path.

I was trying to use 'icecc-create-env ... --addfile /usr/local/bin/as', but this creates the same path in the environment archive.

The following patch adds a search for the assembler in the path and fixes the issue for me:

       --- /dev/fd/63  2017-05-16 11:21:41.262614358 +0200                                              
       +++ /usr/lib/icecc/icecc-create-env     2017-05-16 10:59:19.190657684 +0200
    @@ -230,7 +230,7 @@
 
         gcc_as=$($added_gcc -print-prog-name=as)
         if test "$gcc_as" = "as"; then
    -      add_file /usr/bin/as
    +      add_file $( hash as >/dev/null 2>&1 && hash -t as ) /usr/bin/as
         else
           add_file "$gcc_as" /usr/bin/as
         fi

**Comment by HenryMiller1** [comment]
Why did you use hash instead of which? I don't think any use of hash from within your shell to set a different path will be transferred to the shell this script is running in, so I'm not seeing what advantage this might give you.

I think the idea is right, but unless you can justify using hash over which I don't want to accept it.

**Comment by bkin** [comment]
I read somewhere (tm) that 'hash' is more widely supported, but I don't have strong feelings about this at all. 'which' would be fine.

**Comment by llunak** [comment]
Where is your gcc (or whatever compiler you use) located and what is the output of "gcc -print-prog-name=as" ?

**Comment by bkin** [comment]
The gcc in question is installed in the non-standard path /opt/hacon/gcc_svn/bin.
The output of "/opt/hacon/gcc_svn/bin/gcc -print-prog-name=as" is "as".
I have two versions of "as" on my machine, both reached via PATH, the first in /usr/local/bin/as, the second in /usr/bin/as.

**Comment by llunak** [comment]
2b373a40d387c6781032bff6566bdccf256dd8c3. I went with 'command -v' (according to https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then).

**Comment by bkin** [comment]
Nice, thanks!
