### ISSUE TITLE
/var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable 

### ISSUE THREAD

**Issue by Fungie2134** [icecc/icecream#256]
I have an 6 computers cluster, and I wanted to use this. To try it, I compiled OpenCV with make -j17 ( the total number of cores ). But this is what I get in the logs :

> ICECC[7681] 15:03:48: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.45
ICECC[7681] 15:03:48: got exception 23 (192.168.0.45) 
[ 21%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfMisc.cpp.o
ICECC[7690] 15:03:49: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.45
ICECC[7690] 15:03:49: got exception 23 (192.168.0.45) 
[ 21%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStdIO.cpp.o
ICECC[7699] 15:03:50: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.45
ICECC[7699] 15:03:50: got exception 23 (192.168.0.45) 

Is there any way to fix this? I used the version which is in the Ubuntu 16.04 repository.

**Comment by HenryMiller1** [comment]
The version of icecream in Ubuntu repositories is very old. this problem is believed fixed in master.  I suggest building your own packages instead of the ones in ubuntu.

I'm hoping to release 1.1 soon, but there are a couple more outstanding issues I want fixed first. I hope ubuntu updates their packages after 1.1 is released.

**Comment by Fungie2134** [comment]
Thanks, I will ask to them to update because I know some peoples getting the same issue...
