### ISSUE TITLE
Disconnect when compilation start

### ISSUE THREAD

**Issue by Aang23** [icecc/icecream#257]
I have 8 nodes all showing up in icemon with 23 jobs max.
I run make -j23 and anything look like working, but some seconds after, almost all nodes disconnects... Is there a fix? I use a PXE cluster.

> make -j23
Scanning dependencies of target icemon_automoc
[  4%] Automatic moc for target icemon
Generating moc_fakemonitor.cpp
Generating moc_hostinfo.cpp
Generating moc_icecreammonitor.cpp
Generating moc_mainwindow.cpp
Generating moc_hostlistmodel.cpp
Generating moc_joblistmodel.cpp
Generating moc_monitor.cpp
Generating moc_statusview.cpp
Generating moc_detailedhostview.cpp
Generating moc_flowtableview.cpp
Generating moc_ganttstatusview.cpp
Generating moc_hostlistview.cpp
Generating moc_joblistview.cpp
Generating moc_listview.cpp
Generating moc_starview.cpp
Generating moc_summaryview.cpp
[  4%] Built target icemon_automoc
[  8%] Generating qrc_icemon.cpp
Scanning dependencies of target icemon
[ 12%] Building CXX object src/CMakeFiles/icemon.dir/fakemonitor.cc.o
[ 16%] Building CXX object src/CMakeFiles/icemon.dir/icecreammonitor.cc.o
[ 20%] Building CXX object src/CMakeFiles/icemon.dir/job.cc.o
[ 24%] Building CXX object src/CMakeFiles/icemon.dir/hostinfo.cc.o
[ 28%] Building CXX object src/CMakeFiles/icemon.dir/views/ganttstatusview.cc.o
[ 32%] Building CXX object src/CMakeFiles/icemon.dir/main.cc.o
[ 36%] Building CXX object src/CMakeFiles/icemon.dir/views/joblistview.cc.o
[ 40%] Building CXX object src/CMakeFiles/icemon.dir/qrc_icemon.cpp.o
[ 44%] Building CXX object src/CMakeFiles/icemon.dir/views/hostlistview.cc.o
[ 48%] Building CXX object src/CMakeFiles/icemon.dir/statusview.cc.o
[ 52%] Building CXX object src/CMakeFiles/icemon.dir/icemon_automoc.cpp.o
[ 56%] Building CXX object src/CMakeFiles/icemon.dir/mainwindow.cc.o
[ 60%] Building CXX object src/CMakeFiles/icemon.dir/views/flowtableview.cc.o
[ 64%] Building CXX object src/CMakeFiles/icemon.dir/monitor.cc.o
[ 68%] Building CXX object src/CMakeFiles/icemon.dir/utils.cc.o
[ 72%] Building CXX object src/CMakeFiles/icemon.dir/views/listview.cc.o
[ 76%] Building CXX object src/CMakeFiles/icemon.dir/views/detailedhostview.cc.o
[ 80%] Building CXX object src/CMakeFiles/icemon.dir/views/starview.cc.o
[ 84%] Building CXX object src/CMakeFiles/icemon.dir/models/joblistmodel.cc.o
[ 88%] Building CXX object src/CMakeFiles/icemon.dir/statusviewfactory.cc.o
[ 92%] Building CXX object src/CMakeFiles/icemon.dir/views/summaryview.cc.o
[ 96%] Building CXX object src/CMakeFiles/icemon.dir/models/hostlistmodel.cc.o
ICECC[14300] 16:27:21: write of source chunk to host 192.168.0.49
ICECC[14300] 16:27:21: failed  Broken pipe
ICECC[14300] 16:27:21: got exception 15 (192.168.0.49) 
ICECC[14308] 16:27:21: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14308] 16:27:21: got exception 23 (192.168.0.49) 
ICECC[14298] 16:27:21: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14298] 16:27:21: got exception 23 (192.168.0.49) 
ICECC[14302] 16:27:21: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14302] 16:27:21: got exception 23 (192.168.0.49) 
ICECC[14306] 16:27:22: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14306] 16:27:22: got exception 23 (192.168.0.49) 
ICECC[14307] 16:27:22: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14307] 16:27:22: got exception 23 (192.168.0.49) 
ICECC[14304] 16:27:22: write of source chunk to host 192.168.0.42
ICECC[14304] 16:27:22: failed  Connection reset by peer
ICECC[14304] 16:27:22: got exception 15 (192.168.0.42) 
ICECC[14301] 16:27:22: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14301] 16:27:22: got exception 23 (192.168.0.49) 
ICECC[14303] 16:27:22: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14303] 16:27:22: got exception 23 (192.168.0.49) 
ICECC[14305] 16:27:22: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14305] 16:27:22: got exception 23 (192.168.0.49) 
ICECC[14309] 16:27:22: /var/cache/icecc/target=x86_64/8cb5ffd1a9abb0e58e21523dff412c02/usr/bin/as is not executable - compiled on 192.168.0.49
ICECC[14309] 16:27:22: got exception 23 (192.168.0.49) 
ICECC[14257] 16:27:23: write of source chunk to host 192.168.0.46
ICECC[14257] 16:27:23: failed  Connection reset by peer
ICECC[14257] 16:27:23: got exception 15 (192.168.0.46) 
ICECC[14279] 16:27:23: write of source chunk to host 192.168.0.45
ICECC[14279] 16:27:23: failed  Connection reset by peer
ICECC[14279] 16:27:23: got exception 15 (192.168.0.45) 
ICECC[14299] 16:27:23: write of source chunk to host 192.168.0.41
ICECC[14299] 16:27:23: failed  Connection reset by peer
ICECC[14299] 16:27:23: got exception 15 (192.168.0.41) 
ICECC[14294] 16:27:23: write of source chunk to host 192.168.0.43
ICECC[14294] 16:27:23: failed  Connection reset by peer
ICECC[14294] 16:27:23: got exception 15 (192.168.0.43) 
ICECC[14283] 16:27:24: write of source chunk to host 192.168.0.44
ICECC[14283] 16:27:24: failed  Connection reset by peer
ICECC[14283] 16:27:24: got exception 15 (192.168.0.44) 
{standard input}: Assembler messages:
{standard input}: Fatal error: cannot fill 1 bytes in section .rodata of tmp/icecc-82_5024c849.o because: 'Stale file handle'
{standard input}: Fatal error: can't close tmp/icecc-82_5024c849.o: Stale file handle
ICECC[14243] 16:27:24: Compiled on 192.168.0.49
src/CMakeFiles/icemon.dir/build.make:120: recipe for target 'src/CMakeFiles/icemon.dir/icecreammonitor.cc.o' failed
make[2]: *** [src/CMakeFiles/icemon.dir/icecreammonitor.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:88: recipe for target 'src/CMakeFiles/icemon.dir/all' failed
make[1]: *** [src/CMakeFiles/icemon.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Fungie2134** [comment]
I do not get this problem when using distcc...

**Comment by HenryMiller1** [comment]
This looks like an old version of icecream. Problems like this have been seen from time to time and we have not been able to track down why. We recently added better logging to master in hopes that will help us track this down.

**Comment by tcloaa** [comment]
Hi @HenryMiller1 ,

Is it clear that why we will encounter exception 15 frequently?

Thanks,

**Comment by Fungie2134** [comment]
Hi, I'm always using the latest version, still getting this issue. Because of exception 15 local compilation is almost faster than using.

**Comment by HenryMiller1** [comment]
@tcloaa I have no idea.  It is obvious that somehow the environment we are sending to the remote is broken (which could be because the remote is broken), but I have no guess.

The only thing I can see in @Fungie2134 log is "broken pipe" which I think means we started something and it crashed, but it is hard to tell what might cause that.

**Comment by llunak** [comment]
Is this still a problem with a recent version of Icecream? If you get messages about exception 15, then you do not use the latest version.

**Comment by ericch1** [comment]
I see the infamous "usr/bin/as is not executable " within the many errors in the log..

Maybe it is related to issue #184 ?

**Comment by llunak** [comment]
No response from the original reporter, closing. As for the /usr/bin/as executable, let's track that either in #184 or please file a new issue from details about your problem.
