### ISSUE TITLE
icecc, run out of memory

### ISSUE THREAD

**Issue by FAKERINHEART** [icecc/icecream#258]
I use the icecream with release version 1.1rc2 for my distributed compilation. However, I find that sometimes the distributed compile server will out of memory while icecc outputs 'stderr: run out of memory'. I have tried decreasing the multiprocessor number of iceccd on each distributed compile server, but this problem still happen when my compilation work is too heavy. It seems that iceccd will use the memory of distributed compile servers unlimitedly.

Is there any method limiting the maximum memory that iceccd uses on on each distributed compile server?

3Q~~~

**Comment by HenryMiller1** [comment]
Can you try the latest master and paste the exact error message you are getting?  We have much better error reporting in master, which might be enough that I can figure out exactly where things failed.

I don't know of a method of limited memory directly. (I'm sure there are kernel tricks you can play but I don't know them) 

Are you sure it is the remotes running out of memory?  Your local machine can run out of memory and that seems more likely to cause  the symptoms you list. Maybe try decreasing the -j count to make.

**Comment by scottzhang** [comment]
I get same issue too. Even I only make -j 1 , I get same output. but sometimes some node success.

[marship@znwg-dhzhjk SMDSPProcessor]$ make -f *.mk
g++  -c  "/data/Projects/smdsolution/SMDSPProcessor/UL33.cpp" -Wall -g -fPIC -std=c++14 -Wno-unknown-pragmas -Wno-reorder -Wno-switch -Wno-deprecated-declarations  -o ./Debug/UL33.cpp.o -I. -I. -I.. -I../include -I../interface -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0 -I/usr/local/include/mongocxx/v_noabi -I/usr/local/include/bsoncxx/v_noabi -I../devroot/usr/local/include 
ICECC[13404] 20:55:33: connected to /var/run/icecc/iceccd.socket
ICECC[13404] 20:55:33: native /tmp/icecc-envs/native/e6d007abe75c9f8197ecb2d1ab4e9ec9.tar.gz
ICECC[13404] 20:55:33: env: x86_64 '/tmp/icecc-envs/native/e6d007abe75c9f8197ecb2d1ab4e9ec9.tar.gz'
ICECC[13404] 20:55:33: /data/Projects/smdsolution/SMDSPProcessor/UL33.cpp compiled 1 times on x86_64
ICECC[13404] 20:55:33: Have to use host 192.168.161.4:10245 - Job ID: 284 - env: x86_64 - has env: true - match j: 0
ICECC[13404] 20:55:33: connected to 192.168.161.4
ICECC[13404] 20:55:33: <send compile_file>
ICECC[13404] 20:55:33: </send compile_file: 0ms>
ICECC[13404] 20:55:33: <write_server_cpp from cpp>
ICECC[13404] 20:55:37: sent 1381062 bytes (19%)
ICECC[13404] 20:55:37: </write_server_cpp from cpp: 3660ms>
ICECC[13404] 20:55:37: <wait for cpp>
ICECC[13404] 20:55:37: </wait for cpp: 0ms>
ICECC[13404] 20:55:37: <wait for cs>
ICECC[13404] 20:55:42: </wait for cs: 5441ms>
ICECC[13404] 20:55:42: the server ran out of memory, recompiling locally
ICECC[13404] 20:55:42: got exception 17 (192.168.161.4) 
make: *** [Debug/UL33.cpp.o] Error 17

**Comment by scottzhang** [comment]
and on the same machine's iceccd -vvv output is as following: I can't see any obvious error from local machine, I guess, will the out of memory raised by local machine?

[root@znwg-dhzhjk marship]# /usr/local/icecc/sbin/iceccd -vvvv
Error: no icecc user on system. Falling back to nobody. Success
[9872] 20:52:38: ICECREAM daemon 1.0.1 starting up (nice level 5) 
[9872] 20:52:38: 16 CPU(s) online on this server
[9872] 20:52:38: allowing up to 16 active jobs
[9872] 20:52:38: not detaching
[9872] 20:52:38: already a process group leader
[9872] 20:52:38: ignoring localhost lo
[9872] 20:52:38: broadcast eth1 192.168.161.255
[9872] 20:52:38: broadcast virbr0 192.168.122.255
[9872] 20:52:38: Netnames:
[9872] 20:52:38: ICECREAM
[9872] 20:52:38: ignoring localhost lo
[9872] 20:52:38: broadcast eth1 192.168.161.255
[9872] 20:52:38: broadcast virbr0 192.168.122.255
[9872] 20:52:38: scheduler not yet found.
[9872] 20:52:38: scheduler is on 192.168.161.3:8765 (net ICECREAM)
[9872] 20:52:38: scheduler not yet found.
[9872] 20:52:40: accepted 7 58.0.0.0
[9872] 20:52:40: Connected to scheduler (I am known as 192.168.161.1)
[9872] 20:52:40: send JobLocalBeginMsg to client
[9872] 20:52:40: pushed local job 1
[9872] 20:53:02: eof && !HAS_MSG
[9872] 20:53:02: scheduler->send_msg( JobLocalDoneMsg( 1) );
[9872] 20:53:10: accepted 7 0.0.0.0
[9872] 20:53:10: send JobLocalBeginMsg to client
[9872] 20:53:10: pushed local job 2
[9872] 20:53:18: eof && !HAS_MSG
[9872] 20:53:18: scheduler->send_msg( JobLocalDoneMsg( 2) );
[9872] 20:53:22: accepted 7 0.0.0.0
[9872] 20:53:22: get_native_env  (gcc)
adding file /bin/true
adding file /lib64/libc.so.6
adding file /lib64/ld-linux-x86-64.so.2
adding file /usr/bin/gcc=/opt/rh/devtoolset-4/root/usr/bin/gcc
adding file /lib64/libm.so.6
adding file /usr/bin/g++=/opt/rh/devtoolset-4/root/usr/bin/g++
adding file /usr/bin/cc1=/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.2.1/cc1
adding file /lib64/libdl.so.2
adding file /usr/lib64/libmpfr.so.1
adding file /usr/lib64/libgmp.so.3
adding file /lib64/libz.so.1
adding file /usr/bin/cc1plus=/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.2.1/cc1plus
adding file /usr/bin/as=/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.2.1/as
adding file /opt/rh/devtoolset-4/root/usr/lib64/libopcodes-2.25-10.el6.so
adding file /opt/rh/devtoolset-4/root/usr/lib64/libbfd-2.25-10.el6.so
adding file /opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.2.1/liblto_plugin.so
adding file /etc/ld.so.conf=/tmp/icecc_ld_so_confoDXGee
creating e6d007abe75c9f8197ecb2d1ab4e9ec9.tar.gz
[9872] 20:53:52: waitpid 0
[9872] 20:53:52: native_environment /tmp/icecc-envs/native/e6d007abe75c9f8197ecb2d1ab4e9ec9.tar.gz
[9872] 20:53:52: cache_size = 22855350
[9872] 20:53:52: handle_get_cs 3
[9872] 20:53:52: handle_use_cs 283 3 0x15a83b0 192.168.161.4 192.168.161.1
[9872] 20:53:58: eof && !HAS_MSG
[9872] 20:53:58: scheduler->send_msg( JobDoneMsg( waitcompile 0.0.0.0: (B eof: 1) CID: 3 ID: 283 CS: 192.168.161.4, 118))
[9872] 20:55:33: accepted 7 0.0.0.0
[9872] 20:55:33: get_native_env /tmp/icecc-envs/native/e6d007abe75c9f8197ecb2d1ab4e9ec9.tar.gz (gcc)
[9872] 20:55:33: handle_get_cs 4
[9872] 20:55:33: handle_use_cs 284 4 0x15a83b0 192.168.161.4 192.168.161.1
[9872] 20:55:42: eof && !HAS_MSG
[9872] 20:55:42: scheduler->send_msg( JobDoneMsg( waitcompile 0.0.0.0: (B eof: 1) CID: 4 ID: 284 CS: 192.168.161.4, 118))

**Comment by scottzhang** [comment]
I could say 2 machines has enough memory, the local machine has 32G in total and 16G free. There other one has 8G in total and about 1.2G free by the time of compiling. I can't see the reason why compile a single file can get out of memory.
Another guess is about the g++, maybe the native-build-env crashed on another machine?

**Comment by scottzhang** [comment]
I confirmed it is really out of memory. I don't know how g++ use memory. I restart mongod on 8G machine, then the free memory is about 5.5G. The build success without problem.

**Comment by honwsn** [comment]
error the server ran out of memory, recompiling locally , happened many times ,why????   icecc use memory too large..

**Comment by llunak** [comment]
Remote compilations have their memory limited (using RLIMIT_AS, i.e. ulimit -v), you can see this in function work_it(). It's possible the limit is too low. But I don't think this can be debugged remotely, you'll need to try to find out yourself what the limits in your case are (or why the compiler needs so much memory).

**Comment by dantje** [comment]
cppcheck reports some realloc issues:

[services/comm.cpp:92]: (error) Common realloc mistake: 'inbuf' nulled but not freed upon failure
[services/comm.cpp:225]: (error) Common realloc mistake: 'inbuf' nulled but not freed upon failure
[services/comm.cpp:282]: (error) Common realloc mistake: 'msgbuf' nulled but not freed upon failure
[services/comm.cpp:533]: (error) Common realloc mistake: 'msgbuf' nulled but not freed upon failure

The code doesn't check for out-of-memory from inbuf/msgbuf reallocation, so if these were to fail, it would probably crash when dereferencing the nullptr shortly after.

**Comment by llunak** [comment]
Cppcheck is technically right about those, but I seriously doubt it matters in any way in practice. Icecream's own memory consumption is minimal and so presumably all OOM problems are from the invoked compiler. IMO trying to handle gracefully icecream's own (very unlikely) OOM is not worth the effort and if things got that far, the build would fail anyway.

**Comment by llunak** [comment]
As seen above, the daemon can now log memory limits, so if you still have this problem, please reopen and provide the asked-for details.
