### ISSUE TITLE
Support for -fsanitize-blacklist=file

### ISSUE THREAD

**Issue by RedBeard0531** [icecc/icecream#266]
This flag currently causes failures since the blacklist file isn't present on remote nodes.  For now I've worked around this by having the build system suppress the flag when the file is empty (which ours is for ASAN but not UBSAN). Has anyone managed to make it work? As a short-term solution, it may be worth having that flag force local builds.

**Comment by llunak** [comment]
Done in a2f0d7507c2fb87096c74582d05cdfc05c6e3e40.
