### ISSUE TITLE
Segfault with scheduler

### ISSUE THREAD

**Issue by ericch1** [icecc/icecream#270]
Hi, we are running with the git version 89da4f and have encountered 2 segfault since jul 7.

I used addr2line to retrieve a readable backtrace:
<pre>
/lib64/libc.so.6(+0x8fd9e)[0x7f64bea0ed9e]  __memcpy_sse2_unaligned at ??:?
/usr/lib64/libstdc++.so.6(_ZNSs4_Rep8_M_cloneERKSaIcEm+0x40)[0x7f64bf2fcfc0]
/usr/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x3c)[0x7f64bf2fd61c]
/opt/icecream-1.1/sbin/icecc-scheduler[0x408243] trace at /opt/icecream/scheduler/../services/logging.h:100 (inlined by) CompileServer::updateInConnectivity(bool) at /opt/icecream/scheduler/compileserver.cpp:489
/opt/icecream-1.1/sbin/icecc-scheduler[0x406189] main at /opt/icecream/scheduler/scheduler.cpp:2343
</pre>

Here is the full error with original backtrace:
<pre>
*** Segmentation fault
Register dump:

 RAX: ffff809b43ed6240   RBX: 0000000002646d40   RCX: 0000000004c435e0
 RDX: 0000000002621af0   RSI: 0000000002646d58   RDI: 00007f64bc14f028
 RBP: 00007f64bc14f010   R8 : 00000000ffffffff   R9 : 0000000000000000
 R10: 0000000000000022   R11: 0000000000000246   R12: 00007f64bf544960
 R13: 0000000000000002   R14: 0000000000002805   R15: 00007ffcd744fa80
 RSP: 00007ffcd744f6d8

 RIP: 00007f64bea0ed9e   EFLAGS: 00010202

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000004   OldMask: 00000000   CR2: 04c68838

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: 00000000   RDP: 00000000

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0000000000000000
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) 0000 0000000000000000   ST(7) 0000 0000000000000000
 mxcsr: 1fa0
 XMM0:  000000000000000000000000ffffff00 XMM1:  000000000000000000000000ffffff00
 XMM2:  000000000000000000000000ffffff00 XMM3:  000000000000000000000000ffffff00
 XMM4:  000000000000000000000000ffffff00 XMM5:  000000000000000000000000ffffff00
 XMM6:  000000000000000000000000ffffff00 XMM7:  000000000000000000000000ffffff00
 XMM8:  000000000000000000000000ffffff00 XMM9:  000000000000000000000000ffffff00
 XMM10: 000000000000000000000000ffffff00 XMM11: 000000000000000000000000ffffff00
 XMM12: 000000000000000000000000ffffff00 XMM13: 000000000000000000000000ffffff00
 XMM14: 000000000000000000000000ffffff00 XMM15: 000000000000000000000000ffffff00

Backtrace:
/lib64/libc.so.6(+0x8fd9e)[0x7f64bea0ed9e]
/usr/lib64/libstdc++.so.6(_ZNSs4_Rep8_M_cloneERKSaIcEm+0x40)[0x7f64bf2fcfc0]
/usr/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x3c)[0x7f64bf2fd61c]
/opt/icecream-1.1/sbin/icecc-scheduler[0x408243]
/opt/icecream-1.1/sbin/icecc-scheduler[0x406189]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f64be9a0b05]
/opt/icecream-1.1/sbin/icecc-scheduler[0x4077a7]

Memory map:

00400000-0042d000 r-xp 00000000 00:25 111661                             /opt/icecream-1.1/sbin/icecc-scheduler
0062c000-0062d000 r--p 0002c000 00:25 111661                             /opt/icecream-1.1/sbin/icecc-scheduler
0062d000-0062e000 rw-p 0002d000 00:25 111661                             /opt/icecream-1.1/sbin/icecc-scheduler
025e5000-02606000 rw-p 00000000 00:00 0                                  [heap]
02606000-02668000 rw-p 00000000 00:00 0                                  [heap]
7f64bc14f000-7f64be77a000 rw-p 00000000 00:00 0 
7f64be77a000-7f64be77e000 r-xp 00000000 00:1f 232837                     /lib64/libSegFault.so
7f64be77e000-7f64be97d000 ---p 00004000 00:1f 232837                     /lib64/libSegFault.so
7f64be97d000-7f64be97e000 r--p 00003000 00:1f 232837                     /lib64/libSegFault.so
7f64be97e000-7f64be97f000 rw-p 00004000 00:1f 232837                     /lib64/libSegFault.so
7f64be97f000-7f64beb1d000 r-xp 00000000 00:1f 232840                     /lib64/libc-2.19.so
7f64beb1d000-7f64bed1c000 ---p 0019e000 00:1f 232840                     /lib64/libc-2.19.so
7f64bed1c000-7f64bed20000 r--p 0019d000 00:1f 232840                     /lib64/libc-2.19.so
7f64bed20000-7f64bed22000 rw-p 001a1000 00:1f 232840                     /lib64/libc-2.19.so
7f64bed22000-7f64bed26000 rw-p 00000000 00:00 0 
7f64bed26000-7f64bed3c000 r-xp 00000000 00:1f 2398                       /lib64/libgcc_s.so.1
7f64bed3c000-7f64bef3b000 ---p 00016000 00:1f 2398                       /lib64/libgcc_s.so.1
7f64bef3b000-7f64bef3c000 r--p 00015000 00:1f 2398                       /lib64/libgcc_s.so.1
7f64bef3c000-7f64bef3d000 rw-p 00016000 00:1f 2398                       /lib64/libgcc_s.so.1
7f64bef3d000-7f64bf03d000 r-xp 00000000 00:1f 232848                     /lib64/libm-2.19.so
7f64bf03d000-7f64bf23c000 ---p 00100000 00:1f 232848                     /lib64/libm-2.19.so
7f64bf23c000-7f64bf23d000 r--p 000ff000 00:1f 232848                     /lib64/libm-2.19.so
7f64bf23d000-7f64bf23e000 rw-p 00100000 00:1f 232848                     /lib64/libm-2.19.so
7f64bf23e000-7f64bf328000 r-xp 00000000 00:1f 2752                       /usr/lib64/libstdc++.so.6.0.19
7f64bf328000-7f64bf527000 ---p 000ea000 00:1f 2752                       /usr/lib64/libstdc++.so.6.0.19
7f64bf527000-7f64bf52f000 r--p 000e9000 00:1f 2752                       /usr/lib64/libstdc++.so.6.0.19
7f64bf52f000-7f64bf531000 rw-p 000f1000 00:1f 2752                       /usr/lib64/libstdc++.so.6.0.19
7f64bf531000-7f64bf546000 rw-p 00000000 00:00 0 
7f64bf546000-7f64bf549000 r-xp 00000000 00:1f 232846                     /lib64/libdl-2.19.so
7f64bf549000-7f64bf748000 ---p 00003000 00:1f 232846                     /lib64/libdl-2.19.so
7f64bf748000-7f64bf749000 r--p 00002000 00:1f 232846                     /lib64/libdl-2.19.so
7f64bf749000-7f64bf74a000 rw-p 00003000 00:1f 232846                     /lib64/libdl-2.19.so
7f64bf74a000-7f64bf74e000 r-xp 00000000 00:1f 2494                       /usr/lib64/libcap-ng.so.0.0.0
7f64bf74e000-7f64bf94e000 ---p 00004000 00:1f 2494                       /usr/lib64/libcap-ng.so.0.0.0
7f64bf94e000-7f64bf94f000 r--p 00004000 00:1f 2494                       /usr/lib64/libcap-ng.so.0.0.0
7f64bf94f000-7f64bf950000 rw-p 00005000 00:1f 2494                       /usr/lib64/libcap-ng.so.0.0.0
7f64bf950000-7f64bf970000 r-xp 00000000 00:1f 2294                       /usr/lib64/liblzo2.so.2.0.0
7f64bf970000-7f64bfb70000 ---p 00020000 00:1f 2294                       /usr/lib64/liblzo2.so.2.0.0
7f64bfb70000-7f64bfb71000 r--p 00020000 00:1f 2294                       /usr/lib64/liblzo2.so.2.0.0
7f64bfb71000-7f64bfb72000 rw-p 00021000 00:1f 2294                       /usr/lib64/liblzo2.so.2.0.0
7f64bfb72000-7f64bfb92000 r-xp 00000000 00:1f 232833                     /lib64/ld-2.19.so
7f64bfd7a000-7f64bfd80000 rw-p 00000000 00:00 0 
7f64bfd90000-7f64bfd92000 rw-p 00000000 00:00 0 
7f64bfd92000-7f64bfd93000 r--p 00020000 00:1f 232833                     /lib64/ld-2.19.so
7f64bfd93000-7f64bfd94000 rw-p 00021000 00:1f 232833                     /lib64/ld-2.19.so
7f64bfd94000-7f64bfd95000 rw-p 00000000 00:00 0 
7ffcd7430000-7ffcd7451000 rw-p 00000000 00:00 0                          [stack]
7ffcd75e3000-7ffcd75e5000 r-xp 00000000 00:00 0                          [vdso]
7ffcd75e5000-7ffcd75e7000 r--p 00000000 00:00 0                          [vvar]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
</pre>

Thanks,

Eric

**Comment by HenryMiller1** [comment]
this is concerning, but I cannot guess why something might crash there - in logging.

This seems to be repeatable for you, would you be willing/able to put some more logging into the code there?  That is log each component of trace separately to see what we are trying to log.  I'm wondering if there is a null pointer in something unexpectedly.

**Comment by ericch1** [comment]
It happened 2 times only, but yes, I will happily patch the code or cherry-pick something you will give me!

**Comment by HenryMiller1** [comment]
I created a branch https://github.com/HenryMiller1/icecream/tree/scheduler-segfault-logging for this.  I don't want to merge this, but I hope it will help narrow down where things are failing, and that might be the clue needed.

**Comment by llunak** [comment]
Has there been any progress with this? Is this still an issue?

**Comment by ericch1** [comment]
I have not seen this problem after the reported date...

Eric

**Comment by llunak** [comment]
Ok, closing then.
