### ISSUE TITLE
[Question]Don't recommend use packages maintained by your distribution for installation?

### ISSUE THREAD

**Issue by tcloaa** [icecc/icecream#271]
In README, it is said that, `We recommend that you use packages maintained by your distribution if possible. `

But actually, the icecc version by `apt-get` still remains as 1.0.1, which now ICECC is 1.1rc3.

Does it mean that from now on, we shall all build from source?

Thanks,

**Comment by HenryMiller1** [comment]
The recommendation is correct. Some distributions are not good about updating packages. (they may have a policy of not updating to non release versions) I'm hoping to release 1.1 next week, unless someone reports a new bug. 
--
  Henry Miller
  hank@millerfarm.com



On Thu, Jul 13, 2017, at 04:56 AM, tcloaa wrote:
> In README, it is said that, We recommend that you use packages maintained by your distribution if possible.> But actually, the icecc version by apt-get still remains as 1.0.1, which now ICECC is 1.1rc2.> Does it mean that from now on, we shall all build from source?


> Thanks,


> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2]. > 

Links:

  1. https://github.com/icecc/icecream/issues/271
