### ISSUE TITLE
./configure always telling `error: libcap-ng library was not found`

### ISSUE THREAD

**Issue by tcloaa** [icecc/icecream#272]
HI @HenryMiller1 
I tried to build from source Ubuntu.

And from apt-get, I almost tried out:

libcap-ng0
libcap-ng-dev
libcap-ng-utils

but still, ./configure --prefix=/opt/icecream told me that : "error: libcap-ng library was not found"

Thanks

**Comment by HenryMiller1** [comment]
You need to install libcap-ng there should be a package you can use. 

--
  Henry Miller
  hank@millerfarm.com



On Thu, Jul 13, 2017, at 06:08 AM, tcloaa wrote:
> HI @HenryMiller1[1]
>  I tried to build from source Ubuntu.


> And from apt-get, I almost tried out:


> libcap-ng0
>  libcap-ng-dev
>  libcap-ng-utils


> but still, ./configure --prefix=/opt/icecream told me that : "error: libcap-ng library was not found"> Thanks


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3]. > 

Links:

  1. https://github.com/henrymiller1
  2. https://github.com/icecc/icecream/issues/272

**Comment by tcloaa** [comment]
I am sorry, but I tried out every package available from apt-get

![screenshot from 2017-07-14 09 19 14](https://user-images.githubusercontent.com/8750937/28194237-8fcbb6d6-6875-11e7-99df-3c0fba4b9a41.png)

**Comment by HenryMiller1** [comment]
I was able to install 

sudo apt-get libcap-ng-dev

on ubuntu 14.04 I get the package version 0.7.3-1ubuntu2 and everything builds. The .travis.yml file builds icecream on ubuntu 14.04 so you can look there as well.
--
  Henry Miller
  hank@millerfarm.com



On Thu, Jul 13, 2017, at 08:19 PM, tcloaa wrote:
> I am sorry, but I tried out every package available from apt-get


> screenshot from 2017-07-14 09 19 14


> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2]. > 


Links:

  1. https://github.com/icecc/icecream/issues/272#issuecomment-315243498

**Comment by dipika21** [comment]
below command solved my error:

apt-get install -y libcap*
