### ISSUE TITLE
[Question] building myself, but telling localhost

### ISSUE THREAD

**Issue by tcloaa** [icecc/icecream#273]
Hi @HenryMiller1 , I am running a cluster with 1 daemon+scheduler and 3 daemons.

Why I type ICECC_DEBUG=1 g++ hello.cpp -c, it is always telling me that: building myself, but telling localhost.

In the running log:

ICECC[1069] 13:36:55: connect failed on /var/run/icecc/iceccd.socket
ICECC[1069] 13:36:55: connect failed on /var/run/iceccd.socket
ICECC[1069] 13:36:55: connected to /home/icecream1/.iceccd.socket
ICECC[1069] 13:36:55: native /tmp/icecc-envs/native/f460c155dc5bab0e735d143934a2d5d1.tar.gz
ICECC[1069] 13:36:55: env: x86_64 '/tmp/icecc-envs/native/f460c155dc5bab0e735d143934a2d5d1.tar.gz'
ICECC[1069] 13:36:55: hello.cpp compiled 1 times on x86_64
ICECC[1069] 13:36:55: building myself, but telling localhost
ICECC[1069] 13:36:55: invoking: /usr/bin/g++
ICECC[1069] 13:36:56: speed=14

In the scheduler log:

[440] 13:39:47: NEW 351 client=icecream1-VirtualBox versions=[f460c155dc5bab0e735d143934a2d5d1(x86_64)] sf_vm_shared/icc/hello.cpp C++
[440] 13:39:47: put 351 in joblist of icecream1-VirtualBox
[440] 13:39:47: BEGIN: 351 client=icecream1-VirtualBox(x86_64) server=icecream1-VirtualBox(x86_64)
[440] 13:39:47: END 351 status=0 in=0(0%) out=2176(0%) real=248 user=148 sys=40 pfaults=6517 server=icecream1-VirtualBox

The job I am conducting is compiling linux kernel. It is like that the scheduler will only assign very few jobs out to other remote daemons.

In remote daemons:
![screenshot from 2017-07-14 15 52 10](https://user-images.githubusercontent.com/8750937/28203459-6d523a1c-68ac-11e7-929a-5f71e128360f.png)

What can I do to make sure that it will always use remote servers for build? ( Actually I wanna see how I can trigger Exception 15: Resource Unavaiable so that I wanna congest the network)

Thanks,

**Comment by HenryMiller1** [comment]
There are many compiler options (the list is always changing) the force a build to build locally.

**Comment by tcloaa** [comment]
ah...? sorry but actually I wanna force to build remotely...
