### ISSUE TITLE
[Question] unlink failure

### ISSUE THREAD

**Issue by tcloaa** [icecc/icecream#275]
From compiling log (client):
```
ICECC[8202] 15:45:06: <send compile_file>
ICECC[8202] 15:45:06: </send compile_file: 0ms>
# then keep blanking without continuing compiling
```

From scheduler `-vvv`:
```
[6576] 15:44:50: BEGIN: 40 client=icecream1-VirtualBox(x86_64) server=icecream2(x86_64)
[6576] 15:45:06: NEW 42 client=icecream1-VirtualBox versions=[f460c155dc5bab0e735d143934a2d5d1(x86_64)] icc/1icecream/test.cc C++
[6576] 15:45:06: no job stats - returning randomly selected icecream2 load: 0 can install: x86_64
[6576] 15:45:06: put 42 in joblist of icecream2
[6576] 15:45:06: BEGIN: 42 client=icecream1-VirtualBox(x86_64) server=icecream2(x86_64)
[6576] 15:45:54: END 40 status=-1
[6576] 15:46:06: END 42 status=-1
```

From job-receiving server:
![screenshot from 2017-07-18 15 49 32](https://user-images.githubusercontent.com/8750937/28306126-b66c382a-6bd0-11e7-938b-fe497cd98f1a.png)

And, if I kill the compilation job, then my job-sender daemon will crash:
```
iceccd: main.cpp:1503: void Daemon::handle_end(Client*, int): Assertion `false' failed.
Aborted (core dumped)
```

Does anybody have ideas on what is going on here?

Thanks,

**Comment by HenryMiller1** [comment]
I think the unlink failure message is just a cascading symptom of whatever caused the file transfer to fail in the first place.  I'm not sure why the file isn't transferring correctly though.

**Comment by HenryMiller1** [comment]
I'm not clear on what issue you are reporting here, do you mean that something fails in your builds and the unlink_failure is a symptom of it?  Or do you mean you kill a compilation job and sometimes the daemon asserts? Both are potentially valid bugs to report, and are unlikely to be related.  

If you are interested in both please report them separately.

**Comment by llunak** [comment]
The unlink failure message is bogus. Some of the unlink() calls are there merely to clean up after a failed compilation attempt and it doesn't make sense to report that a file that is to be deleted already doesn't exist. I've already fixed some of those, there are possibly more.

**Comment by llunak** [comment]
No reply for months, closing. If you can still provide the requested information, please reopen.
