### ISSUE TITLE
Raise default for --cache-limit

### ISSUE THREAD

**Issue by RedBeard0531** [icecc/icecream#276]
The current default is 100MB, which seems too low given that each environment is ~60MB. This means that you can only fit a single environment on each server. I think that has caused a few failures in our cluster when multiple people are simultaneously building and wiping each other's environments out. I think either 500MB or 1GB would make a better default.

This problem is compounded by the init scripts used by at least ubuntu and arch not providing a way to set the cache limit, which makes the default more important.

**Comment by HenryMiller1** [comment]
Please raise a bug with ubuntu/debian and arch that their packages do not allow configuring this parameter.  This is something that we expect system administrators to configure.

I'm not sure I want to raise this limit - I know disk space is cheap, but we don't want to use all the disk space on someone (and the cache is on /var which traditionally was a small file system).  I'll have to think about this.  Does anyone else have data I should look at?

**Comment by RedBeard0531** [comment]
> Please raise a bug with ubuntu/debian and arch that their packages do not allow configuring this parameter. This is something that we expect system administrators to configure.

They seem to be based off of the [config file in this repo](https://github.com/icecc/icecream/blob/master/suse/sysconfig.icecream) that does not include a tunable for this.

I poked around at the code, and maybe a reasonable compromise would be to make the "native" rules apply to all environments. [This line](https://github.com/icecc/icecream/blob/2e7bb99/daemon/main.cpp#L1084) in particular seems important, but I'm far from an expert in this code. Additionally, I'm not exactly sure what makes a particular environment "native", but it seems like we never have native environments in our cluster even though it is exclusively x64 linux (of various distros) without any cross compilation (yet). Do I need to do something special when building the environment or setting ICECC_VERSION?

**Comment by llunak** [comment]
Looking at Daemon::check_cache_size(), the cache size is not a hard limit:
- An environment is kept at least 200 seconds after it was used.
- Native environments (which I think means the ones sent automatically by the system without requiring ICECC_VERSION set) are kept for at least a day after they've been installed.

So if the best you have is that you think that this might have caused your problems, better evidence is needed. If nothing else, raising the size limit wouldn't really fix the actual problem anyway.

**Comment by llunak** [comment]
The default has been raised to 256MiB, which I think is a reasonable default, and if somebody has specific needs, the setting can be changed using --cache-limit -> closing.
