### ISSUE TITLE
I met a problem: icecc throw error 30

### ISSUE THREAD

**Issue by huangjianxing4hw** [icecc/icecream#277]
Hi,erveryone. I met a problem , more then half past times one day ,icecc throw erro 30 :ICECC[70600] 20:16:16: got exception Error 30 - error closing temp file (100.120.231.253).   then  compiling  broken.

**Comment by HenryMiller1** [comment]
Please check out #278 - this doesn't fix anything, but it adds some logging which hopefully will tell us better what is failing on your system.

**Comment by HenryMiller1** [comment]
This is strange, I'm not sure why you cannot close a file that is open and your are writing it...  

Can you test again with the environment variable ICECC_DEBUG=DEBUG?

**Comment by llunak** [comment]
No reply for months, closing. If you can still provide the requested information, please reopen.
