### ISSUE TITLE
Limit load on local machine in preprocessing phase

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icecream#285]
When building with a large cluster the correct thing to do is to run make with large -j values. However this will result in make issuing many compile jobs at the same time, all of which compete for local CPU resources to run the preprocessing phase before sending the compilation to a remote machine. This makes the system respond poorly at best, and likely results in worse overall throughput in some of the worst cases.

https://github.com/icecc/icecream/commit/1c15f6b9c6ddd329e4fe1e2a03c7420a0407ae25 was an attempt to solve this problem, but it was reverted due to #280 and #282.

**Comment by llunak** [comment]
Do you have actually any numbers to support this? My machine (8-core AMD FX-8350) can run 100 preprocessing runs of "#include <Qt/QtGui>" in about 2-3 seconds, and all of those are started only after the scheduler assigns a remote host for the compilation. And I rather doubt icecream could realistically supply 100 remote compilations withing several seconds, although I can't test that.

If the -j number is too high for the machine, I doubt preprocessing is the bottleneck.

**Comment by HenryMiller1** [comment]
This depends very much.  I have found that with gcc 5.2 building helloword with C++98 preprocesses in ~ 200ms, while just turning on C++14 brings that time to 500ms.  Including just gmock.h adds 500ms (I don't recall which compiler I used for this, gcc 4.4 most likely).  These were small tests, just building the one file so parallel jobs were not in play. Results were repeatable though so any disk cache was warm.

My real goal is to run "make -j" which is to say infinite parallel jobs, with the trust that my network (50 machines most with 6 cores) and let icecream manage the load. (I still need a way to manage the all the things that cannot be distributed)

**Comment by llunak** [comment]
Hmm. I don't see a noticeable difference with different -std= options. And note that current master runs -E -fdirectives-only, which further reduces the local time. Either way, feel free to work on this if you find it worth it, but I myself think if local preprocessing is slow, it can't sufficiently feed remotes anyway and using a reasonable -j should be a much simpler way to handle this.

> (I still need a way to manage the all the things that cannot be distributed)

icerun <command>

**Comment by cdyson37** [comment]
I wonder if one option would be to delay preprocessing until there's a free slot for the actual build stage? I know that's inherently racy but possibly some heuristic could be used? It's quite easy to blow up a computer if you use a large enough -j and have heavy preprocessing.

@llunak what do you mean by "icerun"?

**Comment by llunak** [comment]
> @llunak what do you mean by "icerun"?

icerun is like icecc, but it will always run the given command locally. So if you e.g. run make -j50 and your machine gets killed by memory problems because of 50 linking processes, invoking them using icerun will limit them up to the number of CPU cores available locally (i.e. as if you didn't use icecream and make -j50).

**Comment by llunak** [comment]
Handled by #486.
