### ISSUE TITLE
clang multiple -arch options not supported

### ISSUE THREAD

**Issue by martinm82** [icecc/icecream#290]
Good morning,

I started to setup an icecc (1.1) cluster on macOS (10.12.2) nodes which should build at some point for macOS x86_64 and iOS x86/x86_64/arm using local Xcode (8.2.1) installations.

When running a build I ran into the following error caused by clang:

```
clang: error: cannot use 'c++' output with multiple -arch options
```

So I started digging in iceccc and debugging it a bit and figured out that it is the preprocessing step which is ran locally.

When running the following command:

```
./client/icecc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -ftemplate-depth-512 -fmessage-length=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -mios-simulator-version-min=9.3 -arch i386 -arch x86_64 -std=gnu++11 -o main.cxx.o -c main.cxx
```

the client is converting the command to:

```
forking /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms
/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -stdlib=libc++ -ftemplate-depth-512 -fmessage-length=0 -mios-simulator-version-min=9.3 -arch i386 -arch x86_64
-std=gnu++11 -fcolor-diagnostics -E main.cxx -frewrite-includes
```

As we can see the command changed for preprocessing only (`-E`) which is resulting in the error message above.

After checking how ccache is handling this issue icecc would need to run the preprocessor for each `-arch`, send the source(s) to the remote, compile them and merge the object files(e.g. using lipo). Of course we would need to ensure that both preprocessed sources are send to the same remote.

So something what clang is doing internally:
```
# "i386-apple-darwin16.6.0" - "clang", inputs: ["main.cxx"], output: "/var/folders/m1/vh73sp0j6977zygp5whhgrq40000gn/T/main-e3b382.o"
# "x86_64-apple-darwin16.6.0" - "clang", inputs: ["main.cxx"], output: "/var/folders/m1/vh73sp0j6977zygp5whhgrq40000gn/T/main-aac2f6.o"                               
# "x86_64-apple-darwin16.6.0" - "darwin::Lipo", inputs: ["/var/folders/m1/vh73sp0j6977zygp5whhgrq40000gn/T/main-e3b382.o", "/var/folders/m1/vh73sp0j6977zygp5whhgrq40000gn/T/main-aac2f6.o"], output: "main.cxx.o"
```

Did someone already thought about this topic? What do you think about this approach by sending for each archictecture the preprocessed file and use lipo on the remote side?

Or what about the "pump" mode that someone has started working on in the 'sendheaders' branch?

**Comment by martinm82** [comment]
Actually my approach for removing the arch arguments is wrong. I will need to split the preprocessing calls and call the preprocessor one by one. Similar what ccache does as well.

**Comment by llunak** [comment]
Actually, ccache handles multiple -arch by throwing up hands in the air, saying it's too hard and passing the compilation directly to the compiler without doing anything. So I've made icecream make the same, i.e. go with forced local compilation. While you're right that icecream could possibly do all the complicated steps to handle this, it doesn't seem to be worth it, and even if, it'd need somebody who could implement and test it. So unless you want to implement that yourself, this is it.
