### ISSUE TITLE
why iceccd exited? 

### ISSUE THREAD

**Issue by huangjianxing4hw** [icecc/icecream#291]
build error,and daemon(icecced) has  exited, what's the matter with the daemon, this is the log :
ICECC[90447] 14:26:22: got_server_for_job 127.0.0.1
ICECC[90454] 14:26:22: building myself, but telling localhost
ICECC[90454] 14:26:22: invoking: /usr/bin/gcc
ICECC[90447] 14:26:22: got_server_for_job 127.0.0.1
ICECC[90457] 14:26:22: building myself, but telling localhost
ICECC[90457] 14:26:22: invoking: /usr/bin/gcc
ICECC[90457] 14:26:22: flush_writebuf() failed Broken pipe
ICECC[90457] 14:26:22: Have to use host 127.0.0.1:10245 - Job ID: 1324543 - env:  - has env: true - match j: 0
ICECC[90457] 14:26:22: no server found behind given hostname 127.0.0.1:10245
ICECC[90457] 14:26:22: build_remote_int failed and has thrown Error 2 - no server found at 127.0.0.1
ICECC[90457] 14:26:22: wait failed No child processes
ICECC[90457] 14:26:22: wait failed No child processes
ICECC[90457] 14:26:22: wait failed No child processes

**Comment by HenryMiller1** [comment]
Can you get logs from the daemon when this happens?

I've observed a few cases where the daemon is no longer running on various machines, but I have never been able to figure out what is happening, and your logs are not providing useful information either.

**Comment by llunak** [comment]
No reply for 2+ months, closing. If you can still provide the requested information, please reopen.
