### ISSUE TITLE
how many iceccd can join to a scheduler?

### ISSUE THREAD

**Issue by huangjianxing4hw** [icecc/icecream#295]
HI,We have more than 3000 VM, and will deploy icecc. how many icecc daemon  can be mangered by one scheduler?
Thank you!

**Comment by HenryMiller1** [comment]
There isn't a hard coded limit.  I'm not sure how our algorithms handle this situation though.  I generally run with 50 nodes and see no problem, but 3000 is several orders of magnitude more.

I do find the idea of running icecc in a VM concerning though: if you are running one VM per physical machine there should be no problem, but if you are running more make sure that icecream doesn't try to use more CPUs across all VMs than physically exist. I run icecc in a VM all the time, but only one VM with 6 CPUs (my machine physically has 8)
