### ISSUE TITLE
Build conftest.c locally

### ISSUE THREAD

**Issue by tbe** [icecc/icecream#300]
To avoid blocking of hosts and long stale times during the execution of autoconf scripts, `conftest.c` should be forced to compile on the local system.

See https://github.com/distcc/distcc/blob/848e4be57bd1c3db30bd1b767660736d77585ca9/src/filename.c#L293

**Comment by llunak** [comment]
While this sort of makes sense, in practice I don't see the point of this. Do you have such problems often? If yes, then you should have exactly the same kind of problems during normal compiles. And in that case what's the point of special-casing just one instance of the problem?

**Comment by HenryMiller1** [comment]
It makes sense if it is more generic. The overhead of ice cream seems to be 100ms. Autoconf is single threaded so every 10 try compiles will add a second of ice cream overhead. These are all trivial files that build in a few ms, so the difference is noticeable overall. 

Cmake has the same problem. Many try complies of trivial files. I would assume that all other portable buildsystems do as well.  Thus I don't want to special case Autoconf, I want a generic way to know if we are in a single threaded configuration phase. This means should be shared with distcc, so any proposal needs to be discussed with them. 

For now I export ICECE=no when running cmake, it makes a big difference.

**Comment by tbe** [comment]
Also, as many autoconf tests may fail, it seems like icecc is marking the executing node as down.

**Comment by coolo** [comment]
doing so for performance overhead makes sense, but icecc shouldn't care if the complicated failed or not. If that's the case (for you) that's a different issue.

**Comment by llunak** [comment]
https://github.com/icecc/icecream/pull/402 has implemented this for configure. I haven't found a good way to detect icecc is called from cmake, so unless somebody knows, there's not much more to do. As this is only a performance improvement, closing.
