### ISSUE TITLE
HELP:  Release 1.1 scheduler Segmentation fault when whole system silence.

### ISSUE THREAD

**Issue by guyibin** [icecc/icecream#301]
*** Segmentation fault
Register dump:

 RAX: 0000000000000000   RBX: 00000000006c5200   RCX: 0000000000006aeb
 RDX: 000000000067a3e0   RSI: 0000000000a6bf98   RDI: 00007fe2067afda8
 RBP: 00007fe206409010   R8 : 0000000000000000   R9 : 0000000000000000
 R10: 0000000000000000   R11: 0000000000000000   R12: 0000000000000000
 R13: 0000000000000000   R14: 0000000000000000   R15: 0000000000002805
 RSP: 00007fff4b487bb8

 RIP: 00007fe20711aa6b   EFLAGS: 00010207

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000004   OldMask: 00000000   CR2: 00a6c000

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: 00000000   RDP: 00000000

 ST(0) 0000 0000000000000034   ST(1) 0000 000000000000000c
 ST(2) 0000 0000000000000000   ST(3) 0000 0000000000000000
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) ffff e600000000000000   ST(7) 0000 0000000000000000
 mxcsr: 1fa4
 XMM0:  000000000000000000000000ffff0000 XMM1:  000000000000000000000000ffff0000
 XMM2:  000000000000000000000000ffff0000 XMM3:  000000000000000000000000ffff0000
 XMM4:  000000000000000000000000ffff0000 XMM5:  000000000000000000000000ffff0000
 XMM6:  000000000000000000000000ffff0000 XMM7:  000000000000000000000000ffff0000
 XMM8:  000000000000000000000000ffff0000 XMM9:  000000000000000000000000ffff0000
 XMM10: 000000000000000000000000ffff0000 XMM11: 000000000000000000000000ffff0000
 XMM12: 000000000000000000000000ffff0000 XMM13: 000000000000000000000000ffff0000
 XMM14: 000000000000000000000000ffff0000 XMM15: 000000000000000000000000ffff0000

Backtrace:
/lib64/libc.so.6(memcpy+0x3fb)[0x7fe20711aa6b]
/usr/lib64/libstdc++.so.6(_ZNSs4_Rep8_M_cloneERKSaIcEm+0x72)[0x7fe20795c462]
/usr/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x3c)[0x7fe20795cb6c]
icecc-scheduler[0x4058c0]
icecc-scheduler[0x407d51]
icecc-scheduler[0x416588]
/lib64/libc.so.6(__libc_start_main+0xe6)[0x7fe2070b4c36]
icecc-scheduler[0x4051a9]

Memory map:

00400000-0042c000 r-xp 00000000 ca:02 1312685                            /usr/local/bin/icecc-scheduler (deleted)
0062b000-0062c000 r--p 0002b000 ca:02 1312685                            /usr/local/bin/icecc-scheduler (deleted)
0062c000-0062d000 rw-p 0002c000 ca:02 1312685                            /usr/local/bin/icecc-scheduler (deleted)
0062d000-0064e000 rw-p 00000000 00:00 0                                  [heap]
0064e000-00a6c000 rw-p 00000000 00:00 0                                  [heap]
7fe206409000-7fe206a6b000 rw-p 00000000 00:00 0 
7fe206a6b000-7fe206a6e000 r-xp 00000000 ca:02 590982                     /lib64/libSegFault.so
7fe206a6e000-7fe206c6e000 ---p 00003000 ca:02 590982                     /lib64/libSegFault.so
7fe206c6e000-7fe206c6f000 r--p 00003000 ca:02 590982                     /lib64/libSegFault.so
7fe206c6f000-7fe206c70000 rw-p 00004000 ca:02 590982                     /lib64/libSegFault.so
7fe206c70000-7fe206c78000 r-xp 00000000 ca:02 591015                     /lib64/librt-2.11.3.so
7fe206c78000-7fe206e77000 ---p 00008000 ca:02 591015                     /lib64/librt-2.11.3.so
7fe206e77000-7fe206e78000 r--p 00007000 ca:02 591015                     /lib64/librt-2.11.3.so
7fe206e78000-7fe206e79000 rw-p 00008000 ca:02 591015                     /lib64/librt-2.11.3.so
7fe206e79000-7fe206e90000 r-xp 00000000 ca:02 591011                     /lib64/libpthread-2.11.3.so
7fe206e90000-7fe207090000 ---p 00017000 ca:02 591011                     /lib64/libpthread-2.11.3.so
7fe207090000-7fe207091000 r--p 00017000 ca:02 591011                     /lib64/libpthread-2.11.3.so
7fe207091000-7fe207092000 rw-p 00018000 ca:02 591011                     /lib64/libpthread-2.11.3.so
7fe207092000-7fe207096000 rw-p 00000000 00:00 0 
7fe207096000-7fe207204000 r-xp 00000000 ca:02 590985                     /lib64/libc-2.11.3.so
7fe207204000-7fe207403000 ---p 0016e000 ca:02 590985                     /lib64/libc-2.11.3.so
7fe207403000-7fe207407000 r--p 0016d000 ca:02 590985                     /lib64/libc-2.11.3.so
7fe207407000-7fe207408000 rw-p 00171000 ca:02 590985                     /lib64/libc-2.11.3.so
7fe207408000-7fe20740d000 rw-p 00000000 00:00 0 
7fe20740d000-7fe207422000 r-xp 00000000 ca:02 591104                     /lib64/libgcc_s.so.1
7fe207422000-7fe207621000 ---p 00015000 ca:02 591104                     /lib64/libgcc_s.so.1
7fe207621000-7fe207622000 r--p 00014000 ca:02 591104                     /lib64/libgcc_s.so.1
7fe207622000-7fe207623000 rw-p 00015000 ca:02 591104                     /lib64/libgcc_s.so.1
7fe207623000-7fe20767e000 r-xp 00000000 ca:02 590993                     /lib64/libm-2.11.3.so
7fe20767e000-7fe20787d000 ---p 0005b000 ca:02 590993                     /lib64/libm-2.11.3.so
7fe20787d000-7fe20787e000 r--p 0005a000 ca:02 590993                     /lib64/libm-2.11.3.so
7fe20787e000-7fe20789c000 rw-p 0005b000 ca:02 590993                     /lib64/libm-2.11.3.so
7fe20789c000-7fe207984000 r-xp 00000000 ca:02 1151125                    /usr/lib64/libstdc++.so.6.0.17
7fe207984000-7fe207b83000 ---p 000e8000 ca:02 1151125                    /usr/lib64/libstdc++.so.6.0.17
7fe207b83000-7fe207b8b000 r--p 000e7000 ca:02 1151125                    /usr/lib64/libstdc++.so.6.0.17
7fe207b8b000-7fe207b8d000 rw-p 000ef000 ca:02 1151125                    /usr/lib64/libstdc++.so.6.0.17
7fe207b8d000-7fe207ba2000 rw-p 00000000 00:00 0 
7fe207ba2000-7fe207ba4000 r-xp 00000000 ca:02 590991                     /lib64/libdl-2.11.3.so
7fe207ba4000-7fe207da4000 ---p 00002000 ca:02 590991                     /lib64/libdl-2.11.3.so
7fe207da4000-7fe207da5000 r--p 00002000 ca:02 590991                     /lib64/libdl-2.11.3.so
7fe207da5000-7fe207da6000 rw-p 00003000 ca:02 590991                     /lib64/libdl-2.11.3.so
7fe207da6000-7fe207daa000 r-xp 00000000 ca:02 1331024                    /usr/local/lib/libcap-ng.so.0.0.0
7fe207daa000-7fe207fa9000 ---p 00004000 ca:02 1331024                    /usr/local/lib/libcap-ng.so.0.0.0
7fe207fa9000-7fe207faa000 r--p 00003000 ca:02 1331024                    /usr/local/lib/libcap-ng.so.0.0.0
7fe207faa000-7fe207fab000 rw-p 00004000 ca:02 1331024                    /usr/local/lib/libcap-ng.so.0.0.0
7fe207fab000-7fe207fb0000 r-xp 00000000 ca:02 591265                     /lib64/libachk.so
7fe207fb0000-7fe2081af000 ---p 00005000 ca:02 591265                     /lib64/libachk.so
7fe2081af000-7fe2081b0000 r--p 00004000 ca:02 591265                     /lib64/libachk.so
7fe2081b0000-7fe2081b1000 rw-p 00005000 ca:02 591265                     /lib64/libachk.so
7fe2081b1000-7fe2081d0000 r-xp 00000000 ca:02 590978                     /lib64/ld-2.11.3.so
7fe208391000-7fe208398000 rw-p 00000000 00:00 0 
7fe208398000-7fe2083cd000 r--s 00000000 ca:02 1043286                    /var/run/nscd/passwd
7fe2083cd000-7fe2083cf000 rw-p 00000000 00:00 0 
7fe2083cf000-7fe2083d0000 r--p 0001e000 ca:02 590978                     /lib64/ld-2.11.3.so
7fe2083d0000-7fe2083d1000 rw-p 0001f000 ca:02 590978                     /lib64/ld-2.11.3.so
7fe2083d1000-7fe2083d2000 rw-p 00000000 00:00 0 
7fff4b46a000-7fff4b48b000 rw-p 00000000 00:00 0                          [stack]
7fff4b5b4000-7fff4b5b5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by HenryMiller1** [comment]
Unfortunately that dump is not helpful - there are no symbols to indicate where we were in the code or any other information on how to reproduce there or where to look in the code.

**Comment by llunak** [comment]
As said, this is useless. If you still have this problem, you'll need to provide the crash info from a build with debug info.
