### ISSUE TITLE
Exception 15, 17 and 19 many times a day - need more information about the exceptions

### ISSUE THREAD

**Issue by gwagner681105** [icecc/icecream#307]
We have a strange phenomenon. We have from time to time a high occurence of the exception 15, 17 and 19 with shifted time in the client log, started from Jenkins:

2017-11-01 14:30:07 ICECC[32899] 12:40:27: write of source chunk to host 172.20.2.46
2017-11-01 14:30:07 ICECC[32899] 12:40:27: failed  Resource temporarily unavailable
2017-11-01 14:30:07 ICECC[32899] 12:40:27: got exception 15 (172.20.2.46) 

2017-11-01 09:57:15 ICECC[24862] 16:05:51: got exception 19 (172.20.2.46) 

Jenkins report the correct time (first time in the line).

We are using Iatest version of icecream (installed 1 week ago) for the scheduler as well as for the deamon

I don't find anything in the log neither on the scheduler nor on the daemon.

What does the exception number actually stands for?  Signal number? System Error? 
Is there a table, which explains the exception number?
That my be helps to find the reason

**Comment by HenryMiller1** [comment]
The latest version of icecream doesn't give errors like that anymore, there is more information in the error message. What version are you really running? Note that most distribution packages have not caught up with our latest release (released in August), you might need to install manually, or bug your distribution for upgraded packages.

That isn't to say that the above errors don't happen anymore, they do. We give more information though, which we hope will be helpful in figuring out why: right now we are stuck.

**Comment by gwagner681105** [comment]
Hi Henry

 

Thank you for your fast reply. I downloaded the master from the git repository (25.10) and let it build on my machine.

Afterwards I replaced the scheduler and the daemon on the machine which had some issues, but kept the client (icecc) in place

 

I did the installation by copy the build images to the target machine.

 

What I also can do is to replace the client to see ig this will bring a more stable status

 

Any other suggestion from your side is any time very welcome ;-)

 

Regards Günther

 

Günther Wagner
Mobile: 078 781 08 99
Kontakt-Email: gwagner68@gmx.ch

 
 

Gesendet: Mittwoch, 01. November 2017 um 17:21 Uhr
Von: "Henry Miller" <notifications@github.com>
An: icecc/icecream <icecream@noreply.github.com>
Cc: gwagner681105 <gwagner68@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [icecc/icecream] Exception 15, 17 and 19 many times a day - need more information about the exceptions (#307)


The latest version of icecream doesn't give errors like that anymore, there is more information in the error message. What version are you really running? Note that most distribution packages have not caught up with our latest release (released in August), you might need to install manually, or bug your distribution for upgraded packages.

That isn't to say that the above errors don't happen anymore, they do. We give more information though, which we hope will be helpful in figuring out why: right now we are stuck.

**Comment by gwagner681105** [comment]
We installed the latest version of icecream 1.1 on all our machine, which are part of our icecream ring.
I see now a different format of the errormessage, but the behavior is still the same.

We were using icecream within our Jenkins node and we see always the same error.

2017-11-13 21:44:33 ICECC[15059] 13:14:02: got exception Error 14 - error reading message from remote (172.20.2.65) 

The error appears always with the icecream time (second time in the line above). Always exactly with the same time, no matter if the server 172.20.2.65 has daemon running or not. And it always appears with the exact same time. 

Do you have an explanation for that? We are really dependent on Icecream

**Comment by HenryMiller1** [comment]
I would have to double check the code, but I think that we save
startup time for various calculations so that is probably what the
second time is.
--
  Henry Miller
  hank@millerfarm.com



On Tue, Nov 14, 2017, at 05:19 AM, gwagner681105 wrote:
> We installed the latest version of icecream 1.1 on all our machine,
> which are part of our icecream ring.>  I see now a different format of the errormessage, but the behavior is
>  still the same.> We were using icecream within our Jenkins node and we see always the
> same error.> 2017-11-13 21:44:33 ICECC[15059] 13:14:02: got exception Error 14 -
> error reading message from remote (172.20.2.65)> The error appears always with the icecream time (second time in the
> line above). Always exactly with the same time, no matter if the
> server 172.20.2.65 has daemon running or not. And it always appears
> with the exact same time.> Do you have an explanation for that? We are really dependent on
> Icecream> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/icecc/icecream/issues/307#issuecomment-344228002

**Comment by gwagner681105** [comment]
So why do we have such a big time difference between Jenkins Server time (first time in the line) and the icecream time (second time in the line)? Could it be that this is not a real exception and rather a bug?

**Comment by gwagner681105** [comment]
After spending some time on the analyses, we found out ccache is the guilty guy. I also stores the icecream exception output in ccache. 
I have seen, that recently a patch has been implemented for exactly that reason. 

--> https://github.com/icecc/icecream/issues/112

When will be a newer version out?

**Comment by llunak** [comment]
I'd like to implement few more things and then make a release, so if nobody beats me to it, about 2 months I'd say. But you can simply patch your build or even use the current git version, I expect it should work just as fine as whatever "stable" release you use.

Does that mean that this issue can be closed?

**Comment by gwagner681105** [comment]
Ok, will RedHat distrubtion updated as well? 
Yes Issue can be closed

 

Regards Günther
 

Günther Wagner
Mobile: 076 504 08 99
Kontakt-Email: gwagner68@gmx.ch

 
 

Gesendet: Sonntag, 07. Januar 2018 um 13:39 Uhr
Von: "Luboš Luňák" <notifications@github.com>
An: icecc/icecream <icecream@noreply.github.com>
Cc: gwagner681105 <gwagner68@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [icecc/icecream] Exception 15, 17 and 19 many times a day - need more information about the exceptions (#307)


I'd like to implement few more things and then make a release, so if nobody beats me to it, about 2 months I'd say. But you can simply patch your build or even use the current git version, I expect it should work just as fine as whatever "stable" release you use.

Does that mean that this issue can be closed?

**Comment by llunak** [comment]
Ok, closing.

I have no idea what the RedHat process is, I'd expect they'll update their package somewhen.
