### ISSUE TITLE
Can't install on FreeBSD 11.0

### ISSUE THREAD

**Issue by LeeBrown** [icecc/icecream#313]
./configure --prefix=/usr/local
checking for lzo1x_1_compress in -llzo2... no

This is indeed installed, a quick test program confirms:
#include "lzo/lzo2a.h"

int main() {
  lzo_bytep src,dst;
  lzo_uint src_len;
  lzo_uintp dst_len;
  lzo_voidp wrkmem;

  lzo1x_1_compress(src,src_len,dst,dst_len,wrkmem );
}
cc -I/usr/local/include /tmp/t.c -L/usr/local/lib -llzo2

generates an executable.

**Comment by HenryMiller1** [comment]
That is one of several problems building on freebsd.

#287 (using cmake)  gets farther into the build, but then fails on a linuxism in something that I can't recall now. 

This is something that I want to fix, but am unlikely to find the time for. To fix it right what we really need is a ci system that can ensure that it isn't broken again. I'm not aware of any.

**Comment by llunak** [comment]
This needs somebody who'd be able to actually test it out in practice, especially given that you do not provide any information besides saying that it is broken. The configure script creates config.log file, where you can find out what went wrong with the test. So you can fix this yourself and create a pull request.

**Comment by LeeBrown** [comment]
@llunak thanks for the hint.  I can now get farther with:
./configure --prefix=/usr/local CXXFLAGS="-I/usr/include -I/usr/local/include" LDFLAGS="-L/usr/lib -L/usr/local/lib" --without-man

This created an almost workable make infrastructure.
1. It fails the link stage because it's trying to link a "dl" library, which doesn't exist on FreeBSD.  The dlopen, etc routines are part of the standard library.  After hacking services/Makefile to remove that, I was able to generate the binaries.
2. It fails the documentation generation stage.  For some reason no parameters are passed to the conversion program.  I tried manually calling the conversion program, but the resulting man pages were less than satisfactory, so I gave up on that for now.

Asides from that I can install the binaries now.

Any help on how to prevent the dl library coming in without hacking the makefile?

**Comment by llunak** [comment]
Something like this?

[configure.ac.patch.txt](https://github.com/icecc/icecream/files/1523645/configure.ac.patch.txt)

**Comment by LeeBrown** [comment]
@llunak that's perfect, thanks.  Without manpages I can now cleanly build the binaries.

I got farther with the docs using gmake (docs/Makefile is not bsd make compatible), but the conversion utility segfaults on man-icecream.7.xml  I was able to manually generate the manpages for the rest, so maybe docbook-to-man is the wrong utility to use in this case.

**Comment by LeeBrown** [comment]
OK, that's all sorted.  I'm in the process of writing a port for this, should have it out within a week.

**Comment by llunak** [comment]
Please don't forget to create a pull request with your fixes.
