### ISSUE TITLE
what does "ICECC_NICE_LEVEL: Nice level of running compilers"  mean?

### ISSUE THREAD

**Issue by honwsn** [icecc/icecream#314]
what does "ICECC_NICE_LEVEL: Nice level of running compilers"  mean?

has optimize space in this parameter?

**Comment by llunak** [comment]
There's no ICECC_NICE_LEVEL in stock icecream, but presumably that is https://en.wikipedia.org/wiki/Nice_(Unix) .

And please note that this is not a support forum. Use http://groups.google.com/group/icecream-users/ .
