### ISSUE TITLE
Compile job's target platform does always refer to the host platform

### ISSUE THREAD

**Issue by stefbo** [icecc/icecream#318]
Hi,

this is more like a question instead of an issue. I am trying to set up icecream for cross-compiling from x86_64 to arm for an embedding device and in practice it seems to work, but I do not understand why. So I started to dive into the source and looked at the role of the environments and compile job's target platform. As mentioned in the documentation, it is possible to add environments for different target platforms using ICECC_VERSION. However, if I look at the compile jobs and how they determine the target platform (which in my case is arm), it seems there is no way to manipulate it, because it is always queried from `uname(...)`. Do you have a hint for me? Maybe its an leftover from distcc and I am just thinking the wrong way round.

Thank in advance, Stefan

**Comment by llunak** [comment]
The cross-compiling support works the other way around. You do not cross-compile from your platform to some other one, you have remote nodes on other platforms cross-compile for your platform. That is why the platform always refers to the local platform.

But if you want to cross-compile to another platform, then cross-compiling really works with Icecream basically the same as it does without it - you invoke the relevant compiler and it generates code for the other platform. So if you achieve that locally using a flag (as is done with Clang), then the flag should also get used remotely, if you achieve that using a specific GCC binary that generates code for that other platform, just package that binary and use ICECC_VERSION.
