### ISSUE TITLE
Authentication mechanism

### ISSUE THREAD

**Issue by rmatev** [icecc/icecream#344]
At my workplace authentication is a prerequisite if we were to deploy some shared service like icecream. Distcc has a GSS-API authentication mechanism (see the man pages, and [here](https://github.com/distcc/distcc/blob/master/doc/protocol-gssapi.txt)) , but I couldn't find anything for icecream.

Any thoughts on the feasibility of adding authentication? I could try to evaluate this myself, but given that the icecream communication protocol is more involved and I cant't find a description of it, I don't really know where to start.

**Comment by mostynb** [comment]
I don't know icecc's network layer well, but perhaps you could start by looking at where LoginMsg's are created/sent in the daemon and received/handled in the scheduler?  It might be possible to insert an optional authentication step before a login is allowed.

**Comment by HenryMiller1** [comment]
icecream intentionally does not handle security.  We assume your firewall blocks access from untrusted remotes.

While this could be added, security is more than just authentication. If you really need something on your network that also implies you are going to harden the rest of the protocol. It does no good to have authentication if there are other bugs that mean an attacker can start running his code before authentication starts.

I would suggest switching to std::network (new in C++17) would be the first step, as an exercise in hardening the communication. I'm not sure how the other maintainers feel about requiring c++17.

That said, I'm not against it so long as if I don't have it enabled it doesn't slow my builds down (this should be an easy bar)

**Comment by ossilator** [comment]
i think the most pragmatic approach would be externalizing the problem: set up a vpn between the participating hosts.

**Comment by mostynb** [comment]
> i think the most pragmatic approach would be externalizing the problem: set up a vpn between the participating hosts.

I think openvpn supports a no-encryption mode (with lower CPU usage), if you only need authentication.

**Comment by llunak** [comment]
As said above, Icecream assumes it runs in a trusted network and so considers this to be an external problem. If you do not run in a trusted network, use external tools such as firewall, VPN etc. to ensure what you want.
