### ISSUE TITLE
Ctrl-C doesn't work on iceccd

### ISSUE THREAD

**Issue by Timmmm** [icecc/icecream#372]
This is on OSX. If I run `sudo iceccd -s myscheduler` it runs ok (complains about no `icecc` user but eh) but I can't kill it with Ctrl-C.

It's kind of annoying when you're trying to set things up.

Edit: Also Ubuntu.

**Comment by llunak** [comment]
Ctrl+C certainly does work with iceccd. If it doesn't work with sudo, then it's sudo not forwarding the signal properly (possibly because of the uid change).

**Comment by themightyoarfish** [comment]
Any advice how to make this work?
