### ISSUE TITLE
"No such file or directory" when running iceccd on OSX

### ISSUE THREAD

**Issue by Timmmm** [icecc/icecream#374]
On OSX 10.12 when I run `sudo /usr/local/Cellar/icecream/1.1/sbin/iceccd -s myscheduler` it prints:

    Error: no icecc user on system. Falling back to nobody. No such file or directory

Fair enough about the icecc user, although that error message is useless (does it matter or can I ignore it? why would I bother creating an icecc user if nobody is fine?).

I have no idea what the "No such file or directory" error is though or if it matters.

**Comment by llunak** [comment]
That is the error message from the call that failed to find the user. I can tweak the error message a bit, but that's about it.

And it doesn't say anywhere that using nobody is fine. Fallbacks are what gets used if the normal solution doesn't work, but that doesn't make them fine.
