### ISSUE TITLE
iceccd doesn't warn you when you don't run it as root.

### ISSUE THREAD

**Issue by Timmmm** [icecc/icecream#375]
If you run `iceccd -s myscheduler` or whatever, *without `sudo`* it seems to work, but in `icemon` it will show the host in italics, with max jobs 0 and "no remote?" as "yes".

Just running with `sudo` fixes this, but surely there should be some kind of message printed, like "Warning: compilation disabled - iceccd must be run as root" or whatever.

**Comment by llunak** [comment]
$ ./iceccd
[20185] 12:30:44: Cannot use chroot, no remote jobs accepted.
