### ISSUE TITLE
Should we add some unit tests?

### ISSUE THREAD

**Issue by mostynb** [icecc/icecream#379]
I think it would be good if the test suite included some unit tests.  Would this be welcome?  My preference would be to use gtest.

**Comment by llunak** [comment]
There actually already is one unit test, tests/args.cpp, it's just practically hidden by the scripted tests, those should get separated into different directories. But otherwise, if you think there's something to test, sure, feel free to add tests.

**Comment by llunak** [comment]
The question has been answered, and this is way too generic to do something more about this. If there's a specific test to be added, it just should be added, but not much point in this generic issue.
