### ISSUE TITLE
Error 14 for large compiler output (Around 1 Megabyte)

### ISSUE THREAD

**Issue by MaxSagebaum** [icecc/icecream#382]
We recognized that build jobs fail on remote machines. The issue we identified is just the size of the generated output from the compiler. Around a file size of 1 Megabyte the remote job fails with the error 14. We created a small test program, that produces large amounts of warnings. The test program could be used to recreate the issue.

The warning is:
> test_icecc.cpp: In instantiation of 'void func(int) [with int dim = 0]':
> test_icecc.cpp:6011:1:   required from here
> test_icecc.cpp:4:33: warning: unused parameter 'arg' [-Wunused-parameter]

This warning is repeated 6000 times until the file size is reached.

The full log for the ungraceful exit is:
> ICECC[28001] 16:06:34: connected to /var/run/icecc/iceccd.socket
> ICECC[28001] 16:06:34: env: x86_64 '/home/msagebaum/Applications/42b4b3fed6af9434d65174165c0f4e83.tar.gz'
> ICECC[28001] 16:06:34: test_icecc.cpp compiled 1 times on x86_64
> ICECC[28001] 16:06:34: Have to use host 131.246.20.79:10245 - Job ID: 6869 - env: x86_64 - has env: true - match j: 0
> ICECC[28001] 16:06:34: connected to 131.246.20.79
> ICECC[28001] 16:06:34: <send compile_file>
> ICECC[28001] 16:06:34: </send compile_file: 0ms>
> ICECC[28001] 16:06:34: <write_server_cpp from cpp>
> ICECC[28001] 16:06:34: sent 24714 bytes (29%)
> ICECC[28001] 16:06:34: </write_server_cpp from cpp: 32ms>
> ICECC[28001] 16:06:34: <wait for cpp>
> ICECC[28001] 16:06:34: </wait for cpp: 0ms>
> ICECC[28001] 16:06:34: <wait for cs>
> ICECC[28001] 16:06:36: !read_a_bit 2
> ICECC[28001] 16:06:36: !wait_for_msg()
> ICECC[28001] 16:06:36: </wait for cs: 1198ms>
> ICECC[28001] 16:06:36: timeout <= 0
> ICECC[28001] 16:06:36: no message type
> ICECC[28001] 16:06:36: got exception Error 14 - error reading message from remote (131.246.20.79)

For the working version the log is:
> ICECC[28079] 16:09:04: connected to /var/run/icecc/iceccd.socket
> ICECC[28079] 16:09:04: env: x86_64 '/home/msagebaum/Applications/42b4b3fed6af9434d65174165c0f4e83.tar.gz'
> ICECC[28079] 16:09:04: test_icecc.cpp compiled 1 times on x86_64
> ICECC[28079] 16:09:04: Have to use host 131.246.20.79:10245 - Job ID: 6870 - env: x86_64 - has env: true - match j: 0
> ICECC[28079] 16:09:04: connected to 131.246.20.79
> ICECC[28079] 16:09:04: <send compile_file>
> ICECC[28079] 16:09:04: </send compile_file: 0ms>
> ICECC[28079] 16:09:04: <write_server_cpp from cpp>
> ICECC[28079] 16:09:04: sent 20691 bytes (29%)
> ICECC[28079] 16:09:04: </write_server_cpp from cpp: 8ms>
> ICECC[28079] 16:09:04: <wait for cpp>
> ICECC[28079] 16:09:04: </wait for cpp: 0ms>
> ICECC[28079] 16:09:04: <wait for cs>
> ICECC[28079] 16:09:05: </wait for cs: 1016ms>

> ICECC[28079] 16:09:05: got 724324 bytes (21%)

We compile the files with:
> g++ -O0 -g -Wall -Wextra -pedantic -std=c++11 test_icecc.cpp -c -o test_icecc.o -fno-diagnostics-show-caret

Had to rename the source files to txt
[test_icecc_5000.txt](https://github.com/icecc/icecream/files/1767618/test_icecc_5000.txt)
[test_icecc_6000.txt](https://github.com/icecc/icecream/files/1767619/test_icecc_6000.txt)

We hope this bugreport is helpful.

**Comment by llunak** [comment]
I've added some log messages to make it easier to identify that the problem is a too large block of data to send, but I think I'm not going to do anything more. If such a remote compile fails, it should be done again locally, so in practice this shouldn't matter except for the extra time, and that's not a big problem in the rare case it happens. And if it's not a rare case that you have more than 1MiB of error messages, then the obvious solution is "don't do it".

**Comment by MaxSagebaum** [comment]
Ok, under the scenario you have described I would have never complained. The problem is, that the file does not get recompiled locally. The process exists with error 14.

Is there a workaround for this behaviour?

**Comment by ossilator** [comment]
if that latter problem persists, i would recommend opening a new gh issue.

**Comment by MaxSagebaum** [comment]
I think that was because of an older version. I have less problems now, but it would be nice if the maximum message size could be configurable. This is just warning output instead of error output.
