### ISSUE TITLE
extrafiles' paths are changed by icecc-create-env but not by the icecc client

### ISSUE THREAD

**Issue by mostynb** [icecc/icecream#384]
icecc-create-env's add_file function replaces the compiler prefix with usr/ in the destination file inside the tarball, but the icecc client doesn't mangle paths to extrafiles in the same way.  This then prevents the usage of clang plugins that happen to be stored inside clang's own prefix (unless the prefix is /usr), since they live inside clang's install dir, but clang does not look for plugins inside that prefix automatically.

For example, chromium has a clang toolchain which is unpacked inside this dir inside the checkout:
third_party/llvm-build/Release+Asserts/bin
And they have a custom clang plugin inside the same compiler prefix:
third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so

If I run the following command:
icecc-create-env third_party/llvm-build/Release+Asserts/bin/clang --addfile $(realpath third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so)
then the resulting tarball has usr/lib/libFindBadConstructs.so inside the tarball.

Then if I run:
icecc $(realpath third_party/llvm-build/Release+Asserts/bin/clang) -Xclang -load -Xclang $(realpath third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so)
then the the path to the plugin is not similarly transformed on the remote command line, clang fails to find the plugin and errors out.

Note: the chromium build uses a relative path to the clang plugin, which is also broken atm due to bugs in get_absfilename().

Should icecc-create-env be modified to avoid mangling paths to extrafiles?  Or should we apply the same transformation to clang plugin paths in the icecc client?  I suppose the latter is more efficient, for example if two developers with the same chromium checkout in different directories would produce an icecc tarball with the same hash.

**Comment by honwsn** [comment]
in chrome icecc compile  , "clang_use_chrome_plugins=false" will cause no repose from remote compile node , icecc did not support clang plugins for remote compile node.  Do not rely on it.

**Comment by llunak** [comment]
Done.
