### ISSUE TITLE
ICECC falls back to local compilation when g++ executable does not end with "++"

### ISSUE THREAD

**Issue by mbitsnbites** [icecc/icecream#390]
For instance, these will all trigger distributed compilations:

```bash
$ icecc c++ [...]
$ icecc g++ [...]
$ /usr/bin/icecc /usr/bin/g++ [...]
```

...while these will trigger local compilations:

```bash
$ icecc g++-5 [...]
$ icecc /usr/bin/g++-5 [...]
$ /usr/bin/icecc /usr/bin/g++-5 [...]
```

**Comment by mbitsnbites** [comment]
I made a dirty workaround in [BuildCache](https://github.com/mbitsnbites/buildcache) to support ICECC + g++ on Ubuntu 16.04: https://github.com/mbitsnbites/buildcache/commit/4b3bda87a03126739340b880b07b09a61aa6e197

**Comment by llunak** [comment]
Already handled by commit 26e4731e15e905ee8dbcdad1f5039c734eff0523 .
