### ISSUE TITLE
Use scheduler for local fallback builds, such as caret workaround

### ISSUE THREAD

**Issue by RedBeard0531** [icecc/icecream#394]
This is related to #190. I think the biggest issue isn't the double compile (remote, then local) it is that the local fallback uses the single-threaded lockfile mechanism rather than being scheduled like any other local job. This means that if you have 10 files with warnings, even if you could run them all in parallel, they are compiled sequentially one at a time.

This should probably apply to any local fallback, such as when the remote node fails.

**Comment by llunak** [comment]
Done.
