### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [icecc/icecream#40]
I guess that the function "[log_info](https://github.com/icecc/icecream/blob/e2afd07d16c067d0989254deb2acf228bf045cb9/client/main.cpp#L121)" is not [async-signal-safe](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).

The data type of the variable "local" should be "[sig_atomic_t](https://www.securecoding.cert.org/confluence/display/seccode/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers)" instead of "bool".

**Comment by llunak** [comment]
Volatile bool should be atomic in practice too, and I'm not aware of any actual real-world problem ever reported because of this, so apparently this is just a theoretical problem. Closing.
