### ISSUE TITLE
compiler_path_lookup_helper returns last compiler path in $PATH 

### ISSUE THREAD

**Issue by wdelgenio** [icecc/icecream#405]
I was having problems getting the `icecc --build-native` to find my gcc binary.  It was always using `/usr/bin/gcc` instead of of `/somecustomdir/gcc`.  My `PATH` variable is something like `/somecustomdir:...:/usr/bin:...`
Turns out that `compiler_path_lookup_helper` in local.cpp will iterate through each path in `PATH` environment variable and if it finds a gcc binary at that path, updates the `best_match` string, which is returned at the end of the function.  This results in the last gcc binary found to be the one returned, which is backwards from how the `PATH` works.  If i type `which gcc` in my prompt, I get `/somecustomdir/gcc`.
Has anyone else run into this problem?

**Comment by llunak** [comment]
The function updates best_match only if it's empty, so what you describe is not a cause for your problem. And icecc --create-native by default uses /usr/bin/gcc, so if you want a different one, you need to specify it explicitly.
