### ISSUE TITLE
Custom build to the latest gcc

### ISSUE THREAD

**Issue by abhi1010** [icecc/icecream#409]
Hi,
I am wondering whether it is possible to do my own build of `icecream`, which caters to the latest `gcc8.3`, for example?
We currently create our own build of GCC enabling various flags. If we were to successfully re-use `icrecream`, it would require us to replace gcc binary with `icecream`.

Any clues on how to do this?

**Comment by llunak** [comment]
Icecream is not a gcc replacement, so there's no need to do anything like that. All that it essentially does it that it wraps calls to /usr/bin/gcc|g++|whatever , so what's at most needed is support for new flags and features of the latest gcc, if necessary. If you have anything like that, you can simply submit them and also use them in your local icecream build.

**Comment by abhi1010** [comment]
Thanks for the update. I was looking for how I can wrap around a different location - something other than `/usr/bin/gcc` for e.g. I tried setting variables during `configure` as follows (for local installation):

```
configure CXX=/opt/gcc82/bin/g++ CC=/opt/gcc82/bin/gcc --prefix=dist LT_SYS_LIBRARY_PATH=/opt/gcc82/
```

Our binaries exist in `/opt/gcc82/`. 

When I run `make && make install`, the `dist/libexec/icecc/bin/g++ --version` still gives me the following:
`g++ (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)`.

This means icecc is still picking up gcc7.3.1 from /usr folder. 

What would it take for it to pick up gcc8.2?

**Comment by llunak** [comment]
The wrappers pick up whatever is next in $PATH. So you should get the same from the wrapper as you get from plain 'g++ --version'.
