### ISSUE TITLE
__COUNTER__ expanded inside directive with -fdirectives-only

### ISSUE THREAD

**Issue by lynxeye-dev** [icecc/icecream#414]
Since the switch to use -fdirectives-only on GCC I'm no longer able to build some packages. One such example is GNU M4, which fails with the error message in the title. This seems to be a corner case where -fdirectives-only can not be used [1]. As this error happens while running the local CPP half for a remote build it is treated as a fatal error, failing the build.

It seems there is no other way to fix this than to detect this error message from the local CPP and fall back to a local build. As this requires more changes to the icecc client than I currently have time to do, I'm documenting the issue here. Maybe someone other can help to fix this.

https://gcc.gnu.org/ml/gcc-patches/2007-06/txt00139.txt

**Comment by stayprivate** [comment]
googlebenchmark also uses __COUNTER__ and creates issue. However it's usage is somewhat optional hence a small change in googlebenchmark header file will work around the issue.

**Comment by LeSpocky** [comment]
FWIW, here's the output of a failing build of m4 1.4.18 with DistroKit and [ptxdist](https://www.ptxdist.org/) and [ICECC 1.2.0 from Debian 10](https://packages.debian.org/buster/icecc):

https://hastebin.com/lirinilaqo.js

@rohieb could reproduce this.

**Comment by rohieb** [comment]
Just for googlability, I also got the same error with libtasn, gettext, glib and gdbserver, which seem to use the same `verify.h` with the `__COUNTER__` definition like m4.

**Comment by HenryMiller1** [comment]
Merged proposed fix
