### ISSUE TITLE
Remote compile with clang looks broken

### ISSUE THREAD

**Issue by pprkut** [icecc/icecream#417]
I'm running a git version of icecream (2247021d74752124289c0e7a8bd7b0a17a527963) and when compiling something with clang (6.0.1) I see log lines like this appearing:

```
sh: -dumpmachine: command not found
ICECC[12030] 2018-09-01 12:43:29: failed to read default clang host platform, building locally
```

This was introduced with 1f883606b354dd5fb8b95c8b889ed37aad4e8fbb (not actually bisected, but that's the only code reference to -dumpmachine).
Looks like in my case `job.compilerPathname()` returns an empty string.

Running it manually works though:
```
hwiesinger@carbon:~$ clang -dumpmachine
x86_64-unknown-linux-gnu
```

**Comment by llunak** [comment]
Fixed by the above commit.
