### ISSUE TITLE
Unclear how to compile on multiple architectures

### ISSUE THREAD

**Issue by brendanlong** [icecc/icecream#42]
The instructions for heterogenous environments only work if they're all running the same architecture. In my case, I want to other machines in my cluster to compile for me, even if they're on different architectures.

For example, I'm running using an x86_64 distro for development, but the most powerful machine in my cluster runs i686. I ran icecc --build-native on the 32-bit machine, and then use it on my 64-bit machine using:

```
export ICECC_VERSION=/etc/icecc/native.tar.gz,i686:/etc/icecc/i686.tar.gz
```

This works fine on WebKit, but not with GStreamer. I'm guessing the difference is that WebKit compiles with -m64 and doesn't use autotools.

I'm guessing I'm not doing this right, but there's very little documentation available. How am I supposed to tell 32-bit machines to cross compile?

**Comment by llunak** [comment]
This and #373  are duplicate, let's keep only #373 and close this one.
