### ISSUE TITLE
Reordering of compiler arguments still causes wrong debug information level

### ISSUE THREAD

**Issue by EnricoB1** [icecc/icecream#435]
icecream is reordering some arguments, which causes issues when trying to build with reduced debug information.

Tested with gcc 5.2. Building with -gsplit-dwarf and reduced debug information -g1:

gcc -c foo.cpp -o foo.o -gsplit-dwarf -g1

but icecream will change this to something like:

gcc -c foo.cpp -o foo.o -g1 -gsplit-dwarf

The result is a binary with full debug info.
After closing of issue #424 this only happens for remote compiles, but not for local compiles anymore.

**Comment by llunak** [comment]
Should work now.
