### ISSUE TITLE
-fsanitize-blacklist=file -- error: no such file or directory: 'file'

### ISSUE THREAD

**Issue by NickRussell0** [icecc/icecream#437]
After trying several file locations to pass in and copying and pasting the file everywhere, I'm convinced there is a bug somehow, because a2f0d75 looks like it should resolve this. I only blame icecream because stopping the iceccd daemon stops the error.

I haven't studied the entire repo to get a good heading on where to look, but maybe it has to do with being on a vpn, local machine distribution to containers that don't have the file, or anything else about my setup.

**Comment by llunak** [comment]
That commit you reference also adds a test, which works fine, so there's no way to help you unless you provide details about your problem.

**Comment by hferreiro** [comment]
Try to use an absolute path, relative paths aren't working with icecream: https://github.com/icecc/icecream/issues/404.

**Comment by llunak** [comment]
No reply, possibly fixed by request #403 , closing. If the problem still persists, please provide the asked for information.
