### ISSUE TITLE
Problem detecting proper compiler ?

### ISSUE THREAD

**Issue by stayprivate** [icecc/icecream#442]
Hi 

Ubuntu 18, with  gcc8 added (but not set as default compiler). Our cmake are setup with toolchain file to use gcc-8 and g++-8.  I created the g++-8 and gcc-8 links in /usr/lib/icecc/bin. That works good for local build, but for remote node, the environment that gets copied is the default gcc (which is version 7). 

When a file gets compile on a remote node, get gazillion compile error, but what confuses me is they all reference header file in /usr/include/8/...   If I overwrite the tools in the environment directory of the node with the proper version all is good.

The local machine and remote nodes have the exact same version of ubuntu and gcc, as they are all clones of the same Virtual Machines.

I guess the solution is to create a custom environment? But it seems to me this should work out of the box and that I might be doing something no quite right.

Using latest version of icecream (1.2.90) build from git.

Regards,

Mario

**Comment by HenryMiller1** [comment]
It would be nice if that would work out of the box, but it doesn't. You
need to create a custom environment.
--
  Henry Miller
  hank@millerfarm.com



On Thu, Jan 3, 2019, at 8:55 AM, stayprivate wrote:
> Hi


> Ubuntu 18, with  gcc8 added (but not set as default compiler). Our
> cmake are setup with toolchain file to use gcc-8 and g++-8.  I created
> the g++-8 and gcc-8 links in /usr/lib/icecc/bin. That works good for
> local build, but for remote node, the environment that gets copied is
> the default gcc (which is version 7).> When a file gets compile on a remote node, get gazillion compile
> error, but what confuses me is they all reference header file in
> /usr/include/8/...   If I overwrite the tools in the environment
> directory of the node with the proper version all is good.> The local machine and remote nodes have the exact same version of
> ubuntu and gcc, as they are all clones of the same Virtual Machines.> I guess the solution is to create a custom environment? But it seems
> to me this should work out of the box and that I might be doing
> something no quite right.> Using latest version of icecream (1.2.90) build from git.


> Regards,


> Mario


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Links:

  1. https://github.com/icecc/icecream/issues/442

**Comment by stayprivate** [comment]
Thank you your answer.

icecc-create-env g++-8 did the trick.  

Cheers!

**Comment by llunak** [comment]
With the next release this will work automatically, https://github.com/icecc/icecream/commit/17e502444f94ecad59dfd69115f963887e30917c .
