### ISSUE TITLE
resolve_path in icecc-create-env is wrong

### ISSUE THREAD

**Issue by yshui** [icecc/icecream#445]
```sh
while test -L "$local_path"; do
    cd $(dirname $local_path)
    local_path=$(readlink $local_path)
done
```

Say, local_path is `/usr/bin/true`, which links to `../tmp/asdf/bin/true`, which is also a symlink.

```sh
test -L /usr/bin/true # true
cd /usr/bin
readlink /usr/bin/true # ../tmp/asdf/bin/true
local_path=../tmp/asdf/bin/true
test -L ../tmp/asdf/bin/true # true
cd ../tmp/asdf/bin
readlink ../tmp/asdf/bin/true # <-- Wrong path!
```

**Comment by yshui** [comment]
```diff
 while test -L "$local_path"; do
     cd $(dirname $local_path)
-    local_path=$(readlink $local_path)
+    local_path=$(readlink $(basename $local_path))
 done
```

Should do

**Comment by yshui** [comment]
Or, just use `readlink -f`

**Comment by ossilator** [comment]
yay, another duplicate for #404 - let's wait a few more years. ;)

**Comment by ossilator** [comment]
you're right, i got confused.
but let's say that there is a bit of an error pattern here. ^^

using `readlink -f` might be a bit too optimistic, as it's a gnu extension and macos doesn't have it.

your patch seems correct to me.

**Comment by llunak** [comment]
I've made the suggested change with basename, thank you.
