### ISSUE TITLE
get total threads

### ISSUE THREAD

**Issue by ohhmm** [icecc/icecream#449]
Is there an option to get current and total available threads from server through command line?

**Comment by HenryMiller1** [comment]
No option. You can get that information from icemon. (I think that you have to count manually) 

The information isn't really useful, it changes all the time as different jobs start and finish. 

-- 
 Henry Miller
 hank@millerfarm.com

**Comment by milianw** [comment]
you can also use the telnet api: https://github.com/milianw/shell-helpers/blob/master/icecream_is_available.sh

**Comment by llunak** [comment]
As said above. Either you have a static cluster that doesn't change its configuration, in which case just count it once and use that value. Or nodes appear and disappear in your cluster, in which case a value at a random time may be very quickly out of date.
