### ISSUE TITLE
iceccd run into busyloop state

### ISSUE THREAD

**Issue by dothan009** [icecc/icecream#453]
I build a distribute build cluster (5 server, 100 cores total) using icecream. Sometimes the iceccd run into busyloop state, and print huge log like this:

```
9999967 [63841] 2019-03-07 21:23:03: select(Error: Bad file descriptor)
9999968 [63841] 2019-03-07 21:23:03: Delaying reconnect.
```

Because of this cluster was used by many people, the build load may become very high (> 1000 job), I think this bug is related to the 1024 limit of the select syscall。When this bug occures, the build job will hang till I restart the iceccd service。

**Comment by dothan009** [comment]
My  icecc version is 1.2, OS  is centos 6.10

**Comment by llunak** [comment]
Should be fixed in git, thank you.
