### ISSUE TITLE
Compile issue on icecream - 1.2 in RHEL7 environment

### ISSUE THREAD

**Issue by Abinayasandhiya** [icecc/icecream#455]
Hi,

We tried to build icecream-1.2 on our RHEL7 server.
Please find below build steps which we are using from our end:

`./configure --prefix=/opt/icecream
make
make install`

Facing issue on "make install", find below issue log:

`nsgmls:I: maximum number of errors (200) reached; change with -E option
test -z "/opt/ice/share/man/man1" || /bin/mkdir -p "/opt/ice/share/man/man1"
 /usr/bin/install -c -m 644 ./icecc.1 ./iceccd.1 ./icecc-scheduler.1 ./icecc-create-env.1 '/opt/ice/share/man/man1'
/usr/bin/install: cannot stat `./icecc.1': No such file or directory
/usr/bin/install: cannot stat `./iceccd.1': No such file or directory
/usr/bin/install: cannot stat `./icecc-scheduler.1': No such file or directory
/usr/bin/install: cannot stat `./icecc-create-env.1': No such file or directory
make[2]: *** [install-man1] Error 1
make[2]: Leaving directory `/root/icecream-1.2/doc'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/root/icecream-1.2/doc'
make: *** [install-recursive] Error 1
`

Please find attachment for full error log.

[icecream_make_install_error.txt](https://github.com/icecc/icecream/files/3007649/icecream_make_install_error.txt)

Suggestion would be appreciated.

Thanks in Advance!

**Comment by ossilator** [comment]
there is a rather obvious issue with the docbook processing; the bug is that the build command doesn't abort with an error already. the underlying issue is rather cryptic, and i wouldn't be surprised if docbook2man simply returns zero despite the failure. check your docbook-xsl (?) installation.

**Comment by Abinayasandhiya** [comment]
Hi,

Already installed below docbook module since issue is persist.

`[root@praveena-test-new rpmbuild]$ rpm -qa | grep docbook
docbook5-style-xsl-1.75.2-4.el6.noarch
docbook-style-dsssl-1.79-10.el6.noarch
docbook-style-xsl-1.75.2-6.el6.noarch
docbook-dtds-1.0-51.el6.noarch
docbook-utils-0.6.14-25.el6.noarch
[root@praveena-test-new rpmbuild]$ yum info docbook-style-xsl-1.75.2-6.el6.noarch
Loaded plugins: product-id, search-disabled-repos, security
Installed Packages
Name        : docbook-style-xsl
Arch        : noarch
Version     : 1.75.2
Release     : 6.el6
Size        : 15 M
Repo        : installed
From repo   : rhel6-server
Summary     : Norman Walsh's XSL stylesheets for DocBook XML
URL         : http://docbook.sourceforge.net/projects/xsl/
License     : Copyright only
Description : These XSL stylesheets allow you to transform any DocBook XML document to
            : other formats, such as HTML, FO, and XHMTL.  They are highly customizable.

[root@praveena-test-new rpmbuild]$
`

Can we get some solution on this issue.

**Comment by llunak** [comment]
As said above, this is very likely a problem with your docbook2man installation. The error messages are about files that have nothing to do with Icecream, and the command apparently does not exit with an error despite failing.

On my system there are multiple packages providing some kind of docbook2man binary (docbook2x-man db2x_docbook2man docbook-to-man docbook2man.pl docbook2man), so try uninstalling this one and installing a different one.
