### ISSUE TITLE
Releases should contain automake generated files.

### ISSUE THREAD

**Issue by rubenvb** [icecc/icecream#457]
Currently one needs to install various GNU Autotools dependencies to compile icecream from source. It would be helpful to add the pre-generated files to the release tarballs as any other project using autotools does.

**Comment by HenryMiller1** [comment]
I agree it would be nice, I'm not sure how to do this. (which shows my ignorance about autotools)

**Comment by HenryMiller1** [comment]
This might just be a matter of someone writing a release document that says what should be done...

**Comment by ossilator** [comment]
you run `autoreconf -i` ...

also, if you just run `make dist`, the necessary files will be included just fine.

**Comment by coolo** [comment]
better make distcheck - which makes sure you didn't forget some _DATA variables :)

**Comment by llunak** [comment]
I've tried to edit the 1.2 release as a draft just to see if I could edit it without changing the date, and that pretty much discarded the original release :(. So I basically had to do the release again, sorry about that. But now the tarballs contain the usual configure stuff.
