### ISSUE TITLE
Remote and local compilation with different processor counts

### ISSUE THREAD

**Issue by MaxSagebaum** [icecc/icecream#459]
If you work on your laptop and you get remote jobs, it might not be a fluent work environment any longer.  Therefore we usually configure only a subset of cores that a available for remote jobs with the -m option of the iceccd process.

If you compile now on you own machine, this margin is no longer required and you could use all of your cores. The problem is that the scheduler will still only use the number of cores that is configured with -m.

Are there some options that we have missed or could this feature be added to icecc?

**Comment by HenryMiller1** [comment]
When building locally you don't want any of your cores used in general. There is a lot of work that cannot be done remotely, and so your local machine will keep all cores busy without doing any compiling. 

-- 
 Henry Miller
 hank@millerfarm.com

**Comment by MaxSagebaum** [comment]
Yes, sure but that is not what I meant.

The scheduler will only keep the specified number of cores busy and not all cores.

**Comment by RedBeard0531** [comment]
At the very least you want your linking to use all cores, and if you use `icerun` you need the scheduler to know about all cores.

**Comment by MaxSagebaum** [comment]
Exactly, but with the -m option also the linking is just done with the number of specified cores.

**Comment by llunak** [comment]
What does "might not be a fluent work environment any longer" mean specifically? I've never noticed that the background compiles would have any noticeable impact on the workflow. The background jobs run at a nice priority, so they shouldn't be a problem for CPU usage, and there's almost no disk I/O. There's no such feature in icecream because AFAIK so far there's never been any (perceived) need for it.

**Comment by MaxSagebaum** [comment]
On most laptops in our group, including mine (i7-7500U),  the GUI process will get stuck and updates to the GUI will stagnate. This makes it impossible to work while external icecc jobs are compiling on the computer.  We are all running a Fedora installation with icecc installed from the standard repositories. I checked the priority on our systems which is 30.

**Comment by llunak** [comment]
20 years and counting and the Linux kernel still can't keep the GUI responsive if there's a low-priority background task, something even the Windows kernel can do. *sigh*

You can try if increasing the nice value makes a difference for you? It's the -nice option passed to iceccd, startup scripts on distributions sometimes provide a way to configure it, or just set it explicitly somehow.

And what is "the priority on our systems which is 30"?

**Comment by llunak** [comment]
No response, closing.
