### ISSUE TITLE
"no response within timeout" with large translation units

### ISSUE THREAD

**Issue by timblechmann** [icecc/icecream#474]
when building large translation units i'm sometimes getting messages like 
```
ICECC[22079] 2019-06-17 10:47:54: no response within timeout
```

this mainly happens with generated c++ unity build files (many lines of code, big object size). it seems that there's a 5 second timeout in the sources. i'm wondering if it would make sense to increase this? or at least expose it to the user?

**Comment by llunak** [comment]
The only "no response within timeout" is in MsgChannel::wait_for_protocol() in services/comm.cpp, which is a timeout when setting up a connection. I find it somewhat unlikely that large compiles would trigger this reasonably often (unless the reason would be the network getting very overloaded). And while the timeout could be increased, there's the question of what would be the downside - it could e.g. cause larger delays with problematic hosts.

**Comment by timblechmann** [comment]
my network is certainly not a "professional" network as i'm using a consumer-grade 5 port gigabit switch to connect 3 laptops. however i'm compiling different projects, i'm often seeing the error on the one with large translation units.

i've done some testing locally, increasing the timeout to 15 seconds, which resolves the issue for me

**Comment by llunak** [comment]
I've raised the timeout to 15 after all, let's see if it causes a problem somewhere.

**Comment by timblechmann** [comment]
@llunak thanks a lot!
