### ISSUE TITLE
Channel for help

### ISSUE THREAD

**Issue by MrD2** [icecc/icecream#479]
IRC? slack or anything related?

**Comment by coolo** [comment]
https://github.com/icecc/icecream#mailing-list

**Comment by MrD2** [comment]
tried to send message to the group and coudn't

**Comment by MrD2** [comment]
Im dropping the message here:

im testing a quick implementation using icecc.

I built a container and im running  4 worker nodes and a controller.
The worker nodes are detected and connected. With icemon i can see the 
icecc tree.

But when compiling, no job is sent to the worker nodes, and the logs 
don't really help
I might be running different worker and scheduller version, but is 
weird since they are installed the same way (on a fedora image)

Any suggestions on what to look for? or common problems?

**Comment by llunak** [comment]
> But when compiling, no job is sent to the worker nodes, and the logs
> don't really help

So what do they say?

**Comment by MrD2** [comment]
>  ninja lldb -j 3
> [1/3553] Building CXX object lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o
> FAILED: lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o 
> icecc /usr/libexec/icecc/bin/g++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Demangle -I/root/dev/llvm-project/llvm/lib/Demangle -I/usr/include/libxml2 -Iinclude -I/root/dev/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o -MF lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o.d -o lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o -c /root/dev/llvm-project/llvm/lib/Demangle/ItaniumDemangle.cpp
> ICECC[7797] 2019-07-06 17:43:25: icecream seems to have invoked itself recursively!
> [2/3553] Building CXX object lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o
> FAILED: lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o 
> icecc /usr/libexec/icecc/bin/g++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Demangle -I/root/dev/llvm-project/llvm/lib/Demangle -I/usr/include/libxml2 -Iinclude -I/root/dev/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o -MF lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o.d -o lib/Demangle/CMakeFiles/LLVMDemangle.dir/Demangle.cpp.o -c /root/dev/llvm-project/llvm/lib/Demangle/Demangle.cpp
> ICECC[7796] 2019-07-06 17:43:25: icecream seems to have invoked itself recursively!
> [3/3553] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o
> FAILED: lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o 
> icecc /usr/libexec/icecc/bin/g++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/root/dev/llvm-project/llvm/lib/Support -I/usr/include/libxml2 -Iinclude -I/root/dev/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o -c /root/dev/llvm-project/llvm/lib/Support/APFloat.cpp
> ICECC[7798] 2019-07-06 17:43:25: icecream seems to have invoked itself recursively!
> ninja: build stopped: subcommand failed.
> 

SOME CONTEXT

`
FROM fedora:31

LABEL maintainer="Diogo Guerra <diogo.filipe.tomas.guerra@cern.ch>"
LABEL author="Diogo Guerra <diogo.filipe.tomas.guerra@cern.ch>"
LABEL description="A icecc image based on alpine for a demo distributed compiler cluster"
ENV LANG=en_US.utf8

# Build environment
RUN dnf install icecream -y && \
    dnf install clang -y && \
    dnf install doxygen -y && \
    dnf install gcc -y && \
    dnf install graphviz -y && \
    dnf install libasan -y && \
    dnf install libasan-static -y && \
    dnf install libedit-devel -y && \
    dnf install libxml2-devel -y && \
    dnf install make -y && \
    dnf install net-tools -y && \
    dnf install python-devel -y && \
    dnf install swig -y && \
    dnf install git bc xz -y

# Compilers
RUN dnf group install "Development Tools" -y && \
    dnf install cmake ninja-build ncurses-devel bison flex elfutils-libelf-devel openssl-devel -y

#ENV CC="/usr/lib/icecc/bin/cc"
#ENV CXX="/usr/lib/icecc/bin/c++"

# Run icecc daemon in verbose mode
ENTRYPOINT ["iceccd","-v"]
#ENTRYPOINT ["icecc-scheduler","-v"]

# iceccd port
EXPOSE 10245 8765/TCP 8765/UDP 8766

# If no-args passed, make very verbose
CMD ["-vvv"]
` 

And then i have same dockerfile but without entrypoint which i use as scheduller.
I run the container, start the icecc-scheduller -d
Im following this https://developers.redhat.com/blog/2019/05/15/2-tips-to-make-your-c-projects-compile-3-times-faster/ to build the llvm with icecream. after downloading the repo to the container i do:

`
cmake ~/dev/llvm-project/llvm \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_USE_LINKER=gold \
  -DLLVM_ENABLE_PROJECTS="lldb;clang;lld" \
  -DCMAKE_C_COMPILER=/usr/libexec/icecc/bin/gcc \
  -DCMAKE_CXX_COMPILER=/usr/libexec/icecc/bin/g++ \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
  -DCMAKE_C_COMPILER_LAUNCHER="icecc" \
  -DCMAKE_CXX_COMPILER_LAUNCHER="icecc"
`

and finally ninja lldb -j 50

**Comment by llunak** [comment]
> > icecc /usr/libexec/icecc/bin/g++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE 
...
> > ICECC[7797] 2019-07-06 17:43:25: icecream seems to have invoked itself recursively!
...
>   -DCMAKE_C_COMPILER=/usr/libexec/icecc/bin/gcc \
>   -DCMAKE_CXX_COMPILER=/usr/libexec/icecc/bin/g++ \
>   -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
>   -DCMAKE_C_COMPILER_LAUNCHER="icecc" \
>   -DCMAKE_CXX_COMPILER_LAUNCHER="icecc"

You are telling cmake to invoke icecream twice.
