### ISSUE TITLE
There are still problems with path canonicalization.

### ISSUE THREAD

**Issue by bwiklak** [icecc/icecream#499]
There are still problems with path canonicalization.
with `-fsanitize-blacklist=../../d/blacklist.txt` it should resolve to `/a/d/balcklist.txt` but is resolved to `/a/b/c/d/blacklist.txt` instead.

_Originally posted by @bwiklak in https://github.com/icecc/icecream/pull/378#issuecomment-527427503_

**Comment by llunak** [comment]
Works fine for with me with current git. Please please a testcase for reproducing the problem.

**Comment by bwiklak** [comment]
Master works, I was checking on version 1.2.
