### ISSUE TITLE
Started Chromium build using icecc process gets killed

### ISSUE THREAD

**Issue by akshay24495** [icecc/icecream#507]
In icemon I could see two system connected but active jobs is 0/16 
1. 12 core machine
2. 4 core machine
![Screenshot from 2019-10-30 12-49-29](https://user-images.githubusercontent.com/32266630/67849494-a9f43f00-fb2c-11e9-878f-fe6beff624e1.png)

No jobs are sent to the build machines. I am using icecream 1.0.1 in 4 core machine and icecream 1.1 in 12 core machine

**Comment by llunak** [comment]
Please update to a more recent version. 1.1 is 2 years old and 1.0.1 is ancient.

If the problem persist using a recent version, run the build with ICECC_DEBUG=debug and provide the debug output.

**Comment by llunak** [comment]
No response, closing.
