### ISSUE TITLE
Failed to access the underlying source code for analysis

### ISSUE THREAD

**Issue by shacker** [icecc/icecream#508]
Under python 3.6, I used `ic()` regularly in my pytest tests to assist with debugging. Now we have switched our project to python 3.8, and I no longer can. It errors with

```
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?
```

Is there something I can do to get it working with pytest / python3.8 again?

**Comment by llunak** [comment]
I have no idea what ic is. Are you sure you've reported your problem in the correct place?

**Comment by coolo** [comment]
-> https://github.com/gruns/icecream

**Comment by shacker** [comment]
Yikes, sorry!
