### ISSUE TITLE
icemon unalbe to connect to specific port

### ISSUE THREAD

**Issue by dibalavs** [icecc/icecream#510]
1) launch icecc-scheduler:
**> icecc-scheduler -p 1234**

2) launch icemon:
**> USE_SCHEDULER=127.0.0.1  icemon**
_scheduler is on 127.0.0.1:8765 (net )
scheduler is on 127.0.0.1:8765 (net )_
Looks like icemon cannot determine correct port.

3) launch icemon with correct ip and port again:
**> USE_SCHEDULER=127.0.0.1:1234 icemon**

_scheduler is on 127.0.0.1: 1234 :8765 (net )
Unknown host Resource temporarily unavailable_

Looks like icemon incorrectly parse URI from USE_SCHEDULER env.

icemon 3.1.0
icecreate-scheduler 1.1
works on ubuntu 18.04

**Comment by HenryMiller1** [comment]
It looks to me like the latest icemon accepts -p on the command line to get the port. 

-- 
 Henry Miller
 hank@millerfarm.com

**Comment by dibalavs** [comment]
Sounds good!.
But what about USE_SCHEDULER env variable?

**Comment by llunak** [comment]
$ ICECC_DEBUG=debug ICECC_SCHEDULER=test:1234 icemon
ICEMON[23348] 2019-11-26 22:21:07: scheduler is on test:1234 (net )
ICEMON[23348] 2019-11-26 22:21:07: Connecting to test failed: Unknown host

So presumably your version is too old.
