### ISSUE TITLE
[icecc-create-env] Unable to specify output name.

### ISSUE THREAD

**Issue by dibalavs** [icecc/icecream#512]
I use icecc-create-env as a part of large build script.
Currently when icecc-create-env produce binary archive, it just print its name to stdout.
And I manually should grep this output, extract archive name and rename archive to something more user-friendly.
I think it will be better to support some flag in icecc-create-env to specify output name. something like:
-output archive.tar.gz
-target archive.tar.gz
-name archive.tar.gz
or something like it.

**Comment by llunak** [comment]
The archive name itself is written to file descriptor 5, if it's open.

But generally it's not needed to run the script, except for cross-compiling, and it shouldn't be such a deal to manually rename the archive when cross-compiling already requires manual setup anyway.

**Comment by dibalavs** [comment]
Yes, you are right it is cross-compiling.
I have large build script which produce SDK, which build next things.
1) cross binutils
2) cross compiler (gcc)
3) a lot of libraries (compiled by gcc from step 2)

When I use icecc-create-env. I use paths to compiler which was build on step 2.
As you understand, each time I run full build, cross compiler will be fully re-build. and need re-generate icecc environment.

Also this SDK is build on the server, which I don't have manual access (unabe to rename manually archive).

Also I do not understand what is a problem to specify output name? all archivers can do it. tar,zip,rar, ...
Why do you close this bug? Is it impossible to implement "by design" ?

**Comment by dibalavs** [comment]
ping

**Comment by llunak** [comment]
You have already several ways of handling this:
- grep the name from stdout
- use fd#5 to get it
- use 'ls' to get the name
And if you really think that icecc-create-env should have an option for this, you can always make a pull request implementing that.
