### ISSUE TITLE
BUG: ccache + icecream + clang -Weverything results in false "warning: macro is not used [-Wunused-macros]"

### ISSUE THREAD

**Issue by ericch1** [icecc/icecream#514]
Hi,

We have a simple but annoying bug with ccache (3.7.1) + icecream + clang 7.0.

This file:

=================

#define UsedMacro double

double foo();

double foo() {
  UsedMacro var = 0;
  return var;
}

=================

Compiles without warnings if compiled with bare clang 7.0 like this:

/usr/bin/clang -Weverything -c t.cc

It compiles also without warnings if I use cache:

ccache -C && /usr/lib64/ccache/clang -Weverything -c t.cc

But If I add export CCACHE_PREFIX=/opt/icecream-1.2/bin/icecc, resulting in this environnement:

CCACHE_PREFIX=/opt/icecream-1.2/bin/icecc
CCACHE_SLOPPINESS=include_file_mtime
CCACHE_HARDLINK=1
CCACHE_DIR=/d1/home/ericc/eric-ccache/

then I have a "false" warning:

ccache -C && /usr/lib64/ccache/clang -Weverything -c t.cc
Cleared cache
t.cc:1:9: warning: macro is not used [-Wunused-macros]
#define UsedMacro double
        ^
1 warning generated.

Is it a ccache bug or an icecream bug?

Thanks,

Eric

**Comment by llunak** [comment]
It's actually a Clang bug https://reviews.llvm.org/D65371 . Icecream detects -Wunused-macros and forces (the suboptimal) ICECC_REMOTE_CPP=0, but -Weverything is not checked. Either use a fixed Clang, disable the warning or try ICECC_REMOTE_CPP=0.

**Comment by ericch1** [comment]
Ok, thanks a lot, I tried  ICECC_REMOTE_CPP=0 and it fixes it! :)
