### ISSUE TITLE
Local daemon/ Freebsd jail/Poudriere Usage

### ISSUE THREAD

**Issue by darkfiberiru** [icecc/icecream#517]
Hello I'm looking at using icecc four freebsd poudriere builds(freebsd ports tree 32000+ packages). Obviously building that much  software takes a lot of resources.

This is a personal project but if I get it working there's a good chance it will be used at my employer iXsystems and other places.

One of the big complaints from poudriere mainteners when distcc was brought up in the past was that poudriere jails are a clean environment for reproducibility including no network connection unless default settings are overridden. 

I saw that you can talk to a local daeamon via sockets. Will that then handle all traffic and proxy everything?

Ideal local icecc daemon on host that is talked to over a unix socket that is passed into jail would be great. Or a way to proxy out to host I guess is an alternative.

**Comment by HenryMiller1** [comment]
I use icecc in a docker all the time. Just make sure the one socket is forwarded from the jail to the host. I think the default is some unix socket in /var, but it will fall back to an ip socket to localhost, but best is if you can figure out what socket that is. Iceccd runs on the host and communicates with the network. I thought I put the required setup in the readme,but I don't see it. 

If you don't figure it out by Monday I'll look up what we do at work.


It would be nice if you can get tests running in freebsd and help us by setting up a ci build.

-- 
 Henry Miller
 hank@millerfarm.com

**Comment by llunak** [comment]
> I saw that you can talk to a local daeamon via sockets. Will that then handle all traffic and proxy everything?

No. Communication related to remote builds themselves (sending the build job, receiving the result) is done directly icecc <-> remote iceccd. And if icecc is jailed, then even the icecc <-> local iceccd communication is done using a localhost socket, because icecc has no way to reach the unix socket. So you'll need to forward outgoing connections to the local iceccd and remote iceccds. I have no practical experience with that though.

**Comment by darkfiberiru** [comment]
Local host sockets can be passed through to FreeBSD jails with out any issues but sounds like I will need to figure out a solution for the icecc to remote-iceccd portion that was my biggest question with this.

**Comment by llunak** [comment]
Technically it would be possible to send that data via the daemon, but normally that's a large amount of data, so doing that would presumably affect performance. So I really suggest just forwarding the network traffic, and I don't see a big difference between talking to a local or remote iceccd. I'm going to close this, unless you have really strong reasons.
