### ISSUE TITLE
iceccd cannot automatically find a scheduler with firewall enabled

### ISSUE THREAD

**Issue by torokati44** [icecc/icecream#521]
I found out that opening all the listed TCP and UDP ports on a "worker" machine is not enough for it to automatically find a scheduler by broadcasting.

It seems that the scheduler responds to the discovery message addressing the same (ephemeral, high-range) port the message was sent from. This is always different, so it's not trivial to open it on a firewall.

**How I discovered this:**
My machine and another one on the same network were both running iceccd as well as the scheduler. All version 1.3.1. All machines' daemons on the network, except mine, were connected to the other scheduler. My daemon was the only one on my scheduler. The NETNAME was the same for both schedulers and all daemons.
Then I stopped my scheduler, just to check if then the daemon finds the other one (and it's not just about the "best scheduler" selection algorithm being broken).
I could inspect that other scheduler with icemon just fine, by manually entering its IP address, and my daemon could also connect to it when I entered its address manually. Only the discovery didn't work.
Then I started examining the network traffic on my machine with Wireshark, and found 3 broadcast discovery responses, and 3 replies from all running schedulers. Except they were dropped by my firewall later, because they were destined to that ephemeral port which is not open.
Once I allowed all incoming traffic through my firewall, either from that single other host, or from the entire local subnet, my iceccd immediately and automatically connected to the other scheduler.

**Suggestions:**
Perhaps the broadcast messages from the daemon should be originated from one of the specified UDP ports; or the reply from the scheduler should not be sent to the ephemeral source port, but instead a fixed, known one, which is mentioned in the README, so can be opened up? Or maybe something like UPnP would solve this somehow?

**Comment by llunak** [comment]
I'm not an expert on firewalls or UDP, but I think it is not possible to specify a source port for UDP messages (e.g. the example in 'man getaddrinfo' specifies only the remote port), so how would you expect this to work?
And firewalld on my openSUSE 15.1 seems to handle this fine, the config file just specifies that 8765 is the remote port:
`
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Icecream compiler daemon (iceccd)</short>
  <description>Icecream is a distributed compiler daemon. Enable this option if this host is a compile node.</description>
  <port protocol="tcp" port="10245"/>
  <source-port port="8765" protocol="udp"/>
</service>
`

**Comment by ossilator** [comment]
of course it's possible, just bind() the udp socket like you'd do for tcp listening.

**Comment by llunak** [comment]
I stand corrected.
But it still doesn't work in practice, as each broadcaster needs a port, so a machine running both the scheduler and iceccd would have the port used by whoever gets it first. And the set of needed ports is not even a limited number, icemon can be running too, or even several of them. So the 'without it getting complicated part' still applies.
But patches are welcome, if somebody feels like sorting this out is less work than getting the right firewall setup.

**Comment by torokati44** [comment]
Yeah, allowing in traffic _originating from_ the listed ports indeed fixes scheduler discovery. I only opened them up as _destination_ ports. Somehow this "given remote source port to any local destination port" policy seems... strange... - maybe even unwise(?) to me. But I'm not that knowledgeable in this topic, and honestly, it'll work for me.

Now I see that this (the need to allow in traffic from _source_ ports) is mentioned in https://github.com/icecc/icecream#firewall, but I only looked at the https://github.com/icecc/icecream#network-setup-for-icecream-firewalls section, since I'm not running SuSEfirewall2.

Thanks for the hints!

**Comment by llunak** [comment]
> Yeah, allowing in traffic _originating from_ the listed ports indeed fixes scheduler discovery. I only opened them up as _destination_ ports. Somehow this "given remote source port to any local destination port" policy seems... strange... - maybe even unwise(?) to me.

Note that the README says not to use Icecream in untrusted networks, so that issue is already covered by that.

**Comment by torokati44** [comment]
This is technically correct, and I don't blame you for not prioritizing security. It is usually way too much effort.
Again, the only thing I was confused by, is what rules I should configure on my firewall (if my trust in the network has limits, so I'd rather not turn it off entirely).
