### ISSUE TITLE
icecream 1.3.1-1 (from AUR) disconnects with `scheduler dead ?!` message

### ISSUE THREAD

**Issue by milianw** [icecc/icecream#523]
Hey there,

since a few days my icecream setup is completely broken. My local `iceccd` keeps disconnecting from the cluster and the log file only contains the message `scheduler dead ?!`. Restarting `iceccd` makes it work for a short time before it then disconnects again with that message. The daemon keeps running - it doesn't crash...

Any suggestions on how to debug that would be welcome.

In strace I'm seeing things like:
```
read(63, 0x557cdda1e900, 128)           = -1 EAGAIN (Resource temporarily unavailable)
wait4(-1, 0x7ffd9cea63a4, WNOHANG, NULL) = -1 ECHILD (No child processes)
...
accept(6, {sa_family=AF_UNIX}, [16->2]) = 16
setsockopt(16, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(16, SOL_TCP, TCP_KEEPIDLE, [27], 4) = -1 EOPNOTSUPP (Operation not supported)
setsockopt(16, SOL_TCP, TCP_KEEPINTVL, [3], 4) = -1 EOPNOTSUPP (Operation not supported)
setsockopt(16, SOL_TCP, TCP_KEEPCNT, [3], 4) = -1 EOPNOTSUPP (Operation not supported
...
read(16, 0x557cdda12cf0, 128)           = -1 EAGAIN (Resource temporarily unavailable)
wait4(-1, 0x7ffd9cea63a4, WNOHANG, NULL) = -1 ECHILD (No child processes)
...
read(31, 0x557cdda1b0e0, 128)           = -1 EAGAIN (Resource temporarily unavailable)

```

**Comment by milianw** [comment]
hmm it seems like a reboot of the machine has helped, maybe a kernel update interfered with some networking functionality? one way or another, this does hint at a lack of error reporting in some place I believe...

**Comment by llunak** [comment]
Maybe, but this information is far from being enough to even guess what was wrong. You'd most probably need to debug it yourself. Can you still reproduce the problem?

**Comment by milianw** [comment]
No... it now works but if I run into it again - what should I look at to debug it? I could also try to create an `rr` record and upload it - potentially that would help. But then I'd also need to compile iceccd from sources with debug symbols. Anyhow, if you have any input on what to look at that would be interesting. As I said, the above was completely mysterious to me - and the lack of information by the tool made it hard for me to inspect what's going on.

**Comment by llunak** [comment]
As I said, from this description I have no idea. You might have had a kernel update that needed a reboot, or simply anything.
As far as information by the tool, icecream is actually quite talkative if you run it with -v -v -v, and it's usually a good idea to check and/or include here a logfile for such problems. That's the first thing to look at.

**Comment by milianw** [comment]
ah thanks, that's the missing information. so far, I only looked at the log file which only contained the undescriptive error message `scheduler dead ?!` and nothing more. Next time this happens, I'll add the `-v -v -v` flags and run it again - thanks! Will reopen once that happens, will close this report for now.

Cheers
