### ISSUE TITLE
Unable to compile chromium by using Icecc and failes with error 14

### ISSUE THREAD

**Issue by himanshumadhavani2611** [icecc/icecream#525]
Trying to build chromium using icecc mac os and linux host. 
Able to get the schedular and linux system on the icemon, however initially I see blob of work starting, however it drops and fails. 

Below are messages with debug output

ICECC[53677] 17:08:08: connected to /var/run/icecc/iceccd.socket
ICECC[53677] 17:08:08: env: x86_64 '/Users/fayaz-macbook/work/boardre/chromium/src/clang_darwin_on_linux_332838.tar.gz'
ICECC[53677] 17:08:08: preparing ../../third_party/flac/src/libFLAC/stream_encoder_framing.c to be compiled for Darwin19_x86_64
ICECC[53677] 17:08:24: Have to use host 3.22.xx.197:10245 - Job ID: 24 - env: x86_64 - has env: true - match j: 0
ICECC[53677] 17:08:24: connected to 3.22.xx.197
ICECC[53677] 17:08:27: <send compile_file>
ICECC[53677] 17:08:27: </send compile_file: 0ms>
ICECC[53677] 17:08:27: <write_server_cpp from cpp>
ICECC[53985] 17:08:27: preparing source to send: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/third_party/flac/flac/stream_encoder_framing.o.d -I../../third_party/flac/include -I../../third_party/flac/src/libFLAC/include -I../.. -Igen -isysroot ../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -DFLAC__OVERFLOW_DETECT -DVERSION="1.3.1" -DHAVE_LROUND -DHAVE_INTTYPES_H -D_LIBCPP_HAS_NO_ALIGNED_ALLOCATION -DCR_XCODE_VERSION=1140 -DCR_CLANG_REVISION="n345938-a1762f9c-1" -DCOMPONENT_BUILD -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_DEBUG=0 -DCR_LIBCXX_REVISION=375504 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DFLAC__NO_DLL -fno-strict-aliasing -fstack-protector-strong -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -arch x86_64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O0 -fno-omit-frame-pointer -gdwarf-4 -g2 -Xclang -debug-info-kind=constructor -mmacosx-version-min=10.10.0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-conversion -Wno-unused-const-variable -Wall -Wno-unused-variable -Wno-misleading-indentation -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-pointer-to-int-cast -std=c11 -Wno-implicit-fallthrough -E ../../third_party/flac/src/libFLAC/stream_encoder_framing.c -frewrite-includes
ICECC[53677] 17:08:27: sent 162415 bytes (11%)
ICECC[53677] 17:08:27: </write_server_cpp from cpp: 493ms>
ICECC[53677] 17:08:27: <wait for cpp>
ICECC[53677] 17:08:27: </wait for cpp: 0ms>
ICECC[53677] 17:08:27: <wait for cs>
ICECC[53677] 17:09:35: saw eof without complete msg! 1
ICECC[53677] 17:09:35: </wait for cs: 67592ms>
ICECC[53677] 17:09:35: saw eof without complete msg! 1
ICECC[53677] 17:09:35: got exception Error 14 - error reading message from remote (3.22.xx.197)
ninja: build stopped: subcommand failed.

**Comment by llunak** [comment]
This only says that the remote daemon failed to provide back the compilation result. You need also the log from the remote daemon (-v -v -v options for it).

**Comment by llunak** [comment]
No response, closing.
