### ISSUE TITLE
icecream seems to have invoked itself recursively!

### ISSUE THREAD

**Issue by jlocatelli74** [icecc/icecream#536]
Hello,

I'am use to run icecc for distributed compilation, but after system upgrade from Debian 9 to Debian 10 I've got this error:
ICECC[8260] 2020-06-04 15:58:50: icecream seems to have invoked itself recursively!

It is the same on ubuntu 18.04.

Anybody have an idear for helping me?

Jerome

**Comment by llunak** [comment]
As the error message says, your icecc wrapper invokes itself. So most probably your $PATH is wrong. You can e.g. run your build in "strace -f -e execve [command]" to find out how.

**Comment by jlocatelli74** [comment]
ics@gamma35:~$ strace -f -e execve icecc
execve("/usr/bin/icecc", ["icecc"], 0x7fffb069c1f8 /* 50 vars */) = 0
strace: Process 6776 attached
[pid  6776] execve("/usr/bin/icecc", ["/usr/bin/icecc"], 0x5651b401e1e0 /* 51 vars */) = 0
[pid  6776] +++ exited with 111 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6776, si_uid=1000, si_status=111, si_utime=0, si_stime=0} ---
ICECC[6776] 2020-06-04 17:54:49: icecream seems to have invoked itself recursively!
+++ exited with 111 +++

Do you have an idear?

**Comment by llunak** [comment]
seli@faith:~/tmp> strace -f -e execve icecc g++ a.cpp -c
execve("/usr/bin/icecc", ["icecc", "g++", "a.cpp", "-c"], 0x7ffc4f6ce340 /* 102 vars */) = 0
strace: Process 8686 attached
[pid  8686] execve("/usr/bin/g++", ["/usr/bin/g++", "-c", "a.cpp", "-o", "a.o"], 0x7ffed094d6c8 /* 103 vars */) = 0
...

**Comment by jlocatelli74** [comment]
I've find!! I use colorgcc package.
