### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ericriff** [icecc/icecream#591]
Hi all, 

I can see that version 1.4 has been stuck in `rc` for a while now`.
Are there any plans of making it an actual release soon?

Thanks!

**Comment by akorn** [comment]
FWIW, I've packaged the latest git snapshot for my own use and have been using it in production for years. I also think it's ready for release.

**Comment by coolo** [comment]
I'm here to make whoever volunteers repo owner

**Comment by akorn** [comment]
Here's hoping someone steps forward. icecream is pretty useful; I'd hate to see it disappear. (I can't take over myself, though. Just adding this comment to clarify that my "thumbs up" reaction to the previous post wasn't an attempt to volunteer.)

**Comment by ppluciennik** [comment]
@llunak is it possible to release new version?
I'm experiencing issues with #527 and from what I've understood it will be available in 1.4.

**Comment by HenryMiller1** [comment]
Does anyone know/remember the process of doing a release?  I did some a few years ago and can do another, but it has been so long I've forgotten what needs to be done...  If @llunak doesn't return soon I'll do this release myself, but I need to figure out the process again.

**Comment by coolo** [comment]
I think you need to tag and then upload additional assets generated from `make dist`

**Comment by ppluciennik** [comment]
@HenryMiller1 could you release new version?

**Comment by HenryMiller1** [comment]
@coolo  @ppluciennik  I attempted to do that.  I can build just fine locally, but when I attempt to build the "make dist" output (that is make distcheck, but also tried elsewhere) I get an error
```make[3]: *** No rule to make target 'icecc-test-env', needed by 'all-am'.  Stop.```

I'm not sure how to investigate that.  (maybe an older version of autosomething?) , so I'm suck for now.

**Comment by coolo** [comment]
Take https://github.com/icecc/icecream/pull/598 for that - and you want to change configure.ac's version section before the tag.

**Comment by HenryMiller1** [comment]
Release 1.4 is now out.

**Comment by ericriff** [comment]
Should we document the release process for future generations?

**Comment by ppluciennik** [comment]
@HenryMiller1 thanks for releasing it.
I've tried to create binaries on my machine, but failed due to #600.
Does it work on linux without my patch?
