### ISSUE TITLE
compile time longer with icecc and extra cores than without

### ISSUE THREAD

**Issue by jamincollins** [icecc/icecream#631]
I'm attempting to speed up a long build by moving it to `icecc`. Aren't we all, right?

However, the builds appear to be taking _longer_ with `icecc` than without.  I'm timing the builds with `time $BUILD_CMD`:

**with** icecc (40 cores, mix and match):
```
real	41m0.320s
user	394m55.541s
sys	28m4.528s
```

**without** icecc (12 core, member of the above 40):
```
real	36m6.670s
user	361m39.386s
sys	17m35.283s

```

The current build systems are a mashup of available hardware I had around but currently total 40 cores, including the original 12 core system timed above.

Any advice or troubleshooting tips would be most appreciated.

**Comment by jamincollins** [comment]
Project/code in question:
https://github.com/SoftFever/OrcaSlicer

**Comment by ossilator** [comment]
that isn't a terribly useful bug report. does it even distribute anything at all? log files? look at some other issues to get an idea.

beyond that, icecc has some architectural limitations that make it somewhat non-competitive nowadays.

also, it's kind of unmaintained. cf. #586.

**Comment by jamincollins** [comment]
> that isn't a terribly useful bug report.

Happy to provide any details you (or anyone else) would like.  I'm very new to `icecc`.  So, I don't know what information would be useful.  I found the fact that the build takes 5 minutes longer with 28 additional cores quite surprising.  So, I figured I'd report what I see as an issue.

> does it even distribute anything at all?

Yes it does:

> beyond that, icecc has some architectural limitations that make it somewhat non-competitive nowadays.

Is there something else you would suggest instead?

**Comment by jamincollins** [comment]
Thank you, I see that `sccache` seems to be the preferred replacement and will look into it.

**Comment by HenryMiller1** [comment]
It is really hard to diagnose these issues at best. I'm not surprized you see things like this as a icecc uses a lot of network bandwidth and often will saturate your network. Your 12 core machine could be limited by disk speed or memory bandwith not cpu - in either case there isn't anything icecc could do for you. 

Icecc was designed in days when computers were slower and had one or maybe two cores. the hardware available to most of us is much faster and so icecc often cannot help. 

--
  Henry Miller
  ***@***.***
