### ISSUE TITLE
Compiling WebKit on MacOS

### ISSUE THREAD

**Issue by ragner** [icecc/icecream#71]
I am trying to compile WebKit project on MacOS with icecc support.
I made two patches on my "for-mac" branch but they aren't woking :)

https://github.com/ragner/icecream/commits/for-mac

The compilation starts "well" but after a while a get the following error message:

CompileC /Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/Objects-normal/x86_64/udis86.o disassembler/udis86/udis86.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/ragner/Workspace/Repositories/WebKit/Source/JavaScriptCore
    setenv LANG en_US.US-ASCII
    /usr/local/libexec/icecc/bin/clang -x c -arch x86_64 -fmessage-length=0 -std=gnu99 -Wno-trigraphs -fpascal-strings -O3 -Werror -Wno-missing-field-initializers -Wmissing-prototypes -Wno-return-type -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-enum-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wnewline-eof -DNDEBUG -DHAVE_DTRACE=1 -DWEBKIT_VERSION_MIN_REQUIRED=WEBKIT_VERSION_LATEST -DHAVE_HEADER_DETECTION_H -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.8 -g -fvisibility=hidden -Wno-sign-conversion -I/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/JavaScriptCore.hmap -I/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release/include -I/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release/DerivedSources/JavaScriptCore -I. -Iicu -I/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/DerivedSources/x86_64 -I/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/DerivedSources -Wall -Wextra -Wcast-qual -Wchar-subscripts -Wextra-tokens -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wpacked -Wpointer-arith -Wredundant-decls -Wundef -Wwrite-strings -Wexit-time-destructors -Wglobal-constructors -Wtautological-compare -F/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release -include /Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/PrecompiledHeaders/JavaScriptCorePrefix-cvbmncevuhmwsbfybcsnvapqaoce/JavaScriptCorePrefix.h -MMD -MT dependencies -MF /Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/Objects-normal/x86_64/udis86.d --serialize-diagnostics /Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/Objects-normal/x86_64/udis86.dia -c /Users/ragner/Workspace/Repositories/WebKit/Source/JavaScriptCore/disassembler/udis86/udis86.c -o /Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/JavaScriptCore.build/Release/JavaScriptCore.build/Objects-normal/x86_64/udis86.o
In file included from <stdin>:1:
In file included from /Users/ragner/Workspace/Repositories/WebKit/Source/JavaScriptCore/disassembler/udis86/udis86.c:30:
In file included from /Users/ragner/Workspace/Repositories/WebKit/Source/JavaScriptCore/config.h:39:
/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release/usr/local/include/wtf/Platform.h:550:5: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
# if __MAC_OS_X_VERSION_MIN_REQUIRED >= 1070

```
^
```

/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release/usr/local/include/wtf/Platform.h:557:5: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
# if __MAC_OS_X_VERSION_MIN_REQUIRED >= 1080

```
^
```

/Users/ragner/Workspace/Repositories/WebKit/WebKitBuild/Release/usr/local/include/wtf/Platform.h:678:22: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
# if PLATFORM(IOS) || __MAC_OS_X_VERSION_MIN_REQUIRED >= 1060

```
                 ^
```

Could anyone help me with that patches?

**Comment by llunak** [comment]
As said above, I have no access to Mac, so I cannot debug this. Since this is very old, I assume this is outdated now. So closing, sorry. If you still have a problem, please reopen or file a new issue.
