### ISSUE TITLE
OSX 10.9 mavericks and xcode 5: icecc --build-native uses wrong paths for some tools, fails

### ISSUE THREAD

**Issue by ec1oud** [icecc/icecream#79]
$ icecc --build-native
adding file /bin/true=/usr/bin/true
adding file /usr/lib/libSystem.B.dylib
adding file /usr/lib/system/libcache.dylib
adding file /usr/lib/system/libsystem_pthread.dylib
adding file /usr/lib/system/libsystem_kernel.dylib
adding file /usr/lib/system/libsystem_platform.dylib
adding file /usr/lib/system/libdyld.dylib
adding file /usr/lib/system/libsystem_malloc.dylib
adding file /usr/lib/system/libcompiler_rt.dylib
adding file /usr/lib/system/libunwind.dylib
adding file /usr/lib/system/libsystem_c.dylib
adding file /usr/lib/system/libsystem_m.dylib
adding file /usr/lib/system/libdispatch.dylib
adding file /usr/lib/system/libsystem_blocks.dylib
adding file /usr/lib/system/libsystem_asl.dylib
adding file /usr/lib/system/liblaunch.dylib
adding file /usr/lib/system/libquarantine.dylib
adding file /usr/lib/system/libmacho.dylib
adding file /usr/lib/system/libcorecrypto.dylib
adding file /usr/lib/system/libxpc.dylib
adding file /usr/lib/system/libsystem_sandbox.dylib
adding file /usr/lib/libobjc.A.dylib
adding file /usr/lib/libauto.dylib
adding file /usr/lib/libc++.1.dylib
adding file /usr/lib/libc++abi.dylib
adding file /usr/lib/libDiagnosticMessagesClient.dylib
adding file /usr/lib/system/libsystem_notify.dylib
adding file /usr/lib/system/libsystem_info.dylib
adding file /usr/lib/system/libsystem_dnssd.dylib
adding file /usr/lib/system/libsystem_network.dylib
adding file /usr/lib/system/libkeymgr.dylib
adding file /usr/lib/system/libcommonCrypto.dylib
adding file /usr/lib/system/libcopyfile.dylib
adding file /usr/lib/system/libremovefile.dylib
adding file /usr/lib/system/libsystem_configuration.dylib
adding file /usr/lib/system/libsystem_stats.dylib
adding file /usr/lib/system/libunc.dylib
adding file /usr/bin/gcc
adding file /usr/lib/libxcselect.dylib
adding file /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
adding file /usr/lib/libicucore.A.dylib
adding file /usr/lib/libz.1.dylib
adding file /usr/bin/g++
ls: cc1: No such file or directory
adding file /usr/bin/cc1=
ls: cc1plus: No such file or directory
adding file /usr/bin/cc1plus=
adding file /usr/bin/as=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/as
adding file /usr/lib/dyld
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
ls: /usr/bin/Apple: No such file or directory
adding file /usr/bin/Apple=
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
ls: /usr/bin/Apple: No such file or directory
adding file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/as/x86_64/as
cp: /usr/bin/cc1=: No such file or directory
cp: /usr/bin/cc1plus=: No such file or directory
cp: /usr/bin/Apple=: No such file or directory
md5: /tmp/iceccenvzUBLyR/usr/bin/Apple=: No such file or directory
md5: /tmp/iceccenvzUBLyR/usr/bin/cc1=: No such file or directory
md5: /tmp/iceccenvzUBLyR/usr/bin/cc1plus=: No such file or directory
creating f633e35470b9ee2701511360c2d05897.tar.gz
tar: usr/bin/Apple=: Cannot stat: No such file or directory
tar: usr/bin/cc1=: Cannot stat: No such file or directory
tar: usr/bin/cc1plus=: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
Couldn't create archive

I built from the git master branch.

**Comment by csaavedra** [comment]
So because you don't have the hardware to reproduce the bug you just close it?

FWIW I can reproduce this too with current master branch.

**Comment by coolo** [comment]
then send a pull request

**Comment by dabrahams** [comment]
@coolo Is that a serious request?  I would gladly buy you a mac if it meant you were going to support that platform.

**Comment by ec1oud** [comment]
Please reopen it.  The fact that nobody got around to fixing it doesn't mean it's not a bug, right?

Yeah there's a chance I could write a patch, maybe; I just didn't get around to it.  Or if you want to propose one, I can test it.

**Comment by HenryMiller1** [comment]
Is this still a problem with the master branch?  I see some commits since this was closed. If it is a problem with master please reopen.
